In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Set pandas display options to show full numbers
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

In [ ]:
# # Reset pandas display options to default (optional)
# pd.reset_option('display.float_format')

---
1.Nhập dữ liệu vào
---

In [ ]:
import pandas as pd

# Assuming the file is a CSV or similar format that pandas can read directly from the Drive path
file_path = '/content/bill_output.xlsx'

# You might need to adjust the read function based on the actual file type
try:
    df = pd.read_excel(file_path)
    display(df.head())
except Exception as e:
    print(f"Error reading file: {e}")
    print("Please check the file path and ensure the file is in a format pandas can read directly.")

,Bill ID,Ngày,User ID,Gender ID,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Category Id
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra xoai hat chia S,1.00,32000.00,NaN
1,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra oi hong dieu tay S,1.00,32000.00,NaN
2,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Yogurt trai cay,1.00,32000.00,NaN
3,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Matcha Da xay S,1.00,39000.00,NaN
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.00,2.00,678fa1cf7fe852c11305676f,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.00,99000.00,NaN

---
2.EDA
---

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98322 entries, 0 to 98321
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Bill ID             98322 non-null  object
 1   Ngày                98322 non-null  object
 2   User ID             98322 non-null  object
 3   Gender ID           75035 non-null  float64
 4   Age ID              50305 non-null  float64
 5   Place ID            98322 non-null  object
 6   Vendor Brand ID     0 non-null      float64
 7   Original Brand Id   0 non-null      float64
 8   Nganh Hang ID       95352 non-null  float64
 9   Spend ID            0 non-null      float64
 10  Khu vực ID          96416 non-null  object
 11  Item Name           98172 non-null  object
 12  Item Number         98265 non-null  float64
 13  Item Price          98265 non-null  float64
 14  Item Category Id    0 non-null      float64
dtypes: float64(9), object(6)
memory usage: 11.3+ MB

In [ ]:
# Số lượng dòng trong df
len(df)

97036

In [ ]:
# Count the number of unique values in the 'Bill ID' column
unique_bill_ids_count = df['Bill ID'].nunique()

# Display the count
print(f"Number of unique Bill IDs: {unique_bill_ids_count}")

Number of unique Bill IDs: 28411

In [ ]:
# Count the number of unique values in the 'Bill ID' column
unique_user_ids_count = df['User ID'].nunique()

# Display the count
print(f"Number of unique User IDs: {unique_user_ids_count}")

Number of unique User IDs: 3513

---
2.a.Xử lý dữ liệu missing
---

In [ ]:
# Drop the specified columns
columns_to_drop = ['Vendor Brand ID', 'Spend ID', 'Original Brand Id ', 'Item Category Id', 'Age ID', 'Gender ID']
df.drop(columns=columns_to_drop, inplace=True)

# Display the info of the DataFrame after dropping columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98322 entries, 0 to 98321
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bill ID        98322 non-null  object
 1   Ngày           98322 non-null  object
 2   User ID        98322 non-null  object
 3   Place ID       98322 non-null  object
 4   Nganh Hang ID  95352 non-null  float64
 5   Khu vực ID     96416 non-null  object
 6   Item Name      98172 non-null  object
 7   Item Number    98265 non-null  float64
 8   Item Price     98265 non-null  float64
dtypes: float64(3), object(6)
memory usage: 6.8+ MB

In [ ]:
import pandas as pd

def missing_values_table(df):
    # Tính số lượng và tỷ lệ missing values
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * mis_val / len(df)

    # Gộp hai cột lại thành bảng
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    mis_val_table.columns = ['Missing Values', '% of Total Values']

    # Lọc các cột có missing values > 0
    mis_val_table_filtered = (
        mis_val_table[mis_val_table['Missing Values'] > 0]
        .sort_values('% of Total Values', ascending=False)
        .round(1)
    )

    print(
        f"Your selected dataframe has {df.shape[1]} columns.\n"
        f"There are {mis_val_table_filtered.shape[0]} columns that have missing values."
    )

    # Lọc các cột không có missing values
    no_missing_cols = mis_val_table[mis_val_table['Missing Values'] == 0].index.tolist()

    if no_missing_cols:
        print("\nCột không bị missing value:", ", ".join(no_missing_cols))
    else:
        print("\nKhông có cột nào đầy đủ dữ liệu (tất cả đều có missing value).")

    print("\nBảng các cột có missing value:")
    display(mis_val_table_filtered)

    return mis_val_table_filtered

In [ ]:
# Drop rows with missing values in the specified columns
df.dropna(subset=['Nganh Hang ID', 'Khu vực ID', 'Item Name', 'Item Number', 'Item Price'], inplace=True)

In [ ]:
# Gọi hàm
missing_values = missing_values_table(df)

Your selected dataframe has 9 columns.
There are 0 columns that have missing values.

Cột không bị missing value: Bill ID, Ngày, User ID, Place ID, Nganh Hang ID, Khu vực ID, Item Name, Item Number, Item Price

Bảng các cột có missing value:

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [ ]:
# Display the info of the DataFrame after dropping rows
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93312 entries, 4 to 98321
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bill ID        93312 non-null  object
 1   Ngày           93312 non-null  object
 2   User ID        93312 non-null  object
 3   Place ID       93312 non-null  object
 4   Nganh Hang ID  93312 non-null  float64
 5   Khu vực ID     93312 non-null  object
 6   Item Name      93312 non-null  object
 7   Item Number    93312 non-null  float64
 8   Item Price     93312 non-null  float64
dtypes: float64(3), object(6)
memory usage: 7.1+ MB

In [ ]:
# Drop duplicate rows
df.drop_duplicates(inplace=True)

In [ ]:
dup_val = df.duplicated().sum()
print(f"Number of duplicate rows: {dup_val}")

Number of duplicate rows: 0

---
2.1.Kiểm tra giá trị ItemNumber
---

In [ ]:
# Thống kê mô tả cho cột 'Item Number'
description = df['Item Number'].describe()
display(description)

count   87763.00
mean        4.15
std       112.93
min        -3.00
25%         1.00
50%         1.00
75%         1.00
max     24124.00
Name: Item Number, dtype: float64

Có xuất hiện trường hợp Item Number <0 nên phải kiểm tra coi thế nào

In [ ]:
# Filter rows where 'Item Number' is less than 0 or equal to 0
negative_item_numbers_df = df[df['Item Number'] <= 0]

In [ ]:
# Tỷ lệ những dòng có ItemNumber <=0
totalItemNumber = len(negative_item_numbers_df)
percentItemNumber = (len(negative_item_numbers_df)/len(df))*100
print(f"Number of ItemNumber<=0 rows: {totalItemNumber}")
print(f"Percentage of ItemNumber<=0: {percentItemNumber:.2f}%")

Number of ItemNumber<=0 rows: 169
Percentage of ItemNumber<=0: 0.19%

Kết quả là có 210 dòng có ItemNumber <=0 (chiếm 0,21% dữ liệu) -> Phương án là xóa những dòng này đi

In [ ]:
# Xóa những dòng có Item Number <0
# Remove rows where 'Item Number' is less than 0
df = df[df['Item Number'] > 0]

In [ ]:
# Thống kê mô tả cho cột 'Item Number' (kiểm tra lại)
description = df['Item Number'].describe()
display(description)

count   87594.00
mean        4.16
std       113.03
min         0.00
25%         1.00
50%         1.00
75%         1.00
max     24124.00
Name: Item Number, dtype: float64

In [ ]:
# Filter rows where 'Item Number' is greater than 20
high_item_number_df = df[df['Item Number'] > 20]

# Display the filtered DataFrame
display(high_item_number_df.head(5))

# Display the number of rows with Item Number > 20
print(f"Number of rows with Item Number > 20: {len(high_item_number_df)}")

,Bill ID,Ngày,User ID,Place ID,Nganh Hang ID,Khu vực ID,Item Name,Item Number,Item Price
491,678e42c28d938b111402b7d9,2025-01-20 19:34:10,673ccf4848defc95a50ab4ab,673cd228cfa8a35edf01f997,5.00,5016fd6c7f8b9ac84200003e,Thit Heo Xay Chuan Ngon Meat Deli - (gam),357.00,146.90
848,678d22a7b26f0b25e708fea4,2025-01-19 23:04:55,677fe62cfb893d87d901344c,678d2298eed7ac7616083867,12.00,5016fd6c7f8b9ac84200002b,HCQ Hydroxychloroquine 200mg 100vien/hop,30.00,4700.00
959,678d03fd51216ef92407b177,2025-01-19 20:54:05,675199df0ab44d11e800bf99,678d03cbf157704c68047ab0,5.00,5016fd6b7f8b9ac842000000,mít thái xẻ miếng,1314.00,21000.00
2448,678a6617c26adad04909756f,2025-01-17 21:15:51,673892bbc6e5ba6f2b0c4345,67626ddd18d1e9e7e1001183,21.00,5016fd6c7f8b9ac842000035,AQUARIUS Nuoc the thao zezo 390ml,24.00,9600.00
3363,67885ba2fd39b94dd80bbe91,2025-01-16 08:06:42,6736c0a4b41787bba8007766,67472980165578e8dc07015f,5.00,5016fd6b7f8b9ac842000000,Nai cuu,142.00,70.00

Number of rows with Item Number > 20: 692

In [ ]:
# Divide 'Item Nummber' by 1000 for rows where 'Item Number' is greater than 100
df.loc[df['Item Number'] > 100, 'Item Number'] = df.loc[df['Item Number'] > 100, 'Item Number'] / 1000
df['Item Number'].describe()

count   87594.00
mean        1.55
std         3.06
min         0.00
25%         1.00
50%         1.00
75%         1.00
max       100.00
Name: Item Number, dtype: float64

---
2.2.Tiền xử lý với Item Price
---

In [ ]:
# Thống kê mô tả cho cột 'Item Price'
descriptionIP = df['Item Price'].describe()
display(descriptionIP)

count        87594.00
mean         99922.23
std        4853545.75
min       -2301000.00
25%          11800.00
50%          29000.00
75%          58000.00
max     1374882569.00
Name: Item Price, dtype: float64

Ở đây có những trường dữ liệu với Price <= 0
-> Cần xem xét đây là những dữ liệu nào

In [ ]:
# Filter rows where 'Item Number' is less than 0 or equal to 0
negative_item_price_df = df[df['Item Price'] <= 0]

# Display the filtered DataFrame
display(negative_item_price_df.head(7))

,Bill ID,Ngày,User ID,Place ID,Nganh Hang ID,Khu vực ID,Item Name,Item Number,Item Price
51,678f9a37a0474d74fe05fc86,2025-01-21 19:59:35,67380c2bf3ccefe0d8060769,673c87acfc422cfe26015b16,3.00,5016fd6c7f8b9ac84200000f,Bao Li Xi,1.00,0.00
90,678f87fd0855b7079a03d75f,2025-01-21 18:41:49,673afb9581219e1b9d0e564d,674c646e72dc678883002b4e,3.00,5016fd6c7f8b9ac84200001a,+ 30% Duong,1.00,0.00
91,678f87fd0855b7079a03d75f,2025-01-21 18:41:49,673afb9581219e1b9d0e564d,674c646e72dc678883002b4e,3.00,5016fd6c7f8b9ac84200001a,+ 30% Da,1.00,0.00
93,678f87b0f564eb1b630ba593,2025-01-21 18:40:32,673b136a7bd7562d240c6432,673c49ecf83ee49ccb09dadc,5.00,5016fd6c7f8b9ac84200003e,+ 30% Đường,1.00,0.00
94,678f87b0f564eb1b630ba593,2025-01-21 18:40:32,673b136a7bd7562d240c6432,673c49ecf83ee49ccb09dadc,5.00,5016fd6c7f8b9ac84200003e,+ 30% Đá,1.00,0.00
103,678f8540beda3c998903e189,2025-01-21 18:30:08,6741cab6495362808f0acd38,674be3c21fb2cd13000570a6,999.00,5016fd6b7f8b9ac842000000,TẶNG PMC DUNG DICH VE SINH,1.00,0.00
148,678f679e52fb2218860bcb1c,2025-01-21 16:23:42,678f4ab0e4ce0869b101025e,678f65f75656f9850507098a,11.00,5016fd6c7f8b9ac84200002f,B.Pepper FL,1.00,0.00

In [ ]:
# Tỷ lệ những dòng có 'Item Price'] <= 0
totalPriceNumber = len(negative_item_price_df)
percentPriceNumber = (len(negative_item_price_df)/len(df))*100
print(f"Number of ItemPrice<=0 rows: {totalPriceNumber}")
print(f"Percentage of ItemPrice<=0: {percentPriceNumber:.2f}%")

Number of ItemPrice<=0 rows: 5752
Percentage of ItemPrice<=0: 6.57%

Kết quả là có 5277 dòng có ItemPrice <=0 (chiếm 5,46% dữ liệu)

-> Đây là những dòng cho thấy là giảm giá hoặc quà tăng

-> Phương án là xóa những dòng này đi và phân tích những dòng này riêng

In [ ]:
# Xóa những dòng có Item Price <0
# Remove rows where 'Item Price' is less than 0
df = df[df['Item Price'] > 0]
df['Item Price'].describe()

count        81842.00
mean        107332.62
std        5021102.66
min              0.16
25%          15000.00
50%          31000.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

In [ ]:
# Thống kê mô tả cho cột 'Item Price' (kiểm tra lại)
descriptionIP = df['Item Price'].describe()
display(descriptionIP)

count        91410.00
mean        103143.38
std        4753551.42
min              0.16
25%          15000.00
50%          30000.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

Một điểm lưu ý:
Đơn vị min của VNĐ là 1 nghìn đồng

-> Những giá trị dưới 1000 thì rất đáng ngờ

-> Lọc ra 2 trường hợp là dưới 1 và dưới 1000

In [ ]:
# Filter rows where 'Item Number' is less than 0 or equal to 0
below1_item_price_df = df[df['Item Price'] < 1]

# Display the filtered DataFrame
display(below1_item_price_df.head(5))

Empty DataFrame
Columns: [Bill ID, Ngày, User ID, Place ID, Nganh Hang ID, Khu vực ID, Item Name, Item Number, Item Price]
Index: []

In [ ]:
# Tỷ lệ những dòng có 'Item Price'] < 1
total1PriceNumber = len(below1_item_price_df)
percent1PriceNumber = (len(below1_item_price_df)/len(df))*100
print(f"Number of ItemPrice<=1 rows: {total1PriceNumber}")
print(f"Percentage of ItemPrice<=1: {percent1PriceNumber:.2f}%")

Number of ItemPrice<=0 rows: 7
Percentage of ItemPrice<=0: 0.01%

Kết quả là có 9 dòng có ItemPrice <=0 (chiếm 5,46% dữ liệu)

-> Đây là những dòng cho thấy tên sản phầm là tiếng anh

-> Đặt ra giả thuyết là có thể những cái này tính bằng USD

-> Phương án là xóa những dòng này đi

In [ ]:
# Xóa những dòng có Item Price <1
# Remove rows where 'Item Price' is less than 1
df = df[df['Item Price'] > 1]
df['Item Price'].describe()

count        81798.00
mean        107390.36
std        5022452.33
min              1.25
25%          15000.00
50%          31000.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

Giờ thì kiểm tra những dòng dữ liệu < 1000 để xem nó là gì ?

Biết đâu đó là do hóa đơn ghi đơn vị tính là (nghìn VND) nên kết quả không ra ?

In [ ]:
# Filter rows where 'Item Number' is less than 0 or equal to 0
below1000_item_price_df = df[df['Item Price'] < 1000]

# Display the filtered DataFrame
display(below1000_item_price_df.head(5))

,Bill ID,Ngày,User ID,Place ID,Nganh Hang ID,Khu vực ID,Item Name,Item Number,Item Price
218,678f389476dd7004100e5abb,2025-01-21 13:03:00,6738221fc69a3c252b01d086,678f383196cb14ba300c3dde,2.00,5016fd6c7f8b9ac84200002f,drink,1.00,88.89
305,678e8b370531c1cbf10cbed1,2025-01-21 00:43:19,6736dbfc70221a573f0733a7,6766c5cc7d9a0ed7aa0f67cc,5.00,5016fd6b7f8b9ac842000000,BANH CREPE MAN,1.00,23.27
306,678e8b370531c1cbf10cbed1,2025-01-21 00:43:19,6736dbfc70221a573f0733a7,6766c5cc7d9a0ed7aa0f67cc,5.00,5016fd6b7f8b9ac842000000,XUC XICH XONG KHOI VI SA,1.00,18.62
491,678e42c28d938b111402b7d9,2025-01-20 19:34:10,673ccf4848defc95a50ab4ab,673cd228cfa8a35edf01f997,5.00,5016fd6c7f8b9ac84200003e,Thit Heo Xay Chuan Ngon Meat Deli - (gam),0.36,146.90
578,678e14b193633a84410f9c0a,2025-01-20 16:17:37,673942b67a159fe0db059c9c,678766183b7450e8ac0041a2,2.00,5016fd6b7f8b9ac842000000,Eggplant dip Tahini,1.00,5.00

In [ ]:
# Tỷ lệ những dòng có 'Item Price' < 1000
total2PriceNumber = len(below1000_item_price_df)
percent2PriceNumber = (len(below1000_item_price_df)/len(df))*100
print(f"Number of ItemPrice<=1000 rows: {total2PriceNumber}")
print(f"Percentage of ItemPrice<=1000: {percent2PriceNumber:.2f}%")

Number of ItemPrice<=1000 rows: 1301
Percentage of ItemPrice<=1000: 1.59%

Ta thấy những dòng < 1000 thì đó là do hóa đơn ghi đơn vị tính là (nghìn VND)

-> Những dòng đó sẽ được * 1000 để chuyển đổi về đơn vị tính là VND

In [ ]:
# Multiply 'Item Price' by 1000 for rows where 'Item Price' is less than 1000
df.loc[df['Item Price'] < 1000, 'Item Price'] = df.loc[df['Item Price'] < 1000, 'Item Price'] * 1000
df['Item Price'].describe()

count        81798.00
mean        109615.03
std        5022525.87
min           1000.00
25%          15000.00
50%          31800.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

In [ ]:
# Thống kê mô tả cho cột 'Item Price' (kiểm tra lại)
descriptionIP = df['Item Price'].describe()
display(descriptionIP)

count        91362.00
mean        105335.84
std        4754877.52
min           1000.00
25%          15000.00
50%          31000.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

---
2.3.Xử lý các hóa đơn nghi ngờ
---

- Thông qua file ggcolab DetectAnomoly mà chúng ta xác định được có những trường hợp spam bill

- Rule để xác định đó là spam bill

Cùng userID cùng PlaceID và cùng trong một ngày

-> Hướng xử lý

Giữ lại một bill, những bill còn lại xóa đi

In [ ]:
import pandas as pd

# Đọc lại file những bill bị đánh giá gian lận
file_path = '/content/fraud_cases (1).xlsx'

# You might need to adjust the read function based on the actual file type

fc = pd.read_excel(file_path)
display(fc.head(2))

,User ID,Ngày_only,Place ID,bill_problem
0,5ed144dc408a530b088b4568,2025-01-04,6777839cd95b0c5a860880b4,"['677953ac76f9aa67f50d2bbd', '6779544e01f65365..."
1,643e6a450b819b09920cae65,2024-09-12,66e284bd1aed5e44ca0342fa,"['66e286f2c6bd30306f03b6bc', '66e2871b6f99b219..."

In [ ]:
# Extract the Bill IDs to be removed from the 'bill_problem' column in fc
bill_ids_to_remove = []
for index, row in fc.iterrows():
    bill_list = eval(row['bill_problem']) # Use eval to convert the string representation of a list to a list
    if len(bill_list) > 1:
        bill_ids_to_remove.extend(bill_list[1:])

# Remove rows from df where 'Bill ID' is in the list of bill_ids_to_remove
df = df[~df['Bill ID'].isin(bill_ids_to_remove)]

# Display the first few rows of the modified DataFrame
display(df.head())

,Bill ID,Ngày,User ID,Place ID,Nganh Hang ID,Khu vực ID,Item Name,Item Number,Item Price
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,678fa1cf7fe852c11305676f,5.00,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.00,99000.00
5,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,678fa1cf7fe852c11305676f,5.00,5016fd6c7f8b9ac842000027,MIRINDA Nước ngọt soda kem 320ml,1.00,57000.00
6,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,678fa1cf7fe852c11305676f,5.00,5016fd6c7f8b9ac842000027,COCA-COLA Nước ngọt coca 390ml,1.00,7800.00
7,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,678fa1cf7fe852c11305676f,5.00,5016fd6c7f8b9ac842000027,LỘC XUÂN an khang 663g,1.00,154000.00
8,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,678fa1cf7fe852c11305676f,5.00,5016fd6c7f8b9ac842000027,TH Trà xanh vị chanh 350ml,1.00,9700.00

In [ ]:
# Count the number of unique values in the 'Bill ID' column
unique_bill_ids_count = df['Bill ID'].nunique()

# Display the count
print(f"Number of unique Bill IDs: {unique_bill_ids_count}")

Number of unique Bill IDs: 25322

---
2.4.Xử lý ngày (tách thành date và time)
---

In [ ]:
# Convert 'Ngày' column to datetime objects
df['Ngày'] = pd.to_datetime(df['Ngày'])

# Extract date and time into new columns
df['date'] = df['Ngày'].dt.date
df['time'] = df['Ngày'].dt.time

# Display the first few rows with the new columns
display(df.head())

,Bill ID,Ngày,User ID,Gender ID,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Category Id,Item Number Clean,Item price clean,date,time
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra xoai hat chia S,1.00,32000.00,NaN,1.00,32000.00,2025-01-21,20:35:56
1,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra oi hong dieu tay S,1.00,32000.00,NaN,1.00,32000.00,2025-01-21,20:35:56
2,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Yogurt trai cay,1.00,32000.00,NaN,1.00,32000.00,2025-01-21,20:35:56
3,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Matcha Da xay S,1.00,39000.00,NaN,1.00,39000.00,2025-01-21,20:35:56
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.00,2.00,678fa1cf7fe852c11305676f,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.00,99000.00,NaN,1.00,99000.00,2025-01-21,20:35:23

---
3.Xuất thành file excel để phân tích
---

In [ ]:
# Export the DataFrame to an Excel file
output_file_path = '/content/bill_output_processed.xlsx'
df.to_excel(output_file_path, index=False)

print(f"DataFrame exported to {output_file_path}")

DataFrame exported to /content/bill_output_processed.xlsx