In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

---
1.Nhập dữ liệu vào
---

In [ ]:
import pandas as pd

# Assuming the file is a CSV or similar format that pandas can read directly from the Drive path
file_path = '/content/drive/MyDrive/TT_DAIntern_Vidimi/Bản sao của Bản sao của checkin-raw-data.xlsx'

# You might need to adjust the read function based on the actual file type
try:
    df = pd.read_excel(file_path)
    display(df.head())
except Exception as e:
    print(f"Error reading file: {e}")
    print("Please check the file path and ensure the file is in a format pandas can read directly.")

,Bill ID,Ngày,User ID,Gender ID,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh hang,Khu vực ID,Items,Item Clean,Prompt,DataPrompt,LabelIndustry
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Tra xoai hat chia...",#ERROR!
1,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.0,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,5016fd6c7f8b9ac842000027,"name: Bánh đậu xanh sen vàng Từ vị RVHG 400g, ...",Bánh đậu xanh sen vàng Từ vị RVHG 400g\nMIRIND...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Bánh đậu xanh sen...",NaN
2,678fa1fb3f8de9d2bf05ad8c,2025-01-21 20:32:43,67504c68aeabe321fc06ed1e,1.0,NaN,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Tra xoai hat chia...",NaN
3,678fa1f929f5fc9bcc060be2,2025-01-21 20:32:41,6738e099301699a63a0e6b0a,1.0,3.0,675d869f7985b4c10f05f7f1,NaN,NaN,1.0,5016fd6b7f8b9ac842000000,"name: Freeze Tra Xanh L, slg: 1, price: 69000\...",Freeze Tra Xanh L\nCookies & Cream M,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Freeze Tra Xanh L...",NaN
4,678fa1d529f5fc9bcc060ba1,2025-01-21 20:32:05,677e5bc6a48a0fc903087979,2.0,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,5016fd6c7f8b9ac842000027,name: RICHY banh hop giay quai xach 412g 89362...,RICHY banh hop giay quai xach 412g 89362262000...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""RICHY banh hop gi...",NaN

---
2.Biến đổi dữ liệu file check in raw
---

---
2.1. Xóa những dòng mà Items là null hoặc không có slg

In [ ]:
# Filter out rows where 'Items' is null or does not contain 'slg'
df_filtered = df[df['Items'].notna() & df['Items'].str.contains('slg', na=False)]

# Display the head of the filtered DataFrame
display(df_filtered.head())

,Bill ID,Ngày,User ID,Gender ID,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh hang,Khu vực ID,Items,Item Clean,Prompt,DataPrompt,LabelIndustry
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Tra xoai hat chia...",#ERROR!
1,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.0,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,5016fd6c7f8b9ac842000027,"name: Bánh đậu xanh sen vàng Từ vị RVHG 400g, ...",Bánh đậu xanh sen vàng Từ vị RVHG 400g\nMIRIND...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Bánh đậu xanh sen...",NaN
2,678fa1fb3f8de9d2bf05ad8c,2025-01-21 20:32:43,67504c68aeabe321fc06ed1e,1.0,NaN,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Tra xoai hat chia...",NaN
3,678fa1f929f5fc9bcc060be2,2025-01-21 20:32:41,6738e099301699a63a0e6b0a,1.0,3.0,675d869f7985b4c10f05f7f1,NaN,NaN,1.0,5016fd6b7f8b9ac842000000,"name: Freeze Tra Xanh L, slg: 1, price: 69000\...",Freeze Tra Xanh L\nCookies & Cream M,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""Freeze Tra Xanh L...",NaN
4,678fa1d529f5fc9bcc060ba1,2025-01-21 20:32:05,677e5bc6a48a0fc903087979,2.0,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,5016fd6c7f8b9ac842000027,name: RICHY banh hop giay quai xach 412g 89362...,RICHY banh hop giay quai xach 412g 89362262000...,"Cho một mảng dữ liệu sau: \n""<câu>"".\n### Role...","Cho một mảng dữ liệu sau: \n""RICHY banh hop gi...",NaN

In [ ]:
print(f"Số lượng dòng sau khi lọc: {len(df_filtered)}")

Số lượng dòng sau khi lọc: 28692

---
2.2.Tách chữ ra để có dữ liệu train

In [ ]:
import re

def extract_item_names(items_string):
    if pd.isna(items_string):
        return ""
    # Split the string by newline characters
    items_list = items_string.split('\n')
    extracted_names = []
    for item in items_list:
        # Find the part after "name: " and before ", slg"
        match = re.search(r'name: (.*?),\s*slg', item)
        if match:
            extracted_names.append(match.group(1).strip())
        else:
            # If the pattern doesn't match, try to extract just the name part
            name_match = re.search(r'name: (.*)', item)
            if name_match:
                extracted_names.append(name_match.group(1).strip())

    # Join the extracted names with a newline character
    return '\n'.join(extracted_names)

# Apply the function to the 'Items' column of the filtered DataFrame
# Use .loc to avoid SettingWithCopyWarning
df_filtered.loc[:, 'Extracted_Items'] = df_filtered['Items'].apply(extract_item_names)

# Display the head of the DataFrame with the new column
display(df_filtered[['Items', 'Extracted_Items']].head())

/tmp/ipython-input-2594561217.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.loc[:, 'Extracted_Items'] = df_filtered['Items'].apply(extract_item_names)

,Items,Extracted_Items
0,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...
1,"name: Bánh đậu xanh sen vàng Từ vị RVHG 400g, ...",Bánh đậu xanh sen vàng Từ vị RVHG 400g\nMIRIND...
2,"name: Tra xoai hat chia S, slg: 1, price: 3200...",Tra xoai hat chia S\nTra oi hong dieu tay S\nY...
3,"name: Freeze Tra Xanh L, slg: 1, price: 69000\...",Freeze Tra Xanh L\nCookies & Cream M
4,name: RICHY banh hop giay quai xach 412g 89362...,RICHY banh hop giay quai xach 412g 89362262000...

2.3. Kết nối các dữ liệu để thành prompt cho gemini

In [ ]:
# Create a new DataFrame with 'Bill ID' and 'Extracted_Items' columns
df_for_gemini = df_filtered[['Bill ID', 'Extracted_Items']].copy()

# Format the data into the desired string format for each row
def format_for_gemini(row):
    bill_id = row['Bill ID']
    extracted_items = row['Extracted_Items']
    # Split the items string by newline and join with newline again
    formatted_items = extracted_items.replace('\n', '\n')
    return f"*{bill_id}\n{formatted_items}"

# Apply the formatting function to each row to create a new column
df_for_gemini['Formatted_Data'] = df_for_gemini.apply(format_for_gemini, axis=1)

# Display the head of the DataFrame with the new formatted column
display(df_for_gemini.head())

,Bill ID,Extracted_Items,Formatted_Data
0,678fa2bcc81cf2c7e5059ff2,Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,*678fa2bcc81cf2c7e5059ff2\nTra xoai hat chia S...
1,678fa29b6cebc373bb047d9a,Bánh đậu xanh sen vàng Từ vị RVHG 400g\nMIRIND...,*678fa29b6cebc373bb047d9a\nBánh đậu xanh sen v...
2,678fa1fb3f8de9d2bf05ad8c,Tra xoai hat chia S\nTra oi hong dieu tay S\nY...,*678fa1fb3f8de9d2bf05ad8c\nTra xoai hat chia S...
3,678fa1f929f5fc9bcc060be2,Freeze Tra Xanh L\nCookies & Cream M,*678fa1f929f5fc9bcc060be2\nFreeze Tra Xanh L\n...
4,678fa1d529f5fc9bcc060ba1,RICHY banh hop giay quai xach 412g 89362262000...,*678fa1d529f5fc9bcc060ba1\nRICHY banh hop giay...

In [ ]:
# Define the chunk size
chunk_size = 410
# 30 vẫn còn chạy tốt khi wait time là 60s

# Create a list to store the combined strings
formatted_data_chunks = []

# Iterate through the DataFrame in chunks
for i in range(0, len(df_for_gemini), chunk_size):
    # Select the chunk of rows
    chunk = df_for_gemini.iloc[i:i + chunk_size]
    # Join the 'Formatted_Data' column of the chunk with newline characters
    combined_data = '\n'.join(chunk['Formatted_Data'])
    # Append the combined data to the list
    formatted_data_chunks.append(combined_data)

# Display the first few combined chunks as an example
for i, chunk in enumerate(formatted_data_chunks[:2]):
    print(f"--- Chunk {i+1} ---")
    print(chunk)
    print("-" * 20)

--- Chunk 1 ---
*678fa2bcc81cf2c7e5059ff2
Tra xoai hat chia S
Tra oi hong dieu tay S
Yogurt trai cay
Matcha Da xay S
*678fa29b6cebc373bb047d9a
Bánh đậu xanh sen vàng Từ vị RVHG 400g
MIRINDA Nước ngọt soda kem 320ml
COCA-COLA Nước ngọt coca 390ml
LỘC XUÂN an khang 663g
TH Trà xanh vị chanh 350ml
OISHI Snack tôm cay db gói 68g/ 73g
ACECOOK Mì Siukay Hải sản 128g
OISHI Đậu Phộng vị Hải Sản SiêuCay 85g
DYNAMITE Kẹo hbaHscSCL BigBang 120g
Oishi Snack Cá Chua 34gr
*678fa1fb3f8de9d2bf05ad8c
Tra xoai hat chia S
Tra oi hong dieu tay S
Yogurt trai cay
Matcha Da xay S
*678fa1f929f5fc9bcc060be2
Freeze Tra Xanh L
Cookies & Cream M
*678fa1d529f5fc9bcc060ba1
RICHY banh hop giay quai xach 412g 8936226200011
COCA-COLA Nc Zero SS.pet 390ml 8935049500148
*678f9c74165841667a02ded1
Len Bèo 69+
*678f9ab3c8ab5063c90708e1
CHAN GA OGARI 500GR
CHAN GA RUT XUONG DI
ECH LAM SACH
CHIM CUT OGARI
BANH SU DAI 30G*10
MUC XE GION
NEM GION CP 180G
CHEN COM SU TRANG ME
SCU MEN SONG YAKULT
PIZZA MANNA THAP CAM
DAU HAO MAGGI 530G
NG XA MAXKLEEN HUYEN
T. XANH C2 CHANH PET
MK CHAI NUOC GIAT XA
Khuyen mai - Promo
*678f9a8326adf5dab30be644
My Tuong Den Tron
Ga Chien Sot Cay Han Quoc
Com Tron Truyen Thong
Pepsi
*678f9a675797a63bc502d6c7
banh bouchee lotte chocolat vl pho mai hop 162g
tao autumn glory my
xoai uc (kg)
oi dai loan (kg)
le hoang kim
cam nhap khau
*678f9a37a0474d74fe05fc86
Hong Tra Thai Tac Sa Mat Ong
Tra Sua Hongkong
Hong Tra Sua Kim Tuyen
Bao Li Xi
*678f99e6876d885cff03e1f8
Nước khoáng đánh thanh ngọt
Oshi Pillows Cookies
*678f9957afccf0a9e50c8e2a
Xuc xich ngot TQ 500g - (goi)
Khoai tay chien MarQuise 1kg - (soi nho)
*678f9823a93aacb7bc0e2bdd
KOKOLA Banh quy hon hop 700g
JOJO Dau Ha Lan vi Wasabi goi 70g
ANYTIME Keo bac ha 60g
STRONGBOW Cider dark fruit lon 320ml
WMH Bong tay trang tron tui 120 mieng
MEAT DELI Thit heo xay
MEAT Deli Tim ga
*678f9722aaf5226b630b7403
Salad Ca Hoi
Sashimi Bung Ca Hoi
Sashimi Ca Hoi
Set California Dac Biet
COCA
*678f971f4d0e29b8940a2ae7
Tra Dao
Tra Quat Hong Bi
*678f92b030b2cbb6230b6afe
Banh my sandwich Aloha S25-NH
*678f90dc269c176ec905f83b
Hat bi dac biet goi 450g
Keo que thanh an goi 200g
Thac gion giai duy dat 400g
Ngu coc goi 4k - cb30
*678f8d34773aadd2fc04890c
Xoai cat chu vang (300-450gr qua)
Quyt 2PH NK size 42-48 T6
GVF-Le nau NK size 30/32
Chuoi cao (500g-1500g/nai)
C - ST thanh trung Dalatmilk k ho duong 95
Bap ngo ngot
Ot cay 100g TH
Nam kim cham Han Quoc 15g g T34
Trung chim cut hop 16 qua
*678f8c64fdb47dec1e08093c
Kem Vani
*678f8bb3d61fe89da109beca
Espresso sua da
Bac xiu nong
*678f88edf564eb1b630ba7d2
COMBO JAN 168K
SQUID RING 5
*678f87fd0855b7079a03d75f
Tra Xanh Dua
+ 30% Duong
+ 30% Da
*678f87b0f564eb1b630ba593
Trà xanh dứa
+ 30% Đường
+ 30% Đá
*678f8770642a8c54e80fcdf7
CBO Chicken
MK_CBO Chicken 1
MK_Bucket2COB
*678f8540beda3c998903e189
DESBEBE
SEA SALT KEO CHANH MUOI GOI
PMC NATRI CLORID 500ML
PMC NATRI CLORID 500ML
PMC DUNG DICH VE SINH MUI B
TẶNG PMC DUNG DICH VE SINH
*678f7ae7dd4208d7b80eb693
Lau THAI (Lau 2ng)
Vang Dau
Mien Tom Phuket
Tra Da - Au
*678f78af0dd13b566904c071
Cơm chiên hải sản túi 210g
Cơm chiên kim chi và xúc xích túi 210g
*678f788c6d247a9a3c027e3f
Chubby Melting Egg
*678f778561f9f9a7e0039d0a
Cốc tập hút Mumbebe
*678f75c80b636db5010cb04b
Cest Bon Sot Kem Lava 162.4g
B.Custas Tiramisu 12p 276g
B.Solite Swissroll Bo Sua 360g
B.Solite Pn Parmesan 10p 250g
Hat Bi Hb-zxa
Banh Chung Wrf 900g
Mang Cau Muot Ot 123 Farm-xa
Mut Mang Cau 123 Farm-xa
Than Ngoai Bo Oushi Dl 400g
Bitiet L.vai Bo Oushi Dl 400g
Toi Thom Hai Duong
Hanh Cu Do (tim) Vn
*678f75800d017a44f6072237
N.T.KHIET DASANI 500ML ICE
*678f750d0107a5e2020cff0e
N.T.KHIET DASANI 510ML*1CH
*678f74e4662de8246104b6bd
Fuzetea tra chanh voi
Fuzetea tra dao va ha
TEMAKI OMUSUBI
*678f749c1a6a610fa7015178
T3.Fuzetea+ trà chanh vải
T3.Fuzetea+ trà đào và hạ
T3.TEMAKI OMUSUBI
*678f7312e3123952b900b4e3
Hong Tra Sua Nguyen La Tran Chau (L)
*678f6e6d74c5e5b5c60c0e54
Tra Sen Vang Khoai Mon M
Phin Den Da M
Extra Thach Ca Phe
*678f6e4126435a2db7097132
Tra Sen Vang_CN S
*678f6e1ac2194bbf270e7000
Corn toredo
COMBO1
*678f6a1c86ad0392730b1566
Tran chau ngoc trai 330g
Mascarpone Tatua 500g
Ruou rhum 700ml
Cream of tartar 100g
Cafe den G7 2g (KTD)
Bot gia vi Xa xiu Thai Lan Lobo 100g
Banh Sampa Y Vicenzovo 200g
*678f67fb8151028a050c883f
Cone Vani
*678f679e52fb2218860bcb1c
Rice Flava
B.Pepper FL
Fried Chicken
HS Drum Stick
Pepsi L
*678f669e9e1b62765e0f2e47
Fried Chicken
NSC Drum Stick
*678f667c893d0f99810a561a
Fried Chicken NSC Drum Stick
*678f665b56df8cecb602092d
Fried Chicken
NSC Drum Stick
*678f663211052ceaff0573b3
Fried Chicken
NSC Drum Stick
*678f660d894e7d62f90fcb5c
Cone Vani
*678f65ff07ed65342d03bf69
Cone Vanil
*678f65abd725ac017d05ef2d
CBO Sung Tuc 86K
HS Mix
Mi Y Pop (New)
Pepsi R
Burger Shrimp
Pepsi L
Add 2 Taro
*678f651b893d0f99810a5403
CBO Sung Tuc 86K
Fried Chicken
NSC Mix (2 @0.00)
Mi Y Pop (New)
Subtotal
Total Tax
*678f651b0b35689e720bb694
Coleslaw L
*678f64f2d3050d05c30040c0
Eat In
Choco Milk Iced
*678f64a55656f98505070760
Fried Chicken
*678f64804c5af55dae037d4d
Rice Flava
B.Pepper FL
Pepsi L
*678f631bd3050d05c3003da8
Luc tra sua
Tra sua Moc Huong
*678f6280a4fd9dfcde0c3393
Pepsi L
*678f6232d23a0ecd420f776c
Mi Y Ga Ran
NSC Drum Stick
*678f6023ea82a79d28070593
Cafe Sua Da
*678f5f9f3f076665700b611f
WHITE CHEESE CB TWINKLE
WHITE CHEESE BIC
WHITE CHEESE POPCORN
Spaghetti (M)
Coca/Sprite/Fanta - DINE IN
Fries (R)
Add Sauce NM
GTNM 1 PC
GTNM ICB
Sweet Potato 1ST
Sweet potato Cheese ICB
*678f5ba0ce2fd759d3094322
500 Cream cheese custard
*678f57b74e9d38a60e00d89a
CBO Sung Tuc 86K 2 Fried Chicken NSC Mix (2 @ 0.00) Mi Y Pop (New) Pepsi
*678f55d7eff9afd4f10d8d75
Tra Thach Dao L
Tra Thach Dao S (NWSM.TET_BOGOTEA)
*678f4a88f75fcb00880717ae
ORIGINAL YOGURT (Yaua chanh da)
*678f456afb9ae6fde50ce38a
Chanh Da Xay S
*678f42aae4f755f3a3028e0b
Nuoc Khoang Lavie Chai 700ml
Nuoc Khoang Lavie Chai 750ml
*678f3a85e3cb9a7d7e0e295f
Giao hàng - Giay phep lai xe
*678f39733c3e3da67604c35d
Burger Zinger
*678f39408a3b0d47300b1fc3
Burger Flava
*678f39014719fad1a8007e17
Burger Flava
*678f38ca257d03e3c009eb2f
Cone Vani
*678f389476dd7004100e5abb
fries
cold drink
hot choco
kfc
burger
taco
pizza
drink
*678f386576dd7004100e5a5b
Cone Chocolate
*678f38364b306fce830973b8
Burger Shrimp
*678f32d9a36c1738c9083709
AROMATICA Muối Tẩy Tế Bào Chết Da Đầu Hương Thảo Rosemary Scalp Scrub 165g.
AROMATICA Xịt Dưỡng Chân Tóc Hương Thảo Rosemary Root Enhancer 100ml
AROMATICA Quà tặng chăm sóc tóc chiết xuất Hương Thảo Size nhỏ. Tây tế bào chết Mini 30ml
*678f31aff35eef1b0a06e9e7
WMC-Banh my trai bi 200g BTS
*678f3025c91344881d0ad11e
Combo Sườn Cây Đặc Biệt
Lạp Xưởng Tươi
Canh Chua
Sườn Cây Thêm
*678f2a970f4f0e32490f88e1
Tra long nhan
tra Kai dac thom
*678f259bedc63b45e905fa61
Nuoc khoang Thien
Banh My Giam Gia 5
Banh My Giam Gia 6
Banh My Giam Gia 6
Banh My Giam Gia 6
Keo Kopiko Capuchi
*678f21ffcaea2e636f0dd3ef
Tra Oolong kem phuc long (L)
*678f20ebf67c12181e030efa
MI OMACHI SOT BO HAM, GOI 81G
MI OMACHI SUON HAM NGU QUA, GOI 80G
CA VIEN BD
*678f1f2498425bd2b306e263
Atable Banh Su Kem 5 Cai 125g/1
ATABLE Banh Su Dai Tra Xanh 140g
NS Flan Pudding Tra Xanh 90g/1 Hop
NS Flan Pudding So Co La 90g/1
PICHI Kho Ga Xe 50g/1 Goi
KOCORI Kho Heo Chay Toi Ngu Vi 50g
LAY'S STAX Khoai Tay Chien Vi To
*678f1ec52bc93be8e70f987a
Com Ga Vien
*678f1817c5099a55930b6d16
Tran Chau PMD (4V)
*678f17ee5c2bd5a0a30718aa
BE-Combo Vui Don Tet
Hibi So Ri (L)
Oolong Ba La (L)
Tra Sua Chom Chom (L)
*678f0e8e6038423bb502e80e
Gum LOT.Fusen dau hu
Keo DYNA Big.B
Mi Reeva3Mien tom chua cay
*678f0e7eedc15b378a0d6f2c
Banh mi que pate & chia bong
*678f08eb384e025d870a08fc
Tra Sen Vang_CN L
Tra Sen Vang_CN S
*678f08b1c54c56526704cc8c
Chocolate Freeze L
LSM.CEN_FSBOGO?
Chocolate Freeze S
*678f0853c7bf82ab5109846c
PMC Khẩu Trang 3D Trẻ Em Hộp
Tặng PMC Khẩu Trang 3D Trẻ Hộp
*678f03edad2ebdf9a6029b1b
Sap 24 mau thien long CR-C06/DO (hop)
But chi 36 mau sieu nhan HE2000-36 (cai)
*678f02a379e32befe00807d5
mít sấy vinamit gói 100g
*678f02a04a28aa8474059e6f
Ca Hoi Tuoi 650g
*678f0226df41a515bb06e142
mit say vinamit goi 100g
*678f01de4a28aa8474059d2b
mít sấy vinamit gói 100g
*678f018c0ad8390afc05762d
mít sấy vinamit gói 100g
*678f015d0ad8390afc0575d8
mít sấy vinamit gói 100g
*678f014dea91730bdb041881
Nuoc t.Luc CARABAO lon 250ml
Unknown
*678efe0cf2c01053e506d64a
Mít sấy vinamit gói 100g
*678efd9177f9ea43d809fb89
mít sấy vinamit gói 100g
*678efd2ca127849f0e0bd3d3
mit say vinamit goi 100g
*678efcecb42937524b008767
Mít sấy vinamit gói 100g
*678efcbe62d8862ad0042784
Bac Xiu (L)
*678efbd493f52df2d4072af7
mit say vinamit goi 100g
*678efb9577f9ea43d809f91b
mít sấy vinamit gói 100g
*678efb5b66d1852f55068540
mít sấy vinamit gói 100g
*678efb2aaf810ccae908d84c
mít sấy vinamit gói 100g
*678efb2766d1852f550684ba
mít sấy vinamit gói 100g
*678efaf71a75e4b89401a01f
mít sấy vinamit gói 100g
*678efaacc6c4712a140165f6
mít sấy vinamit gói 100g
*678efaa91572599cb405517a
mít sấy vinamit gói 100g
*678efa8266d1852f55068363
EGG TART
CROISSANT
*678efa8092fd4056f704109f
mit say vinamit goi 100g
*678efa661572599cb40550da
Mít sấy vinamit gói 100g
*678efa33c32411b3f00e6b2f
mít sấy vinamit gói 100g
*678efa0ade99bf314a018ab8
mít sấy vinamit gói 100g
*678ef9e42332615fb80e2748
mit say vinamit goi 100g
*678ef9bede99bf314a0189dc
mít sấy vinamit gói 100g
*678ef794e3bd36200c0c3ccf
Matcha Latte (I)
*678ee938a4a15eaeb00af785
HEINEKEN Bia 0.0 lon cao 330ml
TPBS Star Kombucha-Cam dao
TPBS Star Kombucha-Oi hong
SANCKI Dau phong phu mai lac hop 165g
BETAGEN SCU len men tu nhien 400ml
RICOLA Keo muc Chanh & Bac Ha 40g
GLICO Hop banh Pocky 116g
YAKULT Sua chua uon len men 65ml
*678e8b370531c1cbf10cbed1
BANH CREPE MAN
XUC XICH XONG KHOI VI SA
*678e8b18390235041d039042
BANH CREPE MAN
XUC XICH XONG KHOI VI SA
*678e8afa45467985a7063bd7
Nuoc Ion-Kiem Ocany 600Ml
*678e8aa7b3105d86d906df2f
Banh crepe man
Xuc xich xong khoi vi sa
CK the AEON 5% 23275
CK the AEON 5% 19600
*678e8353f9b46a02c607fc29
TRA SUA OLONG KEM TRUNG NUONG (L)
Banh mi bo toi
NUOC EP MIX
*678e821e42137d3a01084094
TEZKIN
*678e6edfda1faf00d00965ff
Bụi II / Nướng Gangbuk 179K
Buffel Pepsi
*678e6adbd10510a93f0a28e0
Trà Ô long Tea plus 45
Trà Ô long Xanh Tea P
*678e69e50c4e9cc9450191f5
COCA COLA ZERO Nuoc Ngot Co Ga K
TH TRUE YOGURT Sua Chua An Ngu C
HTA Co Lo To/1 Goi
VINAMILK Sua Chua Luu Do Collage
VINAMILK Sua Chua An Nha Dam 100g/1 Hop
MILO Lua Mach L 22oz/1 Ly
Giam 10% cho hoa don 59K
*678e63fe15a47bd72806464a
Nho xanh Uc (lon)
Banh Sua chua
Banh mix
Banh Doraemon mini
Bot Ngot Nhat Ajinomoto
Dau Hoa Cai Japan
Hat Nem YouKi Nhat
Banh quy Naziba vi bo
tao hong New
Bot Ngu Coc Han 50goi
*678e62b69b7805526809e72c
cha ba sa vien bach tuoc nt (200gr)
tom vien cook hoa doanh goi 200g
ca trung nguyen con tan hai hoa 200g
kem murino super teen 60g kido
bang ve sinh kotex style lst sieu mong canh dem 35cm
nho mau don
nuoc ep trai cay thach jele vitamin a,c,e goi 150g
kem murino superteen huong dau socola
kem murino super teen socola 60g kido
qua tang g: cha ba sa vien bach tuoc nt(200gr)
qua tang g: tom vien cook hoa doanh goi 200g
qua tang g: bang ve sinh kotex style lst sieu mong canh dem 35cm
*678e626f72817862fe00c172
Bac Xiu Da L
*678e61220a346fd666059f12
MATCHA SỮA GẤU
TRÀ SỮA KHOAI MÔN - M
Trà Sữa Kem Trứng Nướng-M
THÊM TRÂN CHÂU ĐEN
TRÀ SỮA TIRAMISU - M
TRÀ TRÁI CÂY NHIỆT ĐỚI
TRÀ SỮA MATCHA - M
TRÀ ỔI HỒNG
*678e611208ad5c3f9407838f
SCU.m.somg Probi v.quat 5x65
SCU.m.somg Probi d.gang 5x65
TPBS.Phomai BEL.huong dau 78
Kem vat-viet.quat TH.que 50g
N.ep dao VKFRESH hg 1L
B.crac.GERY.phomai hg 20x9g
Banh topokki YOPO.phomai 24C
Keo deo GING.ung mat.ong 125
X.ch.lo lo C.P 250g
Muoi bien COOP Select tsay 1l
NN quat rung 12 Coop Select 3
Chan gio R.Xuong Coop Select
*678e5d7a88cd3c14ea0c2daf
Mi lau Thai bo-3 (to)
Mi kim chi bo-5 (to)
Banh Kimbap (dia)
*678e5c01e7bd5c06ae0f72b6
Chè Muối
Chè Muối size L
*678e5bef6dc139aa44044aee
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml
*678e5bc280bdb153e70ee338
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml
*678e5b8a80bdb153e70ee2dc
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml
*678e5b69e7bd5c06ae0f71a6
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml
*678e5b39fddccf353e05034f
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml
*678e5b37659b04acd10273a1
Tra Sua Bi Dao - 大 瓜牛奶 (Lon 1000cc)
Thach Suong Sao 仙草
Tran Chau Hoang Kim baby
*678e5b1014ce55892907168c
Tra Xanh Hoa Nhai (Lon 1000cc)
Tran Chau Hoang Kim baby x 1
*678e57d446f33359920d5111
VM CjSpg FFR
UP Chili Chicke
Spag
UP BBQ Fries
UP Lrg Pepsi
Fork
Spoon
*678e553279205a491503af2b
Tra Sua O Long (Lon 1000cc)
70% duong
Thach Dua Huong Dao
*678e54376665d0971e09aa2f
SC VNM IT DUONG 100G
SNACK SWING BIT TET
*678e537cbfe4bd6601067ec2
LAVIE Nuoc Khoang 500ml/1 Chai
MAMAPOP Nuoc Co Ga Vi Oi Hong 330ml/1 Lo
LUCKY STAR Top Mo Chay Toi 25g/1 Goi
G Da Ca Trung Muoi 50g/1 Goi
OTTO BM Cha Bong Mayo 62.5g/1 Goi
*678e510ef775f5f351064701
Dau tay Moc Chau (khay) / H
Keo Boom Jelly - Orion / G
Chat tay Vim dam dac (450ml) / CH
*678e4d037ce2bd3aeb059bcf
măng lá tre xanh an thịnh gói 450g (cb)
*678e4ca7c5cbf60b830a4e2b
chanh không hạt (kg)
râu mực nhập khẩu
bí đỏ hồ lô (kg)
xúc xích cocktail xông khói c.p gói 250gr (al)
nấm đùi gà baby hq vi 200gr
trứng cút hộp 30
thịt nạc heo c.p
quà tặng: xúc xích cocktail xông khói c.p gói 250gr (al)
*678e4c7428fbf5c8d60a28b5
muop huong
nuoc rua tay puri huong dau 500ml
bot banh ran ajinomoto vi truyen thong 200gr
banh gau koala huong socola 37g
*678e4c29fbb9327cd70f21b5
bot ngot ajnomoto 454g*40
banh bao nhan thit tho phat goi 250g(cb)
chao ngu qua 3 dieu heo bbq goi 320g (cb)
sua chua uong duong nutimilk hop 100g (cb)
banh kem: banh bao nhan thit tho phat goi 250g(cb)
banh kem: banh bao cp nhan thit heo bbq goi 320g (cb)
*678e4b6128fbf5c8d60a27f0
Bang keo sap quan canh cay
No tu cau ruy bang
Xop cam hoa 10
Tui giay quai xach
Kem canh 8
Kem xukem nhung 19
*678e4b2caabbe3218401ad6a
Lien Tet 18
Lien Tet 10
Nhuy hoa 23
Keo nen
Xop tron cam hoa 4cm x 25cm
Xop tron cam hoa
Kem xi/kem nhung 19
Kem canh 8
*678e4b027c31e1d79e06a0d2
Sữa tươi trân châu đường đen
*678e4ae2aabbe3218401acfb
Dau rong
Dau phu tuyet
Mien bach ngoc
Nam linh chi
Nam tuyet nhi
Bap loi rua
Tra sam thao moc
Set nam tuoi
Set rau tuoi
Dau vi huyet cay
Tau hu ki cuon
Set vien thap cam
Tom phi thuy
Tuy bo
Set bo dac biet
Lau ca chua
Lau truong tho
*678e499dd765d6f21207fcb8
Loai ve 50.000d
*678e48e332366ce6090c7eb9
mì slukay vị hải sản gói 128gr
mì trộn khoai tây omachi xốt spaghetti gói 91g/90g
đùi sụn meatdell gói 300g (cb)
mì hảo hảo tôm xào chua ngọt 75g
mì hảo hảo tôm chua cay 75g
*678e47e37c31e1d79e069e1e
MATCHA SUA GAU
*678e470356fb11712a0592da
Oishi bap ngot 68g
BANH MI ME HAN QUOC
Ca Vien Chien
Xuc Xich Xong Khoi
Banh mi me vi choco
Mama BB xa xiu
*678e46828cd4a6df47040e4a
Tra Sua Kem Trung
Topping Tran Chau Den
*678e45f6e77cf6887307cd50
TRA SUA TIRAMISU - M
*678e451cf2db8e693507b6da
TRA SUA KHOAI MON - M
*678e44a821379f8e0a0ad896
MATCHA SUA GAU
*678e43fa8d938b111402b865
Shopee Food
*678e43db3649303d64051fed
CB322 SW Jun02
UP Chili Chicke
Spag
Comga wVeg
Reg FF
Peach Mango Pie
Lrg 7up
Spoon
Fork
*678e42c28d938b111402b7d9
Thit Heo Xay Chuan Ngon Meat Deli - (gam)
*678e42a2e2bc28e83106598b
R - Bí xanh 35/kg
Phô mai mozzarella 200g
*678e42753649303d64051e8e
Dui Ga Chat Mieng CP - (kg)
Xot gia vi ca ri barona 80g - (goi)
Khoai Tay - (kg)
*678e42503785d5ee3b03496e
Dui Ga Chat Mieng CP - (kg)
GUNG - (kg)
Cu sa - (kg)
*678e3aa839aaf8dcee0e3b72
Dau cove xanh 500g (R) 1163423000015
Coupon 2200000009722
*678e3a2f946a08ed820cb2c3
ADULT
*678e3876a197b0229f08ede8
HAOHAO mi lau nam chay 66g x ly
GS25 Combo Muong Dua Nia x Bo
ACECOOK Cay Kay vi bo 66g x ly
HAOHAO Mi tom chua cay 67g x ly
MODERN Mi Bo ham rau thom 65g x ly
MODERN Mi lau thai tom 65g x ly
HAOHAO Mi tomyum 67g x ly
Omachi mi bo ham co thit 148g x ly
*678e36f3a06b9904d209d9bf
Trà Sữa Bí Đao - 冬瓜
+ Trân Châu Đường Đen 黑糖珍珠
+ Không đá..
+ Khách VIP 3K
Trà Sữa Bí Đao - 冬瓜
+ Trân Châu Đường Đen 黑糖珍珠
+ Khách VIP 3K
*678e3638ee34817d390df28a
Ao Luoi Nu Basic Co Ao Lot
*678e32ca68392383d20c5463
CB_HungKhoi S
Phin Sua Nong S
BMO Ga Pho Mai
Pho Mai Tra Xanh
*678e2c6a8ef0d48e8a0cd48d
BIA TIGER CRYSTAL LON 330ML
BUND
*678e2c48674321eab10eb48d
BIA TIGER CRYSTAL LON 330ML

*678e2c0ca4bad9957a0332a4
BIA TIGER CRYSTAL LON 330ML
*678e2af5f2d548a1400718e6
mực viên fcook hoa doanh gói 200g (cb)
viên hải sản rau củ lc foods gói 200g (cb)
bánh mandu thịt bibigo 175g
quà tặng: bánh mandu thịt bibigo 175g
quà tặng: viên hải sản rau củ lc foods gói 200g (cb)
quà tặng: mực viên fcook hoa doanh gói 200g (cb)
*678e28761e5093a32b08a603
Sua chua VNM koduong
Banh xep thit va bap
Mixaohaohaochoa ngot
Banh xop Richoco 15g
*678e2696ba423f74fc0a0a26
SB-BANH SU KEM 40G*4
SB-BM KHOAI LANG H.NHAN 200G
*678e25ea7b9dfac2c2009c5c
Khoai lang kén
Cháo quẩy
*678e22cf37bde476280b6fb0
thịt nạc heo c.p
*678e214690a272c90907c781
SANCHI Bu Chai Pho Mai Sri Xop Khoi 50g
SANCHI Dau rua Muc duong Cx Xanh 50g
KOKOLA Banh Butter Cookies 450g KM
YOFLLO Kep deo tuoi xoi so4 49g
Karo Banh trung chia bong pho mai 25g
*678e210afaeb121b67018dbe
Xuc Xich Bo Vissai
Ban Mai Dabati Pho Mai
Kem Dua Hau
Kem Sua Tuoi Trai Cay Nun
Kem Celaro Carven
Kem Chanh Tuoi
*678e1bf3ca4703966f0ecf07
HEID ALPENLIEBE H.DA
HEID ALPENLIEBE H.ME
HEID ESPREZZO YANG
BMHR ORAL-B 3D WHIT
BMHR ORAL-B CROSS
Banh da dua Bach
KECM PHU HUONG SU
KECM TRON GA XAO CH
MI YAO YKO INDOMIE
MI YAO YKO INDOMIE
MI TRON KOKE SPAG
MI TRON PEEYA BA
MI TRON PEEYA TOM
MI OPP TRON CHUA CA
MI TRON TUONG DEN B
MI HO BANH THO NAU
BANH C'EST BON TRUNG
PHO KIM BO
TP-KHAN MAT YTS2
TP-KHAN MAT YTS2
*678e1bf05d863d7bed0222c6
THTRUE MILK Sua tuoi TT co duong 220ml
DUTCH LADY Sua tiet trung dau 190ml
*678e182c6714abf2da037897
4 Non-Spicy 1 pc
Chicken Day - Mua 2 tang 2
*678e14b193633a84410f9c0a
Eggplant dip Tahini
Casa Pane
Duck Tajarin
Zucchini
Purezza Still
*678e142922b892beca0be3ce
Trà sữa trân châu kem trứng (L)
Trà thái xanh (L)
Milo trân châu pudding
*678e0d4e57275a71a2011599
Mi Y Sot Cay
XUC XICH THEM
*678e0b096756a51e570133cf
Bac Xiu Da - Ice Coffee w Fresh Milk
Sinh to Thanh long Dau Chuoi - Dragonfruit Banana Strawberry Smoothie
*678e0a6f15ded326820324b2
Hau Vang Han Quoc - Song (Con)
Hau Giong Phap - Song (Con)
Che bien - Nuong Moi (KG)
Che bien - Nau
Khan Lanh (Cai)
*678e09de826c2d614806f044
Thanh SCL Lindt 100g 85% cacao
SCL Meiji 50g black
*678e08b4216b6714fa009206
TRÀ SỮA SOCOLA (M)
Trân châu gia truyền
Thạch phô mai lá dứa
TRÀ SỮA SOCOLA (M)
Trân châu gia truyền
*678e04ff04842e5d3d06e5a2
Luc Tra Chanh Leo(L)
Tra sua Nuong Yihetang(L)
*678e027f663ee72dfb06ea39
nuoc tinh khiet aquafina chai 5l
nuoc tang luc monster energy lon 355ml
mi hao hao tom chua cay 75g
mi cung dinh kool spaghetti xot bo bam hop 105g
nuoc tang luc monster energy lon 355ml (ban kem)
*678e0277af80734f9c0d4c4c
Freeze Tra Xanh L
Freeze Kem May Dau Tam M
*678e01b686478e6ec90f7bc6
Kem socola
Kem chanh leo
Cafe de coco
Tra dao kem sua
Huong duong
Tran chau den
*678e01306e4823e79c0edc38
Matcha Latte (I)
*678e00fa8f771a727e034a0d
Special Menu_Nước ép cam
Special Menu_Matcha Latte
*678df9dee69c139e3a0b4080
combo 3 trái dừa xiêm gọt vỏ
dưa leo baby
hạt nêm meizan thịt, xương ống, tủy, cà rốt gói 1kg
quà tặng: dầu ăn good meal chai 1l*12
*678df9b4cc6bacf4e10c2d8c
combo 3 trái dừa xiêm gọt vỏ
dưa leo baby
hạt nêm melzan thịt, xương ống, tùy, cà rốt gói 1kg
quà tặng: dầu ăn good meal chai 1*12
*678df56870301d75980601eb
Oppa Bubble Trân châu kim cương hộp 350g
Oppa Bubble Trân châu đường đen hộp 350g
NESTLE Nestea trà vải 144g
SOLO Bánh kem bơ sữa 252g T12
ELENE Khăn giấy lau mặt 260 tờ
Mỹ Ngọc. Bánh Pía Sầu Riêng Đậu Xanh 100g
ORIFOOD Bò khô 200g
MINH TIẾN Mực trứng 300g
GYOZA Bánh xếp nhân thịt heo và gà 114g
CHIN-SU Hi Fresh Chả giò hải sản 400g
WINECO Mộng tỏi L1 500gr
WINECO Cải ngồng L1 500gr

In [ ]:
# Print the number of chunks created
print(f"Number of chunks created: {len(formatted_data_chunks)}")

Number of chunks created: 70

---
2.2.Biến đổi dữ liệu file output
---

In [ ]:
import pandas as pd

# Assuming the file is a CSV or similar format that pandas can read directly from the Drive path
file_path = '/content/drive/MyDrive/TT_DAIntern_Vidimi/Bản sao của Bản sao của bill_output.xlsx'

# You might need to adjust the read function based on the actual file type
try:
    df = pd.read_excel(file_path)
    display(df.head())
except Exception as e:
    print(f"Error reading file: {e}")
    print("Please check the file path and ensure the file is in a format pandas can read directly.")

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Tra xoai hat chia S,1.0,32000.0,NaN,NaN
1,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Tra oi hong dieu tay S,1.0,32000.0,NaN,NaN
2,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Yogurt trai cay,1.0,32000.0,NaN,NaN
3,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Matcha Da xay S,1.0,39000.0,NaN,NaN
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.0,NaN,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,NaN,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.0,99000.0,NaN,NaN

In [ ]:
# Gom nhóm theo Bill ID
grouped = df.groupby("Bill ID")["Item Name"].apply(list)

# In ra theo format mong muốn
for bill_id, items in grouped.items():
    print(f"^ {bill_id}")
    for item in items:
        print(item)
    print()  # dòng trống ngăn cách giữa các bill

Streaming output truncated to the last 5000 lines.

^ 67889e248001ea9aab009404
Vé hành khách

^ 67889e9b2e61e13c460e0010
Lau Kim Chi Bo Lon
7UP
Pepsi
Khan Lanh

^ 67889ef0b4f88969d509099b
Lau Kim Chi Bo Lon
7 UP
Pepsi
Khan Lanh

^ 6788a5e46fbef6e58c0f3a4f
PEPSI Khong Calo Vi Chanh 320ml
7UP Soda Chanh 320ml/1 Lon
PEPSI Chen Su Ti 1.25/1 Cai
North-Monthly Jan 25-Tang 1 PE
F2G Coc Non Cham Nam Me /1 Goi
F2G Xoai 200g/1 GOI
COCA COLA ZERO Nuoc Ngot Co Ga L
O'STAR Khoai Tay Chien Vi Rong B
FANTA Nuoc Ngot Huong Nho 320ml

^ 6788a98b97cd78815f0a7f6a
Hải Sản Hoàng Gia - Nướng Phô Mai (Kg)
Tôm Hùm Xanh (Size Đặc Biệt) - Sống (Kg)
Bánh Mì (Ổ)
Ốc Vôi Vôi - Sống (Kg)

^ 6788a9ae36bd2ce8f407c41d
Maki Com Cuon Luon Pho Mai (8 Cuon/Phan) (Phan)
Sushi Ca Hoi (Bung - 5 Mieng/Phan) (Phan)

^ 6788b77fe49f6b2ef807f6ed
CHAN BAP GIO HEO (BINH ON GIA)
BAO DOI KDR COLGATE TIET KIEM O
BAO IN TU HUY CAC LOAI
BUN NANG HUONG GOI 300G (BINH)
BUN NANG HUONG GOI 300G - BINH

^ 6788b82d5d4eec49e90992b8
COSCO KEO SOCOLATE VIEN DA 58G CHOCOLATE CANDY - (HOP)
KEO DEO QIFENG NHAN XI RO BAC HA - (CAI)
KEO DEO HUONG XOAI - (CAI)
KEO DEO LOT VO YUAN CHU ZHI GUO 75G (VI DAO MAT) - (TUI)
KEO DEO LOT VO YUAN CHU ZHI GUO 75G (VI NHO TIM) - (TUI)

^ 6788b873f3b994f4a9090bad
Bach tuoc xao cay
Ga sot teriyaki
Mien tron
Coca
7 Up
Com Tron Bibimbap

^ 6788b9352b3ee321c406f775
Ca phe sua
O long sua

^ 6788b97b7d27adcd0a0835a8
long heo dac biet tren to + chao huyet
nuoc sau
khan lanh

^ 6788b9cfbeebf69c160042b0
GAU/NAM BO DL XX UC-WRF
GAU/NAM BO DL XX UC-WRF
GAU/NAM BO DL XX UC-WRF
GAU/NAM BO DL XX UC-WRF

^ 6788ba3407d20ba0bb017abc
Tuong ca cholinex 2.1kg (Binh)
Banh bao trang (bich)
Xot cham remia BBQ 250ml (chai)
Coi so Diep dong lanh (kg)
Xot BBQ 300g (chai)
Hat Mau Dieu (kg)
Dau dam tron Salad 270g (Chai)
Nuoc cot dua 400ml (Hop)
Vang Da Lat Do (Chai)

^ 6788bbe40343fe83ce058d23
Gio choi bi a

^ 6788bc0af5d83395ae0a7349
Giờ chơi bi a

^ 6788bc290343fe83ce058d9d
Gio choi bi a

^ 6788bc4c2679fffaf80af3f1
Gio choi bi a

^ 6788bc6c6ab3b139ca0618bf
Gio choi bi a

^ 6788bc99f5d83395ae0a7415
Set Shin Short Athletic
Bao Li Xi Tet 2025 - Xap 3 Cai - PK0007-1

^ 6788bd0bfb1dc041020b7bd5
DUNG DỊCH NHỎ MẮT V.ROHTO DRYEYE 13ML BỔ SUNG NƯỚC MẮT NHÂN TẠO
STAR SORE THROAT V/12V

^ 6788be88747ca01b810f0f88
Sôcôla Đá Xay (M)
ORCG_DISCOUNT_20%

^ 6788c0054c6d4138f50d1af3
Tra Hoa Ngu Sac (M)
BMQ Ga Xe Pho Mai

^ 6788c2074c6d4138f50d1d2f
MACARON TONKA & VANILLA
CANNELE
EGG TART
(450ML) OOLONG JASMINE MILK TEA

^ 6788c405723f417cbc075fd0
Trà Sữa Chôm Chôm (L)
Trà Vải (L)

^ 6788c45d3214ece778008757
[FULLBOX - ĐẾ NHẸ] Dép xỏ ngón MALL đế...

^ 6788c484ed821ff5470f51e6
Ao thun baby tee Mono ODIN CLUB
Ao thun baby tee Mono ODIN CLUB
Quan short Puffer Odin Club

^ 6788cccbd19e3226f8034382
Kem xoai dua long
Mousse chanh day

^ 6788cd3285bbbb692203c8e0
Ca phe sua
O long sua

^ 6788cd847d5535b6270a49df
Bac xiu
Croissant trung muoi

^ 6788d59fc796bb898208adac
Tra thai xanh (L)

^ 6788d5d4f40bb849ad064925
Tra sua tran chau kem trung chay (L.)

^ 6788d7accbb5cf36cb03805c
Dau Nanh Simply 1L
Khuyen Mai @70000
Nuoc Mam Nam Ngu Nhan Vang 14N 650ml
Banh Gao Nong Vi Tao Bien 111.3g
Mi Hao Hao Tom Chua Cay 75 Gr
Khuyen Mai @4400
Mi Bo Ham Ottogi 120g
Khuyen Mai @11700
Mi Siukay Bo Cay 127g
Bong Tay Trang Poppuf 2 Cong Dung Tui Zi
Bvs Diana Sieu Tham Than Hoat Tinh SMC 8
Bvs Diana Sieu Tham 29CM 12M

^ 6788d8c8c4e187b8a30ce734
COMBO JAN 78K

^ 6788d8ded24041f83a07b208
Menu CjSpg FFR
Reg Pepsi

^ 6788d8e7d72a8d79d70fd9e9
COMBO JAN 78K

^ 6788d903d24041f83a07b243
Tony's Oolong Sữa (Size L)
Trà Sữa Tony's Mùa Thu (Size M)
Sữa Tươi Chân Châu Đường Đen
Tony's Kem Trứng (Size L)

^ 6788d930964882a00403aa57
Tony's Olong Sua (Size L)
Tra Sua Tony's Mua Thu (Size M)
Sua Tuoi Chan Chau Duong Den
Tony's Kem Trung (Size L)

^ 6788d947d72a8d79d70fda69
AD-LI XT TET AN LANH SET 6C
AD-LI XT TET TAI LOC SET 6C

^ 6788da530667314f200d37ad
Sót kẹp tóc 28k
kẹp tóc 12k - (cái)
bông phấn 6k
lens mắt 50k
chi kẻ mày 8k
lấy ráy tai 3k/1c
mi giả 50k
khay dựng len 20k
kim cắt 100k
nước ngâm lens 35k
bông đánh kem 18k
áo lót 75k/c

^ 6788dd7460a983c7750f3551
Hồng Trà Sữa Mật Ong - Ly 700ml
Lục Trà Sữa Mật Ong - Ly 700ml

^ 6788de4b2028300be401378f
M-I-Milk Tea Hồng Trà Sữa-I-M
Bubble (M)

^ 6788e20490f44bf98a082212
GIỜ CHƠI BIDA

^ 6788e3a525f5457ffe04e06e
Banh mi dac biet Huynh Hoa

^ 6788e50e47f60816af0dc0ba
REECEN Thanh Cua Vi BBQ 50g/1 Go
NW-Monthly Jan 25-Gia dung thu c

^ 6788e533f9c68a31b60c463e
COMBO1

^ 6788e69b2ff42e99470868e7
Tao Ambrosia Khay1 (6 Trai Lon)

^ 6788e6d66fbb522c630885a7
ANTG ZCJ2Spag
UP Chili Chicke
CJoy
Spag
Spag
UP BBQ Fries

^ 6788e747773a5973710977e8
ANTG 2CJ2Spag
UP Chili Chicke
UP Chili Chicke
Spag
Spag
Up BBQ Fries
Reg Pepst
Reg Pepst

^ 6788e8bd3319fc988b061dc8
Tra Nhan Son (L)

^ 6788e8ca3c93c3a9db0f8a8f
keo deo 3D

^ 6788e8dd00f12c2800066140
Bánh RAM - ÍT

^ 6788e9072c174a73890899f2
Com Chay Cha bong nho

^ 6788e9e5487df6c40d0c9c6c
Keo deo 3D
Tam Thai 62GR thit bo nuong BBQ
Keo lemon
Nuoc Fanta Lon Vi Dao
Coca nap van Nhat
NUOC NGOT FANTA VI CAM 60ML
Chan ga Anna lala (Rut Xuong)
Bo huc thai
Snack hai san tako vi cay hon hop goi 6
MUC BENTO 18GR
Banh mi hoa cuc

^ 6788ed5950c582cfaa056fb6
Tra dao cam sa

^ 6788edb22f05d1175b0342bb
multiple items

^ 6788ef0a491f3ecb770c5f88
Nuoc Tuong Sushi 5ml
Mc Tac Thuong Hang 2 5g
Sushi 1000vnd
Sushi 1500vnd
Sushi 5000vnd
AEON Sushi 6000
Nuoc Tinh Khiet Dasa 1 Chai 510ml

^ 6788ef4160e6734ae30fda52
PC BIC Meal: 1 Regular Coke Zero

^ 6788f067f6b1cc5c980c2fbb
MEAT DELI Thịt heo xay
MEAT DELI [SIG] Sườn thăn (sườn non)
MEAT DELI Xương ống heo
Húng lằng 50g
Nấm đùi gà baby 300g
VIN - Trà Atiso Không đường 1L
DALAT MILK Sữa thanh trùng k.đường 450ml
YAN YAN Bánh quế socola 50g
BOOM Kẹo Dẻo Vị Đào 91g
KUN SCU hương kem dâu túi 110ml
LACASITOS Socola 20g (T288)

^ 6788f50b13f40f7b6b0f23e4
Matcha Coco Latte sữa
Ít đường
Trà sữa (size Phê)
50% Đường

^ 6788f50ec3c257ec0c00d781
Hồng Trà Sữa (Size M)
Lục Trà Kem Matcha

^ 6788f909c392654aae0ce191
Set 7 Tầng
Set Bào Ngư Đại Dương
Mirinda Cam
Souce Phô Mai
Bò Cuộn Nấm Kim Châm
Khăn lạnh

^ 6788fa8ba698a89fe709795b
PEPSI
BUN QUAY TIEU CHUAN
BUN QUAY TIEU CHUAN

^ 6789015c459490f299034ccc
I-ON LIFE Nuoc ion 1.25L 8938503000024

^ 678901776d46d3d8f8076609
TIÊU MÂN Lychee And Roses Tea
MĂNG CHỨNG Strawberry And Yuzu Tea

^ 6789017a479dafe05f0a0937
SNACK TOONIES VI GA
SNACK OISHI PHO MAI
KTC SLIDE BBQ XOG
TRA BONCHA 0DUONG DAO
BANH XOR RICHESE
KEO GOLIA ACTIVE PUL
KEO AD ALPINELIEBE
KEO CHEWYTRAU PHONG
KEO DEO CHUPA CHUPS

^ 678901a7bcddeca6fd03c286
7UP Revive isotonic chai 500ml

^ 678901da4b9267bf260d6655
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml

^ 67890210e0a32df5f7068184
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml

^ 6789024d459490f299034dd8
Banh Marine Boy rong
Keo deo Boom vi dao
Banh xop Richesee Na
SCL Trumpf dark than
SCL Marou mini phong goi

^ 67890410bcddeca6fd03c4c1
Che Bo Sau
Che Tau Hu Kem Matcha Caramen

^ 67890415bf86bb0bad0d95ab
Phindi Hanh Nhan L
Phindi Hanh Nhan M

^ 6789047398e5108f8d0fc4ca
NGK Coca Light lon cao 370ml
SN. loc Rockstar lon 6x250ml
Tra mat ong tac Roncha 450ml
NGK 7up lon cao 320ml
NGK Coca plus lon cao 320ml
Nuc STING dau lon cao 320ml
TPBS Sua Mach MILO loc8x180
S-Chua anh True ThienNh
xxlch DeLi Sumo LEGOUr 250g
Banh gio nhan thit 150g-rut
Tuong ot SEMPIO hop170g
Dau hu non ccap VINATOFU 300g
K.chitai Cat Tat t.k.Kim20
kem orque Celano extra dau125
Kem cc Cel CRM muoi hop 460ml
Cha. nhiet NHATH hg 25x30
S.Chanh day tuoi lon 245g
Sua tuoi tt DaLat kd 220ml
Ba roi rut suon heo kg-VS990
Bao dua Filo cngthiep 5000g-Lebouci

^ 6789077774f251f7380fd63d
Miếng dán cố định tóc Barber để cắt hoặc uốn duỗi đồ
Tinh dầu dưỡng và giữ nếp tóc karanz 100ml

^ 6789079c68da3c1f5300f365
Mieng dan co dinh toc Barber de cat hoac uon duoi do
Tinh dau duong va giu nep toc karanz 100ml

^ 678907cf933feae3f200aebb
Miếng dán cố định tóc Barber để cắt hoặc uốn dưới đó
Tinh dầu dưỡng và giữ nếp tóc karanz 100ml

^ 67890893a1b9fd491402de03
Mi LT bo C 1
Mi LT suon sun C 1

^ 678908e2624d7f0f0c04de48
COMBO CS 1: MESO TE BAO GOC DNA CA HOI (Gia Foxie Member Card)

^ 678909ba63cb7ed7ed0ef656
VM ComGa CknSp
Comga wVeg
Pumpkin Chicken
Reg Pepsi

^ 67890a9e3bba64b2ea073f05
DX PANTENE NGAN RUNG TOC 150M

^ 67890abc5e1d42b042091f88
Tra Sua Khoai Mon

^ 67890ac063cb7ed7ed0ef7f1
DX PANTENE NGAN RUNG TOC 150M

^ 67890ae06524f6d4750ca28b
DX PANTENE NGAN RUNG TOC 150M

^ 67890b06159a90b92000b386
DX PANTENE NGAN RUNG TOC 150M 4902430837231

^ 67890b600509ea99320d5327
Long Nhan Sua - tra
Cold Brew Mo Da

^ 67890e6816029d8bad038221
Cơm Trộn Bò
Mì kimchi Bò Mỹ
Cấp 0
Coca
Khăn Lạnh
Coca

^ 67890e9cbfbc4fbdcc049d28
T3. Tra O long Tea plus 45
T3. Tra O long Xanh Tea

^ 67890f62a16e6d0a6b044301
Kem bap merino
Banh trung trang an
Sot lisa 130g
Banh dark choco 216g
Tuong ot Chin su tu 500g
Dau dieu an Phuc
Banh hop Omeli khoai tay
Banh trung Custas
Banh chocopie 12 chiec

^ 67890f71a16e6d0a6b044325
cà chua (kg)
rau lang (bó)
cá ba sa fillet
sườn non heo brazil
thịt nạc heo c.p
ba rọi heo c.p
sữa chua ăn có đường lothamilk hộp 100g lốc 4 (al)
sữa chua uống vnm probi dâu chai 65ml lốc 5

^ 678910a229f6ac7fdb046d33
Keo - (gg)
Banh ram Anchi 70g
Banh da nem an lien Anchi 50g - (g)
Banh xop thai Shanghai 320g - (scl)

^ 678910b329f6ac7fdb046d60
COCO DODO M
COCO MATCHA M

^ 6789112d4fafc6d6930a18b8
GIAM GIA BANH MI
GIAM GIA BANH MI
GIAM GIA THUC AN SAN

^ 678911c18d1b8cf69b09daed
CHIN-SU Xot Mayonnaise tuong ca 120gT24

^ 67891243811ecd14fa0f6942
KITKOOL Pizza xuc xich pho mai 140g
TIPO Banh bong lan tang kem xoai 180g
OISHI Snack nhan SCL Pillows goi 80g

^ 67891354e5a660d88306b0d6
MEIZAN Bot my da dung 500G MB
VINAMILK SDD khong duong F220ml

^ 678914b2563260c0fc09c719
Thuy (French Low Carb) (Glass 330ml)
Th (English Black Forest Ale) (Glass 330ml)
Kii (German Weizen) (Glass 330ml)
Nuoc uoi/ Water (Chai 500ml)

^ 67891538563260c0fc09c7da
trà sữa 3in1 wang cha trân châu hộp 400g
bg omo đỏ gói 400gr/380g
gel tẩy rửa tác động sâu duck hoa oải hương 900ml
nước lau sàn sunlight hoa lily & hương thảo/bạch trà túi 3.6kg
quà tặng: khay nhựa đa năng cao cấp

^ 678919259225603b9b0ac7aa
Gio Billiards Giam Gia

^ 678919d862e7bbff110198e2
S-I-Milk Tea Hồng Trà Sữa-I-S
S-I-Milk Tea Hồng Trà Sữa-I-S
S-I-Yogurt Strawberry GMT Lục Trà Sữa Dâu Yogurt-I-S

^ 678919fbf4168bf8f40ec568
CROISSANT HANH NHAN
KHUYEN MAI @17.700
DANISH NHO
DISC 50% @9.800
MUFFIN TRA XANH NHO
BANH HAN QUOC DAU
DISC 50% @11.700
CRUFFIN BLUBERY
DISC 50% @19.400

^ 67891a67235820afb0020157
CLORPHENIRAMIN 4MG

^ 67891a8af4168bf8f40ec621
PANADOL EXTRA - MOI Lô: EVH1653
EYEMIRU 40EX 15ML Lô: M006

^ 67891d61650d0160f40a098a
Bong tay trang dang bic goi

^ 67891f6bb72b8a8f7e05999d
Combo 4 Choux

^ 678920a56febea061a0f36e3
KOIMUCHO Snack bap vi bo toi 30g
KOIMUCHO Snack bap vi thit nuong 30g
MERINO Soa chua deo pho mai 5og
Red Bull NTL voi Vitamin va Kem lon 250ml
Red Bull Nuoc tang luc 150ml
BUONONO Tra hut Tea58 hoang tu soc dem 50g
FUNDAY Keo ngam hat dieu leo 22G

^ 678920d36febea061a0f3724
Dầu gội PANTENE NGĂN RỤNG TÓC
CHÁO THỊT BẮM GÀU ĐỎ 50G
Bánh phô mai Castella
MÌ KHOAI TÂY CUNG ĐÌNH HƯƠNG VỊ BÒ HẦM LY 65G
Mì Kokomi Pro 75g
MÌ HẢI SẢN SIUKAY GÓI 128G
BÁNH BƠ SỮA NGÀN LỚP NHIÊN LỢI

^ 6789266c69b49e5f8b0f7478
Mon Nuoc V Vienna Creamy Frap
SR_SEGMENT_25_JAN_300_BOGO

^ 678928cbeb3a6e6ce60f813e
Cot let heo kgVS990
SCanh bi do tron vi chay

^ 67892a0deb3a6e6ce60f8209
giấy sapa D-Shining 300 tờ 3 lớp trắng

^ 67892a4419bb9548810c40a4
Tui nilon sieu thi T.Do 26x42 3kg 182C/kg
Nuoc Oishi Tea go tra xanh vi chanh 180ml/50
Nuoc Oishi Tea go tra xanh vi dac 180ml/50

^ 67892af119bb9548810c412a
MIT GIONG THAI XE

^ 67892b0a19bb9548810c414a
PhaTea Tra Sua Thai Do 350ml

^ 67892b3ef06ae880800961b8
BÁNH HÀN QUỐC SOCOLA
BÁNH NGỌT XÚC XÍCH SỐT TIÊU CAY
BÁNH NGỌT XÚC XÍCH
BÁNH NGỌT XÚC XÍCH
MUFFIN VANI

^ 67892c31079928484f0ca0be
AUGMENTIN BD TAB 625MG
ALPHA CHOAY 4200IU

^ 67892c8a98d0239d1a0f63cb
Xoi cp 4 vi Coop select 600g
Xoi chien phong Vissan 500g
Xoi cp d.xanh Coop Select 500
Xoi cp la dua Coop Select 500

^ 6789316b0983b5106b0fc506
Eggplant dip Tahini
Casa Pane
Duck Tajarin
Zucchini
Purezza Still

^ 67893316a6f50885c60c713a
TRA BI DAO WONDERFARM 440ML

^ 6789333341d8af0cfb0932bc
TRA BI DAO WONDERFARM 440ML

^ 6789336941d8af0cfb093320
TRA Bi DAO WONDERFARM 440ML

^ 67893386d52b04d2c90babf8
TRA BI DAO WONDERFARM 440ML

^ 6789350475b1c0142c0769cb
Combo Matcha + Cake

^ 6789419b451b2a441909c069
Đậu phộng
Khăn lạnh
Nghêu Hấp Sả
Càng cúm
Ken lon nhỏ
Nước Suối

^ 678947bf4b98b58b3a093f89
11119 KDR y te Ajona 25ml

^ 6789a57cbf5b5bce0a06eca7
Mon Nuoc G Iced Pure Matcha Tea Latte
Discount
Replace Oatmilk
Mon Butter Croissant (For Here)
403280 TCB 25K

^ 6789a5d8505772645e0c0341
WMHOME Nuoc rua chen sa cam tui 3.5L
CHANTE NG Chante h.hoa hong Phap 3.1kg
CHIN-SU H.nem ngot thanh 400g T16

^ 6789ae4533af4f42ac0cd5e8
Cà Phê Sữa

^ 6789b245b4d5e32b550d0b99
Tiền giờ khu D D.05
Dasani

^ 6789b42aa3617e292104f534
Combo Phat Loc 86K
Hot Wings (3 Mieng)
Burger Tom

^ 6789b48f7cf47d4cc6076e38
NOW DEAL 50% ORG
Spaghetti (M)
Fanta TA
FAMILY A
Tender ICB
Cole Slaw (R)
Spicy TCB
Coca TA
Mash (M)
1 BIC
Spicy ICB

^ 6789ba7d3f46d7bf560bd4fd
LVD72T - Chan vay ct tang ren - TRANG 0

^ 6789c1f06ef7431d740788d3
Grab Food

^ 6789c23442c951bddb028993
Ca Phe Sua (L) (Robusta Rang Xay)
+ Sua 12

^ 6789c74983ec59561f05516c
Ao So Mi Nhung Tam Nam Nu Coc Tay Form Rong Thoi Trang Basic Haley A4

^ 6789c7952b9c83ec4809c13a
Ca phe sua Sai Gon

^ 6789c7c22b9c83ec4809c189
Tra Tao Xanh (L)

^ 6789cc68eae4f28a0d050437
Duong va
Banh pho
Banh gio
Kho ca c
Kho ca c
Bot bo k
Bot ca r
Bot ngu
Banh bao

^ 6789cc8ecfae7db8df0ddbde
Gao deo

^ 6789d2f2f35aa17d230b24f0
nước tăng lực sting gold sleek lon 330 ml/320 ml
bàn chải p/s lông tơ mềm mại
sốt ướp thịt nướng cholimex gói 70 g
bcdr col slim soft cham soc nuou
xốt nhà hàng chin-su nướng muối ớt gói 80 g
xốt ướp thịt nướng delly cook gói 70 g
tương ớt knorr vị cay đậm chai 450 g
quà tặng: tương ớt knorr vị cay đậm chai 450 g

^ 6789d6cb9d96639761030788
KEO SOCOLA SUA M&M-XA
DUONG MIA CAO CAP BIEN HOA 1KG
DAU NANH SIMPLY 1L
CHA LA KHO NG.CANH VAF 500G
TUI MUA HANG MM 40x36x22CM

^ 6789e19f3bbd884972089269
Tra Sen Vang_CN S
Phin Sua Da S

^ 6789e1e9a91dd14b430c4b44
Tra Thanh Dao L

^ 6789e1f7256a9e8ad9067bfe
Tra Sen Vang_CN S
Phin Sua Da S

^ 6789e28227564e82a501358d
Medrol 4mg Pfizer 3x10
Nuoc Oxy Gia Vinh Phuc 3% 60ml
Bom Tiem 5 25G Vinahankook 100 cai

^ 6789e3a4399e6499f40baeb7
Tra Sen Vang_CN S
Phin Sua Da S

^ 6789e3d7a97a7886220a2ddd
Tra Sen Vang_CN S
Phin Sua Da S

^ 6789e4e7ae7be637f80d29a8
Phindi Hanh Nhan L
Phindi Hanh Nhan S (lays sau)

^ 6789e505ae7be637f80d29d0
Phindi Hanh Nhan L
Phindi Hanh Nhan S(lays sau)

^ 6789e5237a5704ce6c02fc3e
Phindi Hanh Nhan L
Phindi Hanh Nhan S

^ 6789e82bc5398c86d407791a
trứng gà hộp 10

^ 6789e8600b7ec3956c0caa40
sữa chua ăn có đường nutimilk hộp 100g (al) lốc 4
quà tặng: sữa chua ăn có đường nutimilk hộp 100g (al) lốc 4
quà tặng: sữa chua ăn có đường nutimilk hộp 100g (al) lốc 4

^ 6789e885c5398c86d40779a3
trung ga hop 10

^ 6789e8a1a1528aae560d3301
trung ga hop 10

^ 6789e8d12b91b7ba520d0973
Trung ga hop 10

^ 6789e90d0b7ec3956c0cab4a
sữa chua ăn có đường nutimilk hộp 100g (ai) lốc 4
quà tặng: sữa chua ăn có đường nutimilk hộp 100g (ai) lốc 4

^ 6789ea01c99c7ed545018aa0
TRA SUA CHAACHAANOI DO TRAN CHAU DEN

^ 6789ea380b7ec3956c0cad81
TRÀ SỮA CHAACHAANOI ĐỎ TRÂN CHÂU ĐEN

^ 6789ea5ded62e4beb50460ab
Tra Sua Chaachaanoi Do Tran Chau Den

^ 6789ea812b91b7ba520d0b74
Tra Sua Chaachaanoi Do Tran Chau Den

^ 6789eaab0c4ee7abbc06d49e
Tra sua Chaachaanoi do tran chau den

^ 6789eae0ed219ce44a0ff2d7
Trà Sữa Chaachaanoi Đỏ Trân Châu Đen

^ 6789ed93f293eeb0c8021aa8
Ve trong tuan

^ 6789ede1b249230be60e5d18
Nuoc loc

^ 6789ee24a12a6126900e4aa6
Ve trong tuan

^ 6789ee57ea34b7e6540aa115
Ve trong tuan

^ 6789f0686bdffd22ab0e627a
TRA MAT ONG BONCHA
CH X
MUFFIN SOCOLA 40G*6
KEO DEO CHUPA CHUPS
D.PHONG OISHI PINAT
BANH SU DAI 30G*10
D.OISHI VI COT
KTC SLIDE HOT & SPIC

^ 6789f0c0486a9e9f9303e74f
Chế biến - Rang Muối CT
Chế biến - Nướng Mọi
Cá Chim - Sống
Bọ Hương Sữa (Size 50 - 80 Con/Kg) - Sống
Tôm Càng Xanh (Size 10-12 Con/Kg) - Sống

^ 6789f0c4b249230be60e60bf
Cà phê cốt dừa Đá xay

^ 6789f1cdbed81398c60284ce
Chế biến - Hấp (Kg)
Sọc Xanh Loại 1- Sống (Kg)
Chế biến - Nướng Phô Mai (Kg)

^ 6789f202697e6d52f80d76eb
che bien - nuong mo hanh (kg)
so long - song (kg)
phao hoa (hop)

^ 6789f2478c0318c01d00333f
Chế biến - Nướng Mỡ Hành (Kg)
Sò Lông - Sống (Kg)
Cơm chiên hải sản (Phần)
Tôm Hùm Bông (Size 0.9-1.2Kg/Con) Sống (Kg)

^ 6789f2ae21721ffcfb02abf0
Che bien - Nuong Mo Hanh (Kg)
So Long - Song (Kg)
Com chien hai san (Phan)
Tom Hum Bong (Size 0.9-1

^ 6789f2d22754caa7be09770c
Sashimi va gia vi (Kg)
Sot Hoang Kim (Kg)

^ 6789f3068b1cc3369605f833
Chế biến - Nướng Mọi (Kg)
Cá Chim - Sống (Kg)

^ 6789f33db0007dcfc10cc40f
Chế biến - Sashimi và gia vị (Kg)
Chế biến - Sốt Hoàng Km (Kg)
Tôm Sú - Sống (Kg)
Cá Hồi Na Uy (Phi Lê Thăn) (Kg)
Sashimi Cá Hồi (Thăn - 20 Miếng/Phần)
nan

^ 6789f35b8b1cc3369605f8a7
Poca Partyz Snack Muc Lan Muoi O
Poca Partyz Snack Bo Texas 60g/
Poca Suon Nuong BBQ 60g/1 Goi
NW-Monthly Jan 25-Mua 2 tang 1
C2 Freeze Tra Den Huong Dau Anh
CK Mi Tron Indomie/1 Phan

^ 6789f368ce87c0f5fc006c60
Che bien - Sot Bo (Kg)
Oc Huong Sua (Size 50 - 80Con/Kg) Song (Kg)

^ 6789f38a7b167f404604f756
Chế Biến - Nướng Phô Mai -(Kg)
Hầu Đại Dương (Size Lớn) - Sống - (Con)

^ 6789f3a87b167f404604f792
Maki Com Cuon California (8 Cuon/Phan) - (Phai)

^ 6789f3c39fd9b44eff0a8860
CK Mi Tron Indomiel/ 1 Phan
CK Trung Op La/1 Phan
PhaTea Tra Tac Thai Xanh 22oz/1

^ 6789f40251761affdb09d78d
Che bien - Nuong Muoi Ot (Kg)
Ca Chim - Song (Kg)
Che bien - Nuong Pho Mai (Kg)
Che bien - Nuong Mo Hanh (Kg)
Hau Dai Duong (Size Lon) - Song (Con)

^ 6789f427f766e168ac016f79
Che Bien - Hap (Kg)
Cua Thit Ca Mau Khong Day - Song (Kg)

^ 6789f459905cac2c5803c54e
Keo
Bang bao ve co chan
Ban chai danh rang
Ban chai danh rang 4S
Chi may-10
Mieng rua dang luoi 2S
Kep toc 6cm (Den) 3 chiec
Ban chai can go kem 29CM

^ 6789f6204793ba683a0cae3c
Long Nhái Sữa - trà sữa - SIZE LAAA
Trà Vỏ Cà Phê - size LAAA
Lang Biang - trà trái cây - size LAAA
Trân Châu Gạo Rang
Long Nhiệt Đới - size LAAA
Long Nhiệt Đới - size LAAA
Mơ - Cold Brew Ổ Long Mơ Đào - size LAAA
Bao lì xì Tết 2025

^ 6789f6423b989f6279096c42
Long Nhãi Sữa - trà sữa - SIZE LAAA
70% Đường
Trà Vỏ Cà Phê - size LAAA
70% Đường
Lang Biang - trà trái cây - size LAAA
Trân Châu Gạo Rang
Long Nhiệt Đới - size LAAA
50% Đường
Long Nhiệt Đới - size LAAA
50% Đường
Sài Mơ - Cold Brew Ổi
Long Mơ Đáo - size LAAA
50% Đường
Bao lì xì Tết 2025

^ 6789f67ede3d9b7f2100ee33
Long Nhãn Sữa - trà sữa - SIZE LAAA
Trà Vỏ Cà Phê - size LAAA
Lang Biang - trà trái cây - size LAAA
Trân Châu Gao Rang
Long Nhiệt Đới - size LAAA
Long Nhiệt Đới - size LAAA
Sỉ Mơ - Cold Brew Ổ Long Mơ Đào - size LAAA
Lì xì Tết 2025

^ 6789f69f820802912c03dd49
Long Nhãn Sữa - trà sữa - SIZE LAAA
Vỏ Cà Phê - size LAAA
Lang Biang - trái cây - size LAAA
Trân Châu Gao Rang
Long Nhiệt Đới - size LAAA
Sì Mà - Cold Brew
Long Mơ Đào - size LAAA
Bao lì xì Tết 2025

^ 6789f7e551bd8394cb0a6364
So Huyet (Size 30-40 Con/Kg) - Song
Hai Dai Duong (Size Lon) - Song
Che bien - Nau Chao (Phan)
Ngheu San - Song (Kg) Che bien - Hap Sa
Ghe Xanh Loai 1 - Song (Kg) Che bien - Rang Me Nong
Tom Hum Luoi Duong
Lau Tom Hum
Lau Ghep

^ 6789f815de3d9b7f2100f0c8
Đậu Non Chiên Xù
Bún Thái
Cơm Chiên Trái Cây
Bún Chả Giò Xiên Nướng
Bình Trà Nóng/Lạnh (6 ly)
Lẩu Tom Yum (Nhỏ)
Khăn Lạnh

^ 678a04f7a4bfbe11f005450c
Shaman Milk Tea + it Ngot

^ 678a05352b131fa35605d4d9
Tra Gao Nau

^ 678a056cea2bb34e1300b384
Tra Lai Dac Thom

^ 678a0599a4bfbe11f0054615
Luc Tra Kim Quat

^ 678a0a8722bf3d6ca90cf6a9
Olong Sữa Tươi
Trà Sen

^ 678a147ce2dba12054020c31
Hồng Trà Chanh Mật Ong (M) + Trân châu giê truyền(1) + ít đá(1)


In [ ]:
# Biến Series thành DataFrame
df_for_gemini = grouped.reset_index()
df_for_gemini.columns = ["Bill ID", "Extracted_Items"]

# Hàm format cho từng row
def format_for_gemini(row):
    bill_id = row['Bill ID']
    extracted_items = row['Extracted_Items']  # bây giờ là list
    # Convert each item to string before joining
    formatted_items = "\n".join([str(item) for item in extracted_items])
    return f"^{bill_id}\n{formatted_items}"

In [ ]:
# Tạo cột mới chứa data format sẵn
df_for_gemini['Formatted_Data'] = df_for_gemini.apply(format_for_gemini, axis=1)

print(df_for_gemini.head())

                    Bill ID  \
0  66a84505a75ea9001406cd44
1  66ab3dcf47abf7a4110ccc33
2  66acaab67fb28ac231046400
3  66b968634c427e78680d3a80
4  66c9c5c3b828649bc20b07e9

                                     Extracted_Items  \
0        [Lẩu gà lá é size nhỏ, Nước suối, Bún thêm]
1  [sữa trái cây vị dầu vnm hero 110ml lốc 4, bán...
2  [Mango Nitro Oolong Tea - Cold, Cà Phê Sữa - C...
3                                      [Milk Coffee]
4  [9" Thin Crust Madness (Madness Cheesy), 9" Th...

                                      Formatted_Data
0  ^66a84505a75ea9001406cd44\nLẩu gà lá é size nh...
1  ^66ab3dcf47abf7a4110ccc33\nsữa trái cây vị dầu...
2  ^66acaab67fb28ac231046400\nMango Nitro Oolong ...
3             ^66b968634c427e78680d3a80\nMilk Coffee
4  ^66c9c5c3b828649bc20b07e9\n9" Thin Crust Madne...

In [ ]:
len(df_for_gemini)

28692

In [ ]:
# --- Chunking ---
chunk_size = 50   # số Bill ID mỗi chunk

formatted_data_chunks = []
for i in range(0, len(df_for_gemini), chunk_size):
    chunk = df_for_gemini.iloc[i:i + chunk_size]
    combined_data = '\n'.join(chunk['Formatted_Data'])
    formatted_data_chunks.append(combined_data)

# In thử 2 chunk đầu
for i, chunk in enumerate(formatted_data_chunks[:2]):
    print(f"--- Chunk {i+1} ---")
    print(chunk)
    print("-" * 20)

print(f"Number of chunks created: {len(formatted_data_chunks)}")

--- Chunk 1 ---
^66a84505a75ea9001406cd44
Lẩu gà lá é size nhỏ
Nước suối
Bún thêm
^66ab3dcf47abf7a4110ccc33
sữa trái cây vị dầu vnm hero 110ml lốc 4
bánh quy cosy dừa 132g/135g/126g/117.6g
^66acaab67fb28ac231046400
Mango Nitro Oolong Tea - Cold
Cà Phê Sữa - Cold
^66b968634c427e78680d3a80
Milk Coffee
^66c9c5c3b828649bc20b07e9
9" Thin Crust Madness (Madness Cheesy)
9" Thin Crust Pepper (Pepperoni Feast)
1.5 Liter Bottle COK
^66cb0f6f32d3f04afc0b38b1
ZKDR COLGATE M/F thun 175g
^66cc4a076855aa7e630b5edb
sách
^66ce910a006c0a233005e655
SB Kimbap Bò Bulgogi
^66dab6d652ea3901e10124c2
Tô Ngon Miệng
^66dba6fe0798e6cdd10be534
Phin Sua Da S
BMQ Ga Pho Mai
^66dc1cc795094d9d8c0e7a40
Trà Nhân Sân (L)
^66dcf6015d3ba2ee2a0a306c
Suôn nướng
Suôn cày nướng
Dừa Tươi Trái
Khăn lạnh
^66dd24465ce585c76609b18f
Kid's Mini Trio
Double Scoop
Belgian Waffle
Iced VNS Milk Coffee
bạc xíu it đá
^66dda5d809dec2d4a00ed1e9
Lòng jab
Tê giác
Tỳ rô
Khô
^66de4e240db6eb31e507dd25
Cà phê Espresso Bạc xỉu (l.)
^66de75e80485a5153309d3b5
THIT BO VUN 85% NAC DL XXUC-WRF
THIT BO VUN 85% NAC DL XXUC-WRF
THIT BO VUN 85% NAC DL XXUC-WRF
SET SUN GA CHIEN GION
^66ded9b1e74cc306db094c89
Khô lạnh enzyme
1/2 Bánh mì bò tỏi
Soda chanh
Combo bò Mỹ 2 người
Nước suối
^66dedc27276a43c4a6076741
Bắp cải trái tim kg
Giá đậu xanh 300g
Trà Châu 250g
Trà Châu không đường
^66df1a929cfd6ed04a015973
bắp cải tráng (kg)
cá viên tẩm vịt sin 200g (cb)
^66dfa30bdb2f22c5e80b9798
Bạc Xíu Đá
^66e017958be7dce89a053d47
Cáp BASEUS CRYSTAL SHINE USB-C TO LIGHTNING
Sạc ANKER POWERPORT III 20W A2149-EEN
^66e022d4e7ff326e990dbd06
Cà diều hồng sống
Cá lóc nướng
Sữa UHT
Dưa leo
Nước mắm
^66e0f5d756c4a29e3203b46a
Bac Xiu
^66e11a6b0ff3d304ab0cb012
Cá Trân Châu Đỏ 800g
Rau bí đao bao kg
Xà Xíu 500g
Sá Sùng 500g
Sáu Xáy 500g
^66e121a0da16ae9ce0095441
Espresso (Blend SS)
Cà phê đá (Size nhỏ)
YOGURT (Sữa Chua Đá)
^66e122dd3bfacc2508042797
Espresso (Blend SS)
YOGURT (Sữa Chua Đá)
Cà phê đá (Size nhỏ)
^66e125876faec0547d03045e
cải bẹ dún
hẹ lá gói 100g
đậu hũ lụa vị nguyên cây 220g
dưa leo baby
bí đỏ hồ lô (kg)
^66e126d3063cc185ef058cb8
Đèn cầy màu
Lồng đèn giấy thủ đà
^66e127c0824ccdfec20ee87c
cải bẹ dun
hẹ lá gói 100g
đậu hũ lùa vị nguyên cây 220g
dưa leo baby
bí đỏ hột lồ (kg)
^66e12819a68148794c0504d4
Đèn cây màu
Lòng đèn giấy thứ đặ
^66e129bc6483c61654042ff7
Xang RON 95-IV
^66e129f53f1cce9e240b1591
Xăng RON 95-IV
^66e149215be0d8e1870378f4
Sting
^66e19b17c0bd6e73ec0ec2ce
TIGER NAU LON
KHĂN
SUN GA CHAY TOI
DAU HU CHA BONG TRUNG MUOI IST
LẨU BÒ 300
^66e247df5d5a104c2300e96a
Cà phê sữa đá Size M
^66e2671835d8c04f0b097c4b
Vanilla Peach Limeade (M)
Iced White Cf Vn (M)
^66e284e9b5636833d603b19b
Cà phê đen đá (M)
^66e2866cb5636833d603b222
Trà Vải Sen (L)
^66e286f2c6bd30306f03b6bc
Cà phê đen đá (M)
^66e2871b6f99b2191a0f72dc
Cà phê đen đá (M)
^66e2876e97930d06830a6e73
Espresso (Blend SS)
Cà phê đá (Size nhỏ)
YOGURT (Sữa Chua Đá)
^66e287dfa76854fe310dd765
Espresso (Blend SS)
Cà phê đá (Size nhỏ)
YOGURT (Sữa Chua Đá)
Cà phê đá (Size nhỏ) 2
^66e2880b5ee6ad3fd00d95e3
Cà phê đen đá (M)
^66e288cb301902781c0a1e92
Xăng RON 95-III
^66e2cd8fa1730dc87a04b6c0
Fried Chicken
French Fries R
Pepsi R
^66e2cdafe9e483069d08e7da
CBO 49K_COB+Mi Y
Rice
Fried Chicken
NSC Mix
Mì Y Pop (New)
^66e2dca21519dc7c150e95f6
Cá viên tân việt sin 200g (CB)
Bắp cải trắng (KG)
^66e2dde4612d806ea0095a2c
viên vệ sinh bồn cầu vim hương chanh 55g
kem que wall's ad coconut 58g/63g
snack mực vị rong biển talaethong gói 100g
nước ngọt mirinda soda kem pet 390ml
^66e2df46cfc802c89008cba8
Cá viên tản Việt Sin 200G
Bắp cải trắng
^66e2f462afcf8d383f0c5789
Giấy nhớ
Bút lông
Hộp đựng đồ
Trẻ em
Thẻ giấy
Bảng keo
^66e398feec12a714a30f0892
Bac Xiu
^66e3a8f520778b08d0013d05
Fried Chicken
NSC Mix
Rice
^66e3a8f6c14767cb41022778
CBO 49K_COB+Mi Y
Rice
NSC Mix
Mi Y Pop (New)
^66e3a9341c7826f43c01b81c
CBO 49K COB+Mi Y
Fried Chicken
Rice
^66e3a977cc90fcd8190a897c
CBO Chicken
Fried Chicken
French Fries
Pepsi
MK_CBO Chicken
^66e3a9bfa71e08a6db0ce0d6
CBO 49K COB+Mi Y
Rice
^66e3acbe6bd61aebba0e721f
Cà phê đen đá (M)
^66e3ad0f7690a48ba2081440
Espresso (Blend SS)
Cà phê đá (Size nhỏ)
YOGURT (Sữa Chua Đá)
^66e3c897eace6724e2095f46
Mì Samyang Gà Cay 145GR
Nước Ngọt Coke PET 390ML
Cải Thìa Gói 300GR
^66e42ec40a178d7702005676
Cà phê Espresso Sữa Đá (L)
^66e448725d34f841a10e8ef6
Trà Sữa Chocomel (L)
^66e4e9f06e2ce88333019db9
C6 Bạc Xíu (White Coffee)
^66e50f0c66c8a26700006f83
H. Lý Châu Dương Mát (L)
Bò Giá Đìa Non (S)
^66e5204352d9ff60b204d2a0
Trà Nhân Sen (L)
^66e5392818db8abf8204b689
KHÁN
Nướng tc
Luộc tc
Nước ngọt
Lẩu tc
Sushi
^66e5521dc6e42b489a083c96
K.singun CA FreCUBEchanh
Keo hang Playmore dua hau
Choco NESTLE MILO Nuggets 7g
^66e55248bd2f15e24f0ed6ec
K.singum CA FreeCUBE
Keo the playmore dua hau
Choco NESTLE MILO Nuggets
^66e552df8f317c96ce0da7cd
K.singum CA FreCUBE
Keo the Playmore dua hau
Choco NESTLE MILO Nuggets
^66e553a16b79637c300d8d9a
K.singum CA FreCUBEchanh
Keo the Playmore dua hau
Choco NESTLE MILO Nuggets
^66e553e14ac30cfccc0d8972
K.singum CA FreCUBEchanh hu
Keo the Playmore dua hau hu2
Choco NESTLE MILO Nuggets 75
^66e5664cb43455e7a4086ea1
Trứng gà size L 10tr/hộp-BH
Tao tau 250g-HVV
Dưa leo COOP Kg
Chuối Coop Select L kg - U1T
Củ su hào kg
^66e58284156b3582280fc683
Bucket 3 COB_Kiosk
^66e5829c626634c5a9071176
Bucket 3 COB_Kiosk
^66e5a2f5a76f8e4c6301a88d
K.singum CA FreCUBEchanh hu
Keo the Playmore dua hau hu
Choco NESTLE MILO Nuggets 75g
^66e6478dfe6859956e035ddf
Ca Phe Sua Da
BELT Sandwich(Half)
Milk
^66e67ab7b7b42971e60d5ae0
Oreo đã xay
Cà phê đen đá (M)
Sữa chua việt quất
^66e67addc5eb8fdc950af547
Oreo đã xay
Cà phê đen đá (M)
Sữa chua việt quất
^66e69da926226aed030dbc2f
Quần short PLAC Denim One-Tuck
^66e6ba2b98c31a4e3b000252
Trà tắc
Bún nem chả giò
^66e6ca79a4bf8ce43b0d9d1b
Khay nhựa A5
Sổ vở A4
Túi Daiso size mini Túi số 3
Bút viết
^66e6d090ec65d9656e0c9955
trà gừng hoa tán
^66e789ca5a4284fcbd04ea90
Bac Xiu
^66e799d1b28967879000ecd4
Tires
Labor
Tax
^66e7d0f6bf695cbe4e01674d
Cà phê sữa đá
^66e7e245a452c3712c034e67
Oreo dã xay
Cà phê đen đá (M)
Sữa chua việt quất
^66e7e46e6df7580ca407109e
Ép Cam
^66e7e4e292e8fac86409f19e
Ép Cam (S)
^66e7e552e108aed43f03bafd
Ép Cam (S)
^66e7fd3b6c6acb8bc901d041
Giò bò Dai Loan kg
Chuối Coop Select L1 kg
Bia TOPPO vani socola hg 4
^66e812682ce815b5a701dd3d
Mì Ý (xóng khói sốt kem)
Beefsteak bò Mỹ (150G)
Nước ngọt (Sting)
Trà đá
Khăn lạnh
^66e85a6ceb0f9063df0c6ae2
viên vệ sinh bồn cầu vỏ chanh
kem que wall's ad coconut
snack mực vị rong biển
quà tặng: nước ngọt mirinda soda
^66e85a9206fe63f4f200da4a
viên vệ sinh bồn cầu vim hương chanh 55g
kem que wall's ad coconut 58g/63g
snack mực vị rong biển talaethong gói 100g
quà tặng: nước ngọt mirinda soda kem pet 390ml
^66e85aee88f71b5d07071ace
viên vệ sinh bồn cầu vim hương chanh 55g
kem que wall's ad coconut 58g/63g
snack mực vị rong biển talaethong gói 100g
nước ngọt mirinda soda kem pet 390ml
^66e85bed8b31702e1b05b86f
tương ớt pet cholimex 270gr*24
bắp cải trắng
táo gala đỏ
^66e8ee268bc26095ff03f632
Coca
SPRITE CHAI
^66e8f71ff0015878810938d9
thanh toán
^66e8fa891d262e78f00c9db7
Quét mã QR
^66e8fd3cb887c708c007758c
Cà phê sữa đá (S)
^66e8fd50df30b937a507b242
Tra Sen Vang_CN M
^66e90573d43e24ef54034f4d
Cà phê sữa đá (S)
^66e90c99c72468fcef08e456
Cà phê đá
Bún thịt Xào
Cà phê sữa đá
Cơm tấm
^66e9111d7f4ffbc6f00d87aa
Cà phê đen đá (M)
^66e91143910d3599050bc8e3
Cà phê đen đá (M)
^66e91199dc6231eeb801cbde
Cà phê sữa đá (S)
^66e911b019e8f6a33606dedb
Cà phê sữa đá
^66e911e748bf1816a109fa7f
Cà phê đen đá (M)
^66e911f72a5a119e45068843
Cà phê đen đá (M)
^66e9121c05e153492d077dec
Cà phê sữa đá (S)
^66e9130acc5a0e87d906d351
Cà phê đen đá (M)
^66e913f7901865b2650c16fa
sữa chua ăn có đường nutimilk hộp 100g
combo 3 trái dừa xiêm gọt vỏ
táo queen newzealand
^66e93628b4728a6bfe0c990d
Bac Xiu
^66e97ea3e7e4392b0103ed96
Gala Newzealand
^66ea2f1f870aa27d770ede54
Cà phê Espresso Sữa Đà (L)
^66ea8a986011c5676705a6e4
Cà phê đá
Bún thịt Xào
Cà phê sữa đá
Cơm tấm
^66eae6562aec1e29110cae54
Sinh Tố Bơ (M)
Trân Châu Trắng
Trà Sen Vái (M)
^66eb817370589ccd9f020c3a
Bac Xiu
^66eb83f87b8f2a79ba0d51a5
Steak Size XL
HAPPY DAY
Nước Suối
^66eb8e307c607c664001b714
Lẩu 2 ngăn
Thịt heo ba chỉ
Thịt bò mềm
Thịt mềm cắt lát
Cá viên
Rau tổng hợp
Coca cola
Nước suối
Bia Tiger bạc
Quầy gia vị
Cơm chiên trứng
Thịt heo tảng
Mồng tơi
^66ebb1bf864b7e217d0f0e51
PhaTea Tra Sua Thai Xanh 35z/1L
PhaTea Tra Sua Thai Do 35z/1L
^66ebb2e4b8cd5f945504bed0
Trà Chanh Thái (Thai Lemon Tea)
TC ChaTraMue (Sugar Boba)
Trà Sữa Thái (Thai Tea)
^66ebb55dfcd2e3c7e1075fb4
Tra Chanh Thái (Thai Lemon Tea)
Tra Sữa Thái (Thai Tea)
^66ebf1689fec9041d106c657
Cái nĩa
Ly sứ
Dĩa sứ
Muỗng
Dao inox dùng cho nhà bếp
DC mài dao
Túi Daiso size mini Túi số 2
^66ebf32ed59e130cdd00c0fc
Trà Nhân Sen (M)
^66ec4df09adfb821c809923c
Trà Sữa Legend 1 ly
Panna cotta Vải Hoa
^66ec4e27d8661ccbed0bddac
Trà Sữa Legend ly
Panna cotta Vải Hoa
^66ece6626aaaa20b2e080b58
snack mực vị rong biển talaethong gói 100g
thức uống dinh dưỡng socola lúa mạch lof malto hộp 180ml lốc 4
scu lên men hương cam lof malto hộp 180ml lốc 4
quà tặng: ly phí hành gia malto - km
^66ece6ac57e0cce56404f41a
snack mực vị rong biển talaethong 100g
thức uống dinh dưỡng socola lúa mạch lof malto 180ml
scu lên men hương cam lof malto 180ml
^66ece71fd428e2f1b8094402
snack mực vị rong biển talaethong gói 100g
thức uống dinh dưỡng socola lúa mạch lof malto hộp 180ml lốc 4
scu lên men hương cam lof malto hộp 180ml lốc 4
quà tặng: ly phi hành g à malto - km
^66ecee13cff8216a0809c299
Trà Sữa Legend ly
Panna cotta Vải Hoa
^66ecf648fa3e75c1c0066fb3
snack mực vỉ rong biển talaethong gói 100g
thức uống dinh dưỡng socola lúa mạch lof malto hộp 180ml
scu lên men hương cam lof malto hộp 180ml
quà tặng: ly phi hành gia malto - km
^66ecf6ee31abb4399407866a
Kem chống nắng Martiderm
^66ed01e25a90f3465400c922
Bắp cải trang CoopSelect
Bì đao COOP kg
Bì đậu COOP kg
Bánh đậu xanh
Cải bọ xôi
Nam tôm 250g
^66ed167211d5e2be2803d3bc
Trà Sữa Legend ly
Panna cotta Vải Hoa môn
^66ed88a2ebbcb8ac9d065d44
Café Sữa (M)
Bạc Xíu (M)
^66eda6259c5c9fb849064ba1
Café Sữa (M)
Bạc Xíu (M)
^66ee21d2205e1f5e5806a61a
Xà Lách Lổ Lồ Xanh Thủy Canh 200GR
Ôi Nữ Hoàng
^66ee221a5bdeb796550d6241
chuối già
hành lá
xà lách
dưa leo
trứng gà
phở tái
phở
phở bề bề
đậu nành
^66ee228b1c64718bc20ab070
chuối giống nam mỹ
hành lá bồ 300gr
xà lách lolo xanh
dưa leo
muối hường
trứng gà so hợp 10+2
phở bò tái lẫn đệ nhất gói 68g
sttt dalatmilk có đường hộp 180ml gói 4
phở bò cung đinh hà nội gói 86gr
^66ee3020f079bb2756074d12
White Coffee
^66ee3518c7743f01da099f40
SIGNATURE MAROU
^66ee3c5e997c95e858098baf
chuối giá giống nam mỹ
hành lá bó 330gr
xà lách lolo xanh (kg)
dưa leo
mướp hương
trứng gà so lộn 10+2
phở bò tái lẫn bệ nhất gói 68g
stt dalatmilk có đường hộp 180ml lốc 4
phở bò cung đình hà nội gói 88gr
^66ee3d258e57dbadb00943aa
chuối giá giống nam mỹ
hành lá bớ 330gr
xà lách lolo xanh
dưa leo
mướp hương
trứng gà so hợp 10+2
phở bò tái lăn đệ nhất gói 86g
phở bò cung đình hà nội gói 86gr
sữa đá dalatmilk có đường hợp 180ml lốc 4
^66ee70c9a9cacea8350f0689
Sườn heo nướng mè
Gỏi cuốn bánh ướt với bồ nướng
Cơm Chiên Hải Sản
Cá hú kho tộ
Canh chua tôm nấu dọn nân bớp
Coca
Bia tiger
Cơm trắng
^66ee8ec9314f099c010c7363
Bì đậu nôn kg
Dầu hũ trang
^66ee9990ce5c5f09810fe346
Trà Vải Khúc Bạch (M)
Trà Xoài Vàng (M)
Croissant Chà Bông PM Trứng Muối
^66eed00be91a6a53e2034416
Nước Ép Lựu
^66eef5e3cf76a956b109fe24
Milo Flan Trân Châu
Dâu Tây
^66ef85fef0431bb40d04594f
Sốt Vayo ít béo vị Nattkeu
^66ef8b75ee8864f0cf07ff84
Iced Pure Matcha Tea Latte
Dolce Espresso (BYO)
Dolce Espresso
^66efa768659b113d7204f888
Mon Nguoc Salted Caramel Cold Foam
^66efb18b14d45357ad0580bb
Phê cốt dừa
^66efbe8ddabf58f0c504aa74
Nước suối Dasani
Combo rau
Bông cải xanh
Bò hokubee hấp sớt tiêu - nấm mối
Sò điệp nhật hấp phố mai
Combo rau nấm
Cài thảo cuộn tôm thịt
Cá điều hồng hấp nước tương
Mì quảng xào hải sản
Nước ép cóc non
Xôi khúc
Nước sấu non
^66efd0fea413ff16df05a31f
Trà Sữa Chờm Chờm (L)
Trà Vải (L)
Vải (3T)
^66f0c3cc980f798731044a10
Xíu L
^66f0c65bf1abbca6b7061191
LKMI X-MEN Wood 50ml
^66f0f7ed6d3aaf36ca06633f
bún bò nam
Bún bò bình thường
Bún bò đặc biệt
^66f0f924e1e5ff554b0b8b02
bún bò nạm
Bún bò bình thường
Bún bò đặc biệt
^66f100032f9660ce380f034e
Bạc Xíu (L)
Trà oolong 80 - 100g
^66f101ab27a2beadeb03f1a2
Cơm thịt kho tiêu
Trứng Ốp La
Cơm thêm
^66f11c5aab0a78df46041fde
Trà Sữa Full Topping
Trà Sữa Cheese Ball
Trà Sữa Mochi Triple Cheese
^66f11cbe64137d759a03153c
Trà Sữa Full Topping
Trà Sữa Cheese Ball
Trà Sữa Mochi Triple Cheese
^66f11d2fd8234d69fc025662
Trà Sữa Full Topping
Trà Sữa Cheese Ball
Trà Sữa Mochi Triple Cheese
^66f11d68473184d4510c8349
Trà Sữa Full Topping
Trà Sữa Cheese Ball
Trà Sữa Mochi Triple Cheese
^66f1290fbb8b99a1ef04148e
Trà Sữa Truyền Thống
Trà Sữa Matcha
^66f129540eebc34d3c0b61c6
Mì cay cấpdộ cá viên xúc xích
Bánh tráng cuốn
Trà bí đào chia chia
^66f13b78319a20101606ed04
VEDAN Bột ngọt (ml chính) gói 454g
FRISTI Sữa chua uống vị cam 80ml
FRISTI Sữa chua uống hương dưa 80ml
THTRUE MILK Sữa tươi TT h. đậu 110ml
SLOBODA Dầu Hướng Dương Organic 1L
FRISTI Sữa chua vị cam sữa 100ml
^66f13bf76fbc4257020528b7
MEAT DELI [PRE] Thịt heo xay đặc biệt
^66f13c64b2df865cd70773d1
EVERREADY Pin shd 1212 bp4+2 aaa
^66f152f1e594862dae0e9183
Morning Rice Tea La1
Choco Sable
45K - Golden Melon
Freshness Preserve
^66f154677c5af2407d05ce0e
Morning Rice Tea Lal
Choco Sable
45K - Golden Melon
Freshness Preservel
^66f218edef6151e3ce0b1c47
Trà Yuzab Ô long Bách Hoa (M)
Bạc Xíu (L)
^66f21c7051e8a9a71a06903b
Mon Nuoc G AMERICANO
^66f2246ff8a3fc248809d94c
Cơm thịt kho tiêu
Trứng ốp la
Cơm thêm
^66f22fc3bc0ca1807007823e
dừa leo baby
xà lách lolo xanh
rau thơm các loại
hành lá bồ 300gr
^66f2461c1eb39ada2a070d98
Trà Sữa Thái Xanh
Trà sữa bắc hà
^66f24698aab8227c20013f60
Trà Sữa Thái Xanh
Trà sữa bạc hà
^66f2474f44b8b638610ba914
Trà Sữa Thái Xanh
Trà sữa bạc hà
^66f24b651ec3f0df7e066228
CK Mi Tron Indomie
CK Trung Op La
Adhoc Oct 24_NW_Only 1k Fried Egg when b
PhaPhin Ca Phe Den Da 12oz/1 Ly
^66f24ddc3eb4cb612603fa1a
FANNIE DRESS - XÁM - SIZE L
RIZZAN TOP - VÀNG NON - FREE SIZE
^66f2c31b02c8c35d500dafa1
Giấy note Macarons CL-SN002(36C)
Giấy note FIN 10*14 kê ngang
Bút Lông Crown P - 800W Đỏ
Bút Lông Dầu Crown P - 800W Đen
Tập note nhó - Checklist màu tím - NTN06
Tập note nhó - Notes - NTN01
Xếp hạng 999
Chuột chỉ máy bay S-021 hộp 18/132
Bít lông đầu 3529
^66f2d2fd1011ab4186021781
Croffle Bò Chà Bông Thái
Sương Sáo Mix
^66f2d344fde82916c90ab2ef
Khẽn Lành
Xòi Dừa
1/2 Gà Ngũ Vị
Ép Chanh Dây
^66f36ab3de12f5298b02e4de
Bạc Xỉu (L)
^66f389f5af614c2c300301a1
Soda Việt quất
^66f38aafaf614c2c300301fc
Soda Việt quất
^66f38b3cc189287d7900de7f
Giữ xe
Khăn lạnh
Vé Buffet Rau
Set mặn 2 người
^66f3cbf486dde0456a08c4a7
Trà Sữa Kiều Mạch
Trà Sữa Tiramisu
^66f3ccf5fa70cf325b0dbe2a
Trà Sữa Kiều Mạch
Trà Sữa Tiramisu
^66f3cdb32a23256c1b0c74c1
Trà Sữa Kiểu Mạch
Trà Sữa Tiramisu
^66f3d073157104c6c803b382
Trà Sữa Kiểu Mạch
Trà Sữa Tiramisu
^66f3d0dc4e3df245a40611ee
Trà Sữa Kiểu Mạch
Trà Sữa Tiramisu
^66f3dc01efc7d1758f05efdd
Cai cau vong 250g
Hung cay 50g
Rau dap ca 50g
Sa lach lo lo xanh COOP
Dua leo baby COOP kg
Gung goi 100g
Ot hiem 50g HUHU
Ca chua kg
Chanh khong hat kg
^66f3ecc218aa69c9da018965
Matcha Sữa Gấu Gấu Thái Lan/ Matcha Thai Bear
Matcha Latte Đá
^66f3ef2ee3cced8c7e04694e
Cai cau vong 250TN
Hung cay 50g
Rau dap ca 50g
Sa lach lo xanh COOP kg
Dua leo baby COOP kg
Gung goi 100g
Ot hiem 50HUYVU
Ot hiem Coop 50g
Ca chua Kg
Chanh khong hat kg
^66f3f0a0b55737c3dd04ebbb
Cải cầu vồng 250g
Bầu dài
Rau đắp ca 50g
Dưa leo baby COOP kg
Gừng gói 100g
Ớt hiểm 90g
Chanh không hạt kg
^66f45227e99552577207dd90
Trà Olong Sữa (M)
^66f4e2ba22463e205b0556e6
Chai xịt tẩy đa năng cho Ô Tô Flamingo 450ml mã F012
^66f4e61288e927a88008cd61
Bắp cải trai tím kg
Cà chua Kg
Ôi Trần Châu ruột đỏ 800g
Ba roi heo kg VS990
Sa lách lolo xanh thủy canh
Rau kinh giới 50g
Húng cay 50g
^66f4e7bf9ab4bd7a55056ace
Bắp cải trái tim kg
Cà chua Kg
Ôi Trần Châu ruột do 800g
Ba rọi heo kgVS990
Sà lách lolo xanh thủy canh
Rau kinh giới 50g
Hung cay 50g
^66f4f50b4ab19780330c762b
Bắp cải trái tim kg
Cà chua Kg
Cải châu ruột 800g
Bà rọi heo kg
Sà lách lolo xanh thu hoạch
Rau khôi giới 50g
Húng cay 50g
^66f520c78ac04061c608af9c
CHÁ BÒ ĐÙM
BÁNH PHỞ THÊM
TÀU HỦ KY
MÌ THÊM
VŨ HEO NƯỚNG
CƠM CHIÊN TRỨNG TÔI
KHÁN
ĐẬU HỦ RANG MUỐI HỒNG KÔNG
SỤN GÀ CHÁY TÔI
LẨU BÒ 450
NƯỚC SUỐI
NƯỚC NGỌT
^66f52ad694ae507186072ad5
BANAPEACONUT
Cơm dừa nếp non
TRÀ VẢI HOA NHAI
^66f54cd865e4a1ee36039f29
Trứng gà size L 10tVFood
Dưa leo Kg
Nạc roi heo xay VS990
^66f5578193010972a50beb0c
đậu hũ ta vị nguyên hợp 280g
rau mồng tơi gói 400gr
hẹ lá 100g
hành lá - ngò rí gói 100gr
lá giang - gói
cà chua beef
cà bẻ dún
táo gala mini nhập khẩu
vịt 1/2 con (kg)
cá basa cắt khúc
^66f562a31da0d2ec300d9b1e
BUFFET NGƯỜI LỚN
^66f57d62d4ff41dcb9003477
Hạt Châu Đường Mát (L)
Trà Oolong Nướng Sữa (M)
Hạt Châu Trắng
^66f57e3da528ed3086069679
Huyền Châu Đường Mát (L)
Trà Oolong Nương Sữa (M)
Trần Châu Trắng
^66f609af470f6dd9160b0658
Bac Xiu
^66f61e2c2ad8cb6707060432
Espresso Da
^66f648b4332aede803035ed7
Uot quay
Bun thuong
^66f65e25ac720d14c50700be
Chashu Ramen (Xa Xiu)
Udon Phile Ga Chien
Rong Bien Boc Thit Vien
Tra Da
Nuoc Gao
^66f69a3a35c126d79e0bdfa4
Aquafina chai 500ml
Redbull lon 250ml
Tay da (T)
^66f69c5e8a517e4a36036e83
Tra Sua Bac Ha L
Tran Chau Hoang Kim
Sua Viet Quat Dam
^66f6a243919d0889c20d4b67
Hong Tra
Chanh Day L
Tra Sua Vai L
^66f6a8710e6e86f9620b5ff8
Gia vi ngu vi huong TT 10g
^66f6afdc16d4e2f9030bd87f
trung ga so hop 10+2
khoai lang nhat
bun tuoi goi 500gr
bvs hang ngay huong tu nhien kk 20x48
chan gio heo c.p
hanh la bo 300gr
rau muong nuoc (bo)
^66f6c7b6f5802212050a6130
nước mắm nam ngư ớt tỏi lý sơn chai pet 300ml
mì sukiay vị hải sản gói 128gr
nước ngọt coke / coke giảm đường pet 600ml
cải thìa gói 300gr
diếp cá gói 100gr
rau thơm các loại 200g
bắp cải trái tim (kg)
giá sống (kg)
^66f7691be7994d4fea09d435
Bac Xiu (L)
Tra Sua O Long Bach Hoa (M)
^66f7822c86fc20d5b801b185
Nước tăng lực Sting dâu chai 330ml
Ức gà phi lê có da (kg)
^66f790cf4bf08786b30f7c39
TAY B.CAU VIM XANH B
CH
BCDR COLGATE SLIMSDF
^66f79cf801fe7ab7780bec23
T3.Snack da ca hoi tom n
^66f79d436b770f5e2209ceac
T3. Miếng gà chiên tiêu Pe
T3. Mỹ Iy Cung Đình lâu t
T3. Mì trộn khoai tây Oma
^66f7a21d5461e2d81a00911c
Be Thau Lay Tinh (Nira)
Ga Ran Com Nep (1/2)
De Chien Shun Yi
Tom Cu Sot Sa Te Ttom
Suon Rang Xot Xi Muoi
Bo Xao Ot Xanh Tieu
Trai Cay
Hu Sua Hong Kong
^66f7c9b5fb694f18520ae53c
Nuoc Dua Tuoi Nguyen Chat
Nuoc Dua Thai Lan Thach Dua Gion
Rau ma Sua Dua
^66f7e471b35c0623bd077e54
SB-BANH MI MUOI 130G
SB-BAGUETTE XOT BO TOI 260G
B.KARO TRUNG CBONG PM HK156G
BANH CA BONG BANG SOCOLA DD 145G
T. GA HAPPY EGG SZ 61-67 V. 10
STTT CGHL K. D BICH 180ML
STTT VNM 100%.D 180ML X4
^66f7e613522dad1d3a0f2316
Xuong ga CN CPMN 500g
^66f816eee6748956e80c0bb5
Com hop HQ - Thit heo chien xu (SC)
Banh Croissant pho hanh nhan 180g
^66f818bd5ef20d91bb08da94
NXY COMFORT HUONG TINH TE 3.7L TUI
STC LOF KUN HUONG TRAI CAY CHAI 85ML*
STC LOF KUN HUONG NHO CHAI 85ML*6
STC LOF KUN HUONG TAO XOAI CHAI 85ML*
NGU COC YAVA T.CAY NHIET DOI TUI 125G
SNACK MARINE BOY VI TOM 2P 70G
KEO DEO CO NHAN ALPENLIEBE TC HH 90G
K?0 NG?M MENTOS PF PEPERMINT KD HU 35
LO 5 SNACK ORION FUNNY 5 VI 120G
^66f8eed4651c4665dc0ab4be
Oi gionng Dai Loan kg
Tao Envy NewZealand size
Hat bi nv nuong kgK990
Tao do say deo kgK990
Tom the kg5160conkg
Hanh la 100g
^66f8fc87f82f06233103509e
Than noi (TENDERLOIN 200G)
Dau than ngoai (RIB EYE 400Gr)
Thit loi nac vai phu pho mai (CHEESE STEAK 200Gr)
Nuoc ngot COCA
Nuoc ep oi (GUAVA)
Nuoc ep hon hop (SOURCING BREEZE)
Khan uot (WET TISSUE)
^66f931edf3457c0a970d836b
Mam Thai du du ca kg
Nuoc mau Bep Xua BH 210g
Xoai keo kg
Rau om 50g
Rau ngo gai 50g
^66f93206062b46923e03a2f2
Mat Thai du du ca kg
Nuoc mau Bep xua BH 210g
Xoai keo kg
Rau om 50g
Rau ngo gai 50g
^66f945b730ebb9363204e91e
Trà đá
Pepsi
Chân gà tàu xì tương quế lam
Bánh cuốn tôm
Bầu đỏ sốt dầu hào
Cáo GU
Hạt điều tôm tươi
^66f95c520eba01aaed08459b
trung ga hop 10

---
3.Nhập API key của Gemini
---

In [ ]:
from google import genai
from google.genai import types

In [ ]:
# Khởi tạo Gemini client với API key
client = genai.Client(api_key="API Key của tôi")

In [ ]:
#  #Initialize the Gemini model (make sure to use the correct model name if needed)
# gemini_model = genai.GenerativeModel('gemini-1.5-flash-latest') # Uncomment if not initialized already

In [ ]:
import time

In [ ]:
prompt= """
Bạn là một hệ thống gán nhãn sản phẩm theo đơn hàng.
Nhiệm vụ: Gán nhãn cho từng hóa đơn và sản phẩm bên trong theo đúng định dạng dưới đây.
⚠️ QUY TẮC BẮT BUỘC:
1. Mỗi hóa đơn bắt đầu bằng dòng:
   *<Mã hóa đơn> - <Nhãn lớn>
   (ví dụ: *678f8770642a8c54e80fcdf7 - 1)
2. Mỗi sản phẩm trong hóa đơn được ghi trên 1 dòng, theo dạng:
   <Tên sản phẩm> - <Nhãn phụ>
   (ví dụ: Trà xoài hạt chia S - 1.1)
3. KHÔNG được trả về chỉ số đơn lẻ (ví dụ "1" hoặc "2" đứng một mình).
4. KHÔNG được bỏ sót tên sản phẩm.
5. KHÔNG được thay đổi tên sản phẩm đầu vào.
6. LUÔN phải tuân thủ đúng format như ví dụ.
--- Ví dụ ---
Input:
*678f8770642a8c54e80fcdf7
Trà xoài hạt chia S
Trà ổi hồng điều tay S
Yogurt trái cây
*678fa29b6cebc373bb047d9a
Bánh đậu xanh sen vàng Từ vị RVHG 400g
MIRINDA Nước ngọt soda kem 320ml
COCA-COLA Nước ngọt coca 390ml
LỘC XUÂN an khang 663g
TH Trà xanh vị chanh 350ml
OISHI Snack tôm cay db gói 68g/ 73g
Output:
*678f8770642a8c54e80fcdf7 - 1
Trà xoài hạt chia S - 1.1
Trà ổi hồng điều tay S - 1.2
Yogurt trái cây - 1.3
*678fa29b6cebc373bb047d9a - 4
Bánh đậu xanh sen vàng Từ vị RVHG 400g - 4.2
MIRINDA Nước ngọt soda kem 320ml - 4.10
COCA-COLA Nước ngọt coca 390ml - 4.10
LỘC XUÂN an khang 663g - 4.2
TH Trà xanh vị chanh 350ml - 4.10
OISHI Snack tôm cay db gói 68g/ 73g - 4.2
--- Hết ví dụ ---
--- DANH SÁCH NHÃN ---
1 Coffee: Đồ uống chính là cafe, sinh tố, ... kèm đồ ăn sáng/nhẹ
  1.1 Nước uống: trà, sinh tố, cafe
  1.2 Thức ăn đi kèm
  1.3 Tiệm bánh
  1.4 Trà sữa/Sữa tươi: trà sữa, sữa tươi
  1.5 Topping
2 Nhà hàng/Quán ăn
  2.1 Thức ăn chính
  2.2 Nước uống đi kèm
  2.3 Lung tung
4 Siêu thị: Thông thường nếu có sản phẩm như nhu yếu phẩm thì nhãn lớn phải là siêu thị
  4.1 Nhu yếu phẩm: Thịt cá, rau củ
  4.2 Đồ ăn vặt: Snack (oshi,yay,..); kẹo; bánh (bánh chocopie,..)
  4.3 Đồ điện máy
  4.4 Đồ gia dụng: nước giặt, nước lau nhà,...
  4.5 Đồ nội thất
  4.6 Hiệu sách: sách vở, hộp bút, văn phòng phẩm, truyện,...
  4.7 Đồ chơi trẻ em
  4.8 Chăm sóc cá nhân: băng vệ sinh,sữa tắm, dầu gội,...
  4.9 Sản phẩm cho bé: bỉm, sữa,..
  4.10 Sữa, thức uống: sữa, nước khoáng, nước ngọt, sữa chua,...
  4.11 Thức ăn chế biến sẵn: Các món mà có chế biến qua (Sấy, hấp, nướng,..)
  4.12 Trái cây
  4.13 Mĩ phẩm
5 Tổ hợp giải trí
  5.1 Escape room / board game café
  5.2 Sân thể thao
  5.3 Bar, pub, karaoke
  5.4 Rạp phim
  5.5 Show diễn nghệ thuật
  5.6 Khu vui chơi
  5.7 Gym & fitness
6 Nhà thuốc
  6.1 Mỹ phẩm
  6.2 Thuốc tây
  6.3 Thực phẩm chức năng
  6.4 Dụng cụ y tế
7 Nghỉ dưỡng
  7.1 Khách sạn
  7.2 Spa & chăm sóc sức khỏe
  7.3 Resort
8 Cửa hàng thời trang
  8.1 Áo quần
  8.2 Giày dép
  8.3 Thời trang khác
10 Làm đẹp bản thân
  10.1 Tiệm làm tóc
  10.2 Tiệm nail
11 Cửa hàng điện thoại & phụ kiện công nghệ
  11.1 Điện thoại
  11.2 Laptop
  11.3 Đồ điện tử khác
12 Tiệm sửa chữa điện thoại và máy tính
13 Studio chụp ảnh
14 Trung tâm ngoại ngữ
15 Tiệm sửa xe máy, ô tô
16 Cửa hàng cây cảnh & vật tư làm vườn
17 Dịch vụ tổ chức sự kiện & trang trí tiệc
18 Cửa hàng đồ thể thao
19 Cửa hàng đặc sản vùng miền
20 Cửa hàng hoa tươi & dịch vụ trang trí hoa
21 Dịch vụ vận chuyển & giao hàng nhanh
999 Khác
--- HẾT DANH SÁCH NHÃN ---
Bây giờ hãy xử lý dữ liệu sau theo đúng format ở trên:
{input_text}
"""

---
3.Bắt đầu dán nhãn

In [ ]:
# List to store the model's responses
gemini_responses = []

gemini_responses

In [ ]:
# Đây là cái chạy cho nhập chunk bắt đầu và chunk kết thúc
# Nhập phạm vi chunk muốn chạy (tính từ 1 cho dễ nhìn)
start_chunk = int(input("Nhập số chunk bắt đầu: "))
end_chunk = int(input("Nhập số chunk kết thúc: "))

# Đảm bảo không vượt ngoài phạm vi
start_chunk = max(1, start_chunk)
end_chunk = min(len(formatted_data_chunks), end_chunk)


# Duyệt qua range cần chạy (chú ý: index trong Python bắt đầu từ 0)
for i in range(start_chunk-1, end_chunk):
    try:
        print(f"Processing chunk {i+1}/{len(formatted_data_chunks)}")
        # Combine the prompt and the data chunk
        full_prompt = prompt + "\n" + formatted_data_chunks[i]
        response = client.models.generate_content(
            model="gemini-2.0-flash-lite",
            contents=full_prompt,
            config=types.GenerateContentConfig(
                thinking_config=types.ThinkingConfig(thinking_budget=0)
            ),
        )

        # Append the model's response to the list
        gemini_responses.append(response.text)

        # 🔹 Chỉ in ra response của chunk hiện tại
        print(f"\n--- Response for chunk {i+1} ---")
        print(response.text)
        print("-" * 20)

        # Pause 60s before next request
        if i < end_chunk - 1:
            print("⏳ Waiting 60s to avoid rate limit...")
            time.sleep(60)

    except Exception as e:
        print(f"Error processing chunk {i+1}: {e}")
        gemini_responses.append(f"Error processing chunk {i+1}: {e}")

Streaming output truncated to the last 5000 lines.
OVAL TINE Sua ti lua mach lo 400g - 4.10
TEA+ Tra Teas+ Oolong 1L - 4.10
YAKULT Sua chua uong len men 5bao - 4.10
SUSHI GVS 10 con gia doi 63g - 4.11
*67419235ce4ceaab8a09a8d4 - 4
Rau Ma Mix Cocochi (LON) - 4.1
Banh Trang Mix Pho Mai - 4.2
*67419193ce4ceaab8a09a7c9 - 1
4 Eggtarts - 1.2
Add 2 Eggtart - 1.2
*67418ff0379b4d44380ea1fc - 1
Iced Americano - 1.1
Extra Classic Syrup - 1.5
Extra Classic Syrup - 1.5
No Iced - 999
Iced Americano - 1.1
Extra Classic Syrup - 1.5
Extra Classic Syrup - 1.5
No Iced - 999
*67418fc3599d19bc06026ea3 - 1
Trà sữa Thiết Quan Âm (L) - 1.4
+ Sợi QQ - 1.5
+ Đường 70% - 1.5
*67418fa59c800090c8069983 - 1
Cà phê sữa / Milk Coffee - 1.1
Nước Ép Carot / Carrot juice - 1.1
*67418e8ae401daa85b0820ab - 1
Bạc xỉu đá - 1.1
*67418e58f4d21e3665074335 - 1
Banh Cake Chuoi - 1.2
Banh Crocot - 1.2
Vien Aux Chocolate - 1.2
Chuyen MXI - 1.2
*67418dd29ff24ed06008086d - 19
CayDamLungCapiNauRutMui - 19
Khan lau nguoi BL - 19
Discount P - 999
LUOI KEU HEO 3020 - 19
*67418d9fe401daa85b081f61 - 1
TRA SUA TRAN CHAU DUONG DEN (LANH) - 1.4
*67418d79717ef71b5b0301bf - 1
TRA CHANH LO HOI - 1.1
THACH DUA - 1.5
TRA DAO BON MUA - 1.1
*67418d0d47c739592d0d347e - 1
Super Sundae Tran Chau Duong Den (Kem Vani) - 1.5
*67418ce0717ef71b5b0300db - 1
Trà sữa nướng (lạnh) - 1.4
*67418cc4ff7eb78fbf08a70c - 4
hanh la goi 100g - 4.1
gao thơm lai 5kg - 4.1
*67418b9b793ce01a29026743 - 4
SIMPLY Dau huong duong chai 1L - 4.4
*67418b63959ea29e5b059b9e - 4
Kem Che Khuyet Diem XIAO YUMI 3 Vung 5G - 4.13
Hoa Nhan Tao - 999
Gia do dien thoai microphone - 11.3
Khan Mat Kho Da Nang Dung 1 Lan - 4.8
*67418b41f932848bbf08f3ed - 1
M-Green/1ut Milk Tea - 1.1
*67418ab147c739592d0d31dc - 8
Sandals F8B trang den size 42/42F8B0010 - 8.2
Sandal nam nu de cao F8B quai hau xoay full den son ombre size 43/43F8B1158 - 8.2
*6741897ff371515a200566c7 - 1
Bac Xiu PERCE%T - 1.1
Bac Xiu PERCE%T_Da - 1.1
*6741895a267477c22f0c625a - 4
Dutch Lady Sua TT it duong goi 180ml - 4.10
Dutch Lady Sua TT dau goi 180ml - 4.10
Vinamilk SDC khong duong F220ml - 4.10
TH True Milk Sua tuoi TT co duong 220ml - 4.10
Coca-Cola Nuoc ngot coca 1.5L - 4.10
Tiet Kiem Hoi Vien Win - 999
Omachi Mi K'ay xot tom chua cay 111g - 4.2
Acecook Mi vi lau Thai tom Modern 67g - 4.2
Cung Dinh Mi k.tay lau tom ch.cay ly 65g - 4.2
*6741894375c6f2a18d04151f - 1
Matcha Yuzu Citrus - Giảm ngọt - 1.1
Pink Guava Nitro Oolong Tea - Cold - 1.1
*67418928d04dff62c50a407d - 1
Mat Thien Thanh (M) - 1.1
*67418876d04dff62c50a3f37 - 2
Tra bi dao chia chia - 2.3
Banh trang tron - 2.3
Banh trang cuon - 2.3
*674188475bb492aa9101d9ce - 4
XÚC XÍCH TIỆT TRÙNG OH TEEN VỊ HEO CAY 65G - 4.2
TRÀ Ô LONG TEA+ CHANH 1L - 4.10
BẮP CẢI TRÁI TIM (KG) - 4.1
MÌ GORENG XÀO KHÔ VỊ ĐẶC BIỆT GÓI 85GR - 4.2
QUE SURIMI HƯỚNG CUA AKIRA 250G - 4.2
XÚC XÍCH ỚT XIÊM XANH G KITCHEN GÓI 200G (CB) - 4.2
*6741882970d07e79d00ef4c7 - 4
gao deo thom tui 5kg - 4.1
*6741879811e7a33a580e6aae - 1
Green Garlic - 1.2
Smart Aleck - 1.2
Cranberry Cream Cheese - 1.2
Ya Ya Egg Tart - 1.2
Rainbow Dry Cake - 1.2
Rainbow Donut - 1.2
*67418756267477c22f0c5ef9 - 4
HAO HAO Muoi cham Tom chua cay 120g 8934563065249 - 4.2
*67418711ba18e0f2610f259b - 1
Bac xiu - Size: M - 1.1
Matcha dua - Size M - 1.1
*674186f44c85b35b6b05790a - 1
Tra sua Thiet Quan Am (L) - 1.4
*674186ecc55a7dc40c05b596 - 4
Nuoc suoi - 4.10
Ve cuoi tuan T7-CN - 999
*674186d1e7f68f24e5074f64 - 1
COFFEE NAU FIN - 1.1
COFFEE MUOI - 1.1
TRA GUNG MAT ONG - 1.1
HUONG DUONG - 1.2
NAU LAC - 1.2
*674185fa97f321243a0b4e8b - 1
Nhất Trần Hồng Tụ (M) - 1.1
Tuyết Quan Sơn (M) - 1.1
*6741854f80f76dc265064e1d - 999
Dia Sushi - 999
*674184bb852cd7ed67020f83 - 11
Mouse Bắp 2.0T phụ kiện - 11.3
BL phú sĩ - 999
nến xoắn dài - 999
*6741849ad8d7be3ef80c1736 - 1
Combo 3 - Trà Sữa - 1.4
Matcha + **UPSIZE Vừa Trà - 1.5
+ Trà Sữa Hot&Cold - 1.4
+ CB - Khúc bạch - 1.5
+ Matcha - 1.5
+ Viên phô mai cà phê - 1.5
*67418235c01ee66c410aa0d3 - 6
SELSUN DAU GOI GIAM GA - 6.1
*674181ea09c92869d406f66e - 1
DONUT DAM BONG PHO MAI - 1.2
BANH NGOT XUC XICH SOT TIEU CAY - 1.2
*674181e97c23adb8bf06c9de - 1
Mon Nuoc G Peppermint Mocha Frappuccino - 1.1
Mon Nuoc G GREEN TEA CREAM FRAPP - 1.1
*674181b90f5f7636a2057a44 - 4
NGK COCA-COLA GIAM DUONG 1.5L - 4.10
BANH BAO NHÂN THIT 12 THO PHAT 500G - 4.11
BANH KHOAI MON MY? HUONG 300G - 4.2
SUA CHUA AN TAO SO RI TH TRUE YOGURT 100 - 4.10
BANH GIO NHÂN THIT THO PHAT - 4.11
XXIT TEEN ON-GO LC 35GX5 - 4.2
SUA LAC TRAI CAY NUVI CAM THACH 170ML*4 - 4.10
SUA CHUA UONG MEIJI VIET QUAT 150ML - 4.10
DAU THANH TRUYEN THONG 500G ABC - 4.10
RTC - CANH GA SA OT - 4.11
PACKED_LUON CA HOI - 4.11
VIEN HAI SAN TAM SAC KITKOOL 300G - 4.2
NUOC GIAT XA MAXKLEEN C.TRUOC TUI 3.6KG - 4.4
*6741819954bbbab5910f0c01 - 2
My Tuong Den - 2.1
My Cay - 2.1
*6741813efe350f0b8a0cc527 - 6
Bao xop nho (20x30) - 6.2
Tham tu lung danh Conan T. - 4.6
Dragon Ball Super T.20 - 4.6
*67418097c2fe38c4d50d8485 - 1
Nuoc Ep Chanh Vang - 1.1
Tra Nhai Vai - 1.1
Tra Kiwi Chanh Vang - 1.1
Tra Luu Hoa Peony - 1.1
*6741807076fe2328a60b20fe - 1
Tra Vai Lai (M) - 1.1
Hong Tra Sua (M) - 1.1
Topping thach konjac - 1.5
Hong Tra Dao Sua Thach Konjac (M) - 1.1
Hong Tra Dao Sua Thach Konjac (M) - 1.1
*6741805c0f5f7636a2057824 - 1
Tra Oolong Nhai - 1.1
Muoi - 999
*67417fab76fe2328a60b1ff7 - 1
Trà Oolong Nhài - 1.1
Muối - 999
*67417f55802ca7c8be0802b0 - 4
STC KUN HUONG NHO 180MLx4 - 4.10
SCU KUN VI KEM DAU 180MLx4 - 4.10
SCU KUN HUONG CAM 180MLx4 - 4.10
BG OMOP CF HOA HONG DMBL 3.9KG - 4.4
STTT MILK T.DI TOM 1L - 4.10
STTT MALTO SOCDB.HA 180MLx4 - 4.10
STTT MALTO SOCOL MACH 180MLx4 - 4.10
CAPHE SUA HIGHLANDS 235ML - 4.10
NN BIG COLA PET 3.1L - 4.10
STTT HL MILK N.CHAT 950ML - 4.10
8863673090171 SD NSPN XANH HOP 1.284G - 4.10
CL-DAU THUC VAT Y.M CHEF 5L - 4.4
NTL POWER IN 320ML - 4.10
TRA SUA LATTE PET 440ML - 4.10
STT VPMILK K.DIUNG 220ML - 4.10
*67417ed599e18a2a71004b39 - 1
Tra me cherry - 1.1
Tra sua Hong Kong - 1.1
*67417e61542618408104656f - 1
Chocolate (Nóng) - 1.1
Trà Oolong Nhài - 1.1
*67417e5fb7885879f20e461c - 4
NISSUI Thanh Cua Pho Mai 50g/1 G - 4.2
G Cha Lua Que Bi 50g/1 Goi - 4.11
NORBETA Banh Trung Cuon 89g/1 Ca - 4.2
TH Nuoc Tinh Khiet 500ml/1 Chai - 4.10
*67417e185b454fd47f0b7442 - 1
Tra Sen Vang Dua M - 1.1
*67417d0408d106ef5a0d6a53 - 2
Chashu Ramen (Xa Xiu) - 2.1
Ramen Tonkatsu (Heo) - 2.1
tra da - 2.2
*67417c70f2dacc09a50c03bd - 2
Cải thảo (Nửa phần) - 2.1
Đậu phụ ky cuộn (Nửa phần) - 2.1
Bắp bò tươi thái lát (Nửa phần) - 2.1
Túi Tiền May Mắn Trung Cá (Nửa phần) - 2.1
Hoa Khai Phú Quý (Nấm Tuyết) - 2.1
Cải cúc - 2.1
Thịt tôm sú băm (Nửa phần) - 2.1
Nấm đùi gà - 2.1
Thịt bò Haidilao (Nửa phần) - 2.1
Gia vị tự chọn - 2.3
Nước lẩu ngàn - 2.2
Đồ uống tự chọn - 2.2
Nấm linh chi trắng - 2.1
Rau Mồng Tơi (Nửa phần) - 2.1
Phục vụ cơ bản - 999
Mực phủ thủy (Nửa phần) - 2.1
*67417c6336172ee9d1015ecb - 1
Olong sữa đào - 1.1
50% ĐƯỜNG - 1.5
100% ĐÁ - 999
*67417be45ecab96236045ca2 - 2
ANTG 2CJ2Spag UP Chili Chicke Cjol Spag Spag UP rg BBQ Frie Reg Mirinda Reg Mirinda - 2.1
*67417bb37da1dc9c3c02e3e9 - 6
NATUREINE GEL LAM SAC - 6.1
*67417b6e2374f6f24e01b9f5 - 6
NATUREINE GEL LAM SAC - 6.1
*67417b53946ad870620d7a19 - 1
Tiramisu Khalua Coffee - 1.1
Trà dưa lưới táo xanh - 1.1
*67417b533c1ee10214047c5c - 1
Phin Sua Da M - 1.1
*67417b393c1ee10214047c25 - 2
NẠM - CHẢ CUA - 2.1
CHÉN TRỨNG - 2.1
THẬP CẨM LỚN - 2.1
BÚN GÂN - 2.1
*67417aed0e3c4db8d40235bd - 11
Dien thoai di dong realme RMX3033 - realme - 11.1
Km: tui ban hang vai (Hang khuyen mai khong thu tien) - 999
*67417adc24dd7ef1510a9eb2 - 4
Thịt heo xay 285613B033111 - 4.1
*67417a42c18d1bfeee0cf1ad - 1
Matcha Latte Đá/Ice - 1.1
Americano Ice/ Đá - 1.1
Cà Phê Sữa Đá - 1.1
*6741798d882951e634014545 - 4
HTRUE YOGURT SCA co duong 100g - 4.10
HEINEKEN Bia Silver lon cao 250ml - 4.10
*674179644d771bbcf706ac95 - 4
COCA-COLA Nuoc ngot coca 390ml - 4.10
HEINEKEN Bia Silver lon cao 250ml - 4.10
*67417940952c60c15b09f7aa - 4
Heineken Bia Silver Ion cao 250ml - 4.10
*67417912085d402c3301b94c - 4
HEINEKEN Bia Silver lon cao 250ml - 4.10
*674178f191f7bff64501de6e - 15
Voi bom 01 - DO 0.05S-II - 15
*674178c6085d402c3301b8e1 - 4
HEINEKEN Bia Silver lon cao 250ml - 4.10
TEA+ Tra oolong chai 320ml - 4.10
*6741785bf8ad222e910e7f2b - 4
HEINEKEN Bia Silver lon cao 250ml - 4.10
TEA+ Tra O long chanh chai 320ml - 4.10
*6741784486b729f24808b57a - 4
AVIE Nuoc Khoang 500ml/1 Chai - 4.10
Monthly Nov 24 - Mua 2 tang 1 - 999
*67417825965329e4fb06b25a - 1
CAFÉ ĐEN ĐÁ - 1.1
CAFÉ SỮA ĐÁ - 1.1
NƯỚC ÉP CAM - 1.1
*674177ff55bbd98be605e803 - 4
VINATHE Hat dieu pho mai goi 70g - 4.2
KITKAT Socola Chunky 3 thanh 114g - 4.2
HEINEKEN Bia Silver lon cao 250ml - 4.10
*674177c810a590352c0eda05 - 4
HEINEKEN Bia Silver lon cao 250ml - 4.10
*674177797313fb3e39091d70 - 1
Trà Mơ (Set 2 người) - 1.1
Hồng Trà Mơ Tươi - 1.1
*67417774952c60c15b09f624 - 1
Tra Sen Vang_D/l L (it duong it kem) - 1.1
Tra Sen Vang_D/l S (it duong it kem) - 1.1
*6741771586b729f24808b4db - 4
Tui nilon sieu thi T.do 10kg 35x60 55C/Kg - 4.4
Ngong Cai Lang Son - 4.1
Cai Lan lang son - 4.1
Rau Muong - 4.1
Xa lach - 4.1
Tui nilon sieu thi T.dong 5kg 30x50 87C/Kg - 4.4
Banh mi Star sandwich - 4.2
Nuoc ngot - 4.10
Tra xanh 1 - 4.10
Tra xanh 2 - 4.10
Bot canh nhat TA - 4.2
Gia vi (66)9081 - 4.4
*6741770b7e21c9e16008b76f - 1
Trà Thái Xoài - 1.1
*674176f891f7bff64501db9b - 4
C2 Freeze Tra Xanh Chanh Tuyet B - 4.10
C2 Tra Xanh Oi Hong Chanh Day 45 - 4.10
PICHI Banh Trang Tron Sate 100g - 4.2
LAY'S Khoai Tay Chien Tao Bien - 4.2
COSY Banh Que So Co La 117.6g - 4.2
*674176a77e21c9e16008b6bb - 1
Cloud Mousse Matcha Latte (Cốc lớn 16oz/Đá/Full đường) - 1.1
*67417676cc8e36d6a10c584d - 4
WMS-Ca Hoi Uc Fillet khuc giua 2657162100569 - 4.11
*674176191c4d4dbc1b08613a - 1
Hồng Trà Mơ Tươi - 1.1
Hồng Trà Chanh - 1.1
*674175b8f16ff5b679080564 - 2
Canh Phật Nhảy Tường (chen) lạnh - 2.1
*674175a3f16ff5b679080532 - 4
WMS-Ca Hoi Uc Fillet khuc giua - 4.11
*674174b4130cfc7eab0f2255 - 1
Hồng trà tắc xí muội (nhỏ) - 1.1
Hồng trà trân châu (lớn) - 1.1
CB Mì cay kim chi bò - 2.1
*67417484c9a47f7c8f0d8cb9 - 2
Mi kim chi hai san - Cap 2 - 2.1
Mi kim chi suon sun - Cap 4 - 2.1
Mi kim chi Bo My Cuon Nam - Cap 0 - 2.1
Banh Kimbap - 2.1
Tokbokki hai san - 2.1
Mi kim chi hai san - Cap 1 - 2.1
Mi kim chi hai san - Cap u - 2.1
Mi kim chi Bo My nam trung - Cap 0 - 2.1
*674174836bfe35b59c0615ca - 4
Ruot goi nam Coop Select 50x - 4.2
Ao thun nu NT PTV 6109.2 - 8.1
Q.nu short dkeo 821 - 8.1
Ao kieu nu NT A580 - 8.1
Q.tole nu lung 1thun PHQ-QFQ - 8.1
Ao goi nam Coop Select 50x70 - 8.1
*6741743b3013c4b3a10711e1 - 4
TRA OLONG TEA+ CHAI 450ML - 4.10
PHO BO TAI - 2.1
NC TT AQUARIUS CHAI 390ML - 4.10
*674173cae9953719c9023976 - 1
Bạc xỉu - 1.1
*674173c860cccd469606bdb2 - 1
TRÀ ĐÀO CAM SẢ (M) - 1.1
*674173a377712edaa602f22e - 1
TRA DAO CAM SA (M) - 1.1
*674172b177712edaa602f07a - 4
Snack oishi phomat - 4.2
Banh gao OrtonTB - 4.2
StingVangLon320ml - 4.10
StingdauLon320ml - 4.10
Tay da (T) - 6.1
*67417289657d6a870507b0fd - 1
Dua tuoi - CN trai - 4.12
Nuoc Thom Ep 1 ly - 1.1
*6741726298e7798c360cc1c4 - 4
Tay da (T) - 6.1
NTK MINISTOP chai 1L - 4.10
*674172511cb6326e1802e813 - 1
Sang Tao Sua Da ly - 1.1
Nuoc Cam Vat ly - 1.1
Ca phe dua ly - 1.1
*67417197d988e2db730b8166 - 999
Tui mua hang ACC - 250*200*70 - 999
Non tai beo-BM91 4438 - 999
Kinh chong anh sang xanh 1M - 999
*67417141273876781c0d1c1b - 1
Jasmine Green Tea - Iced - 1.1
*6741713e8297ba6d5b04eed5 - 1
HSNT - 999
Ngoc trai dau tam M - 1.5
Bac xiu da S - 1.1
House Cacao - 1.1
Chanh day da vien L - 1.1
*674171358dc95bcf6006264a - 1
O Long 4 Cheese (M) - 1.1
Tra Sua Nguyen La (L) - 1.1
Tran Chau Trang Extra - 1.5
*67417118aa16a515630788d6 - 1
Jasmine Green Tea - Iced - 1.1
*674170de273876781c0d1b5d - 2
Mi Kim chi bo My - 2.1
Khan lanh + Dung cu an uong - 999
*674170628bc04050d10975fc - 4
Kem ốc quế Bingxue (Mix) - 4.2
*6741704c64fb9302f6026b3e - 999
THUNGG - 999
*67417042414126eb0c084b69 - 2
COM CHAO BO (Beef Rice Skillet) - 2.1
MI TANTAN RAMEN (Tantan Ramen) - 2.1
*67416f5781d715a22b037c02 - 1
Bạc Xỉu Đá (L) - 1.1
*67416f5051e2c1616b004b02 - 6
Lau thai Ajiquick - 6.3
Diana Cool co canh - 6.1
Ca tom vien LC food 500g - 4.2
*67416f4ef8042f928e04e11f - 2
Mẹt Thịt Luộc - 2.1
Thịt Luộc Thêm - 2.1
*67416ee45cdb0b6e7d0c2c46 - 6
Laurier BVS supper slimguard 22.5cm 20M - 6.1
BVS Sieu tham Sieu mong 8 canh 8 M - 6.1
Sốt mayonnaise và chi muối canxi gói 20ml - 2.3
C.canh Sốt Tương ot Sriracha CD 250g - 2.3
*67416e93b960449b7d026a28 - 2
Com Burger Bo va Ga - 2.1
Ha cao tom
--------------------
⏳ Waiting 60s to avoid rate limit...
Processing chunk 51/70

--- Response for chunk 51 ---
```
*67409f968422b1312f09843f - 8
W CHAN VAY - 8.1
M AO KIEU - 8.1
*67409ea3120df9461c05d1bb - 1
Cafe Muoi - 1.1
Bac Xiu - 1.1
*67409e672cd959f93701c4f6 - 4
SDN Fami co nxi 1L*10 - 4.10
SC uong lem den Betagen cam 500ml - 4.10
Nuoc Col e Light Sleek 320ml - 4.10
Pepsi vi cao xanh khong calo on cao 33 - 4.10
Thit lon x py cao cap 170g Ha Long - 4.1
Phở trộn Le nhat Pho bo 84G - 4.11
My Hao tieu saté hanh tim 75gr - 4.2
My Hao lao saté hanh tim 75gr - 4.2
ACECOOK-Mi Hao 100 tom chua cay - 4.2
*67409da163e1f1d0c309ea83 - 2
Buffet 249k - 2.1
Buffet Pepsi 29k - 2.2
*67409d772e62c28fe0009b6e - 2
Canh Tom Yum cay voi tom - 2.1
Tra Thai xanh - 2.2
Pad Thai - 2.1
Goi mien tom co nho - 2.1
Dao suon cay - 2.1
Nguoi lon - 2.1
Bun tuoi - 2.1
Com chien dua - 2.1
Che tran chau hat ngoc - 2.1
*67409d6d59fb01379a04400e - 8
Ao ren dai tay qua tran LL - 8.1
*67409cfd63e1f1d0c309e962 - 1
Blizz Oreo - S - 1.1
Sundae Choco Extreme - 1.1
*67409cd9a286ec1a9d06d128 - 1
trà ổi dâu tây - 1.1
trà xoài cam vàng - 1.1
chocolate cookie - 1.3
*67409c9c10461c866e0f56d6 - 1
Blizz Oreo - S - 1.1
Sundae Choco Extreme - 1.1
*67409c651ac077c43304f32b - 4
ABC Dau Phu Non lang mo 300g - 4.11
Ca chua do - 4.1
*67409c40fcda16122d06716b - 4
Xúc xích ớt xiêm xanh G Kitchen gói 200g (cb) - 4.2
Xúc xích tiệt trùng Oh Teen vị heo cay 65g - 4.2
Mì Goreng xào khô vị đặc biệt gói 85gr - 4.2
Bắp cải trái TIM (kg) - 4.1
Que surimi hương cua AK'rol 250g - 4.2
Trà Ô Long TEA+ chanh 1l - 4.10
*67409c352e62c28fe0009954 - 4
Oi giong Dai Loan kg - 4.12
Gi vi ca kho rieng KNORR goi 2 - 4.11
Ca basa nc bo dau tam Uop k - 4.11
Rau ngo ri kg - 4.1
Hanh To Mien Bac kg - 4.1
Man Hanh To Mien Bac kg - 4.1
*67409c0d1ac077c43304f270 - 4
SCUI MS VNM PRDBT DUA GANG CHAI 65ML*5 - 4.10
SCUI MS VNM PRDBT VET QUAT CHAI 65ML*5 - 4.10
SCA VNM TT DUONG 100G*4 - 4.10
BANH TRUNG TUOI KARO CB 156G/192G - 4.2
XXTT CP RED 40G*5 - 4.2
NUI RAU CU CAO CAP MEIZAN CHU C 200G - 4.2
BVS H.NGAY DIANA SENSI COMPACT 20M - 4.8
BOT CHIEN GION MIWON 100G - 4.11
MI SPAGHETTI NO 5 SAN REMO 250G - 4.11
*67409bd4403a09c6dd00c66e - 4
COCA Nuoc ngot plus 320ml - 4.10
P/S KDR 1st rang trang tham linh+tre230g - 4.8
PLAYMORE kẹo the vi dao Sakura 22g - 4.2
*67409bcd782cab4de90af8a5 - 4
RAU MUC VI CAY HANWEI - 4.11
MUC ONG TAM VI CAY - 4.11
XUC XICH SUN GION - 4.2
THANH CUA VI CAY - 4.2
MI CAN CAY CHAY - 4.2
QUE CAY LAT HINH THANH GUOM SIWA - 4.2
QUE CAY CUON HINH THANH GUOM SIWA - 4.2
*67409b7fb8530c430c0f27a3 - 999
Thỏ 7 Màu-G121 - 999.1
*67409b5e10461c866e0f549a - 6
COLORKEY MN B5 HT SAN - 6.1
SOME BY MI MNA CICA CA - 6.1
*67409abf234ce452bb0906d4 - 1
Phe Truffle - ca phe - 1.1
Si Mo - Cold Brew O Long Mo Dao - size LAAA - 1.1
O Long Nhai Sua - tra sua (size Phe) - 1.4
Tran chau Phong Lan - 1.5
Phong Lan - tra sua (size Phe) - 1.4
Tran chau Phong Lan - 1.5
Bong - Cold Brew O Long Nhai Kem Cheese - 1.1
Khen lua dao - 1.2
*67409aad4c2f0012bf0d6242 - 1
Matcha Latte Da/Ice - 1.1
Berry Matcha Latte - 1.1
Sweet Grapefruit - 1.1
Lychee Pink - 1.1
*67409a91b4a761cc8c0e8094 - 4
Xuc xich roma Duc Viet 500g - 4.1
NG Omo matic comfort cua tren 3.6kg(3.9kg) - 4.4
Lan Nu NIVEA Extra sang min toi uu 50ml - 4.8
Khan mat soi tre cao cap Lux.SA Vietsun - 4.4
SCA Vinamilk trai cay, dau 100g - 4.10
*67409a7cb8530c430c0f25f7 - 999
Chiet 10ml Burberry Hero EDP - 999.1
Chiet 10ml Alexandria Fragrances Blu Talassim - 999.1
[QUA TANG] Vial Thierry Mugler Alien EDP - 999.1
*67409a79b8530c430c0f25df - 4
O mai pho co - Mo man ngot 200g - 4.2
Keo Alpenliebe huong bac ha nhan socola 26g (16/g) - 4.2
Keo mem huong chanh day hat chia 15/H - 4.2
*67409a76353246786a0e8e3c - 4
Nuoc khoang chanh Lemona 500ml - 4.10
PEPSI - TRA O LONG XANH 450ML - Chai - 4.10
*67409a64170ce2fd8807f7cf - 4
DUTCH LADY Sua tuoi co duong 180ml - 4.10
8934841901850 - 999.1
VNM Sua tuoi iet truong socola 180ml - 4.10
TH MISTORI ST sua mach 180ml - 4.10
DUTCH LADY Sua TT socola got 180ml - 4.10
THMILK Sua chua an Li duong 10g - 4.10
VINAMILK Sua chua an co duong 100g - 4.10
DIANA SENSI BVS HM khang khuan 20M - 4.8
YAKULT Sua chua uong len men 65ml1 - 4.10
*67409a610da14d1da2017b34 - 4
Xuc xich roma Duc Viet 500g - 4.1
NG Omo matic comfort cua tren 3.6kg(3.9kg) - 4.4
Lan Nu NIVEA Extra sang min toi uu 50ml - 4.8
Khan mat soi tre cao cap Lux.SA Vietsun - 4.4
SCA Vinamilk trai cay, dau 100g - 4.10
*67409a2a2bb97c24b409e8ea - 4
Kem ốc quế matcha Bingxue - 4.2
*674099fa234ce452bb090591 - 1
Tra sua Nguu ma vuong - 1.4
Tra matcha - 1.1
*674099ce170ce2fd8807f6d1 - 999
MUJI SHOPPING BAG S / TUI MUA - 999.1
HOP DUNG DO TRANG DIEM PP - 999.1
*674099cd8aba2727530af0d2 - 4
VINAMILK PROBI Sua Chua Uong 400 - 4.10
A-DEW Nuoc Suong Sao 450ml/1 Chai - 4.10
*67409795201cf3d0ad023ce2 - 999
HQS Ro 179K-DINH STICKER XANH 38 Q3.23 - 999.1
ATV HD- NON KET LEN XAM S50 KT-24JULY-23 - 999.1
*67409789164d57042c005f59 - 2
Ga Pop Tok (L) - 2.1
Sot Cklk (L) - 2.3
Ga Pop (M) - 2.1
Sot Cay HQ (M) - 2.3
*674096f39ec9178a25040d6d - 2
Mì Hải Sản - 2.1
Mì Bò - 2.1
Kim Bắp - 2.3
Coca - 2.2
Thêm Kim Chi - 2.3
Kim Chi Hộp 1 kg - 2.3
Khăn Lạnh - 2.3
*674096bd9ec9178a25040cfe - 999
TUI THUNG CAM LAP 10 - 999.1
XUC XICH IBERIACX T BAP - 999.1
CAY OT NGOT VN - 999.1
XUC XI TIEX IX LEC PP - 999.1
TRA DET GIAP PHAP BIOT - 999.1
*6740966d9ec9178a25040c77 - 999
THU BOP GIAM STRESS GA - 999.1
*67409602cdbe1c7d2808b406 - 1
Plain 32 layered til - 1.3
Choco Layer Croissa1 - 1.3
50k - Combo 2 Tart1 - 1.3
Cream Cheese Tart1 - 1.3
Egg Tart - 1.3
Choco Ball Donut - 1.3
*6740956b523111d49100b3f7 - 2
Pizza Hon Hop 18cm 2 - 2.1
*674094dcb78a13073a0bb781 - 4
Kitkool CornDog pho mai 80g - 4.2
VINAMIL < SCA Nep Cam 100g - 4.10
DALAT MILK Sua chua uong co duong 500ml - 4.10
Coupon 221000032408 - 999.1
*674094d119957acd4a05820e - 14
Bao xop nho - 14.1
Lop hoc rungs ron T.3 - 14.6
*6740941b3b8bf2220f064ddc - 2
BUFFET 229K - 2.1
*674093e87aa8e2869907db58 - 2
TOM XO NUONG MOI - 2.1
LAU CA BOP - 2.1
7 UP - 2.2
KHAN LANH - 2.3
BUN THEM - 2.1
*674093bacc5c0a37980dd236 - 8
KITTYs.01 - Sandal, Hồng, 25 - 8.2
*674093b1787fad85b0005916 - 999
Không có thông tin - 999.1
*67409318b78a13073a0bb554 - 999
Không có thông tin tên sản phẩm - 999.1
*674092dfb78a13073a0bb4fc - 1
Phindi Hanh Nhan L - 1.1
*674092d8ebeb887d7e0612dd - 1
Matcha Latte Da/Ice - 1.1
Bac xiu - 1.1
*67409278ebeb887d7e061245 - 4
GI K UOT EM BE CHOICE L 80M - 4.9
38 TUI RAC 50L(6L) BIOHOME - 4.4
KHAN RUT DA NANG FAIRY 100T - 4.4
*67409223989210ec2805378f - 4
OHII-SU Nuoc tuong toi ot 330ml - 4.11
MAGGI Dau hao chai 300g - 4.11
OHII-SU Tuong ot Sriracha QT 250gr - 4.11
Tiet Kiem Hoi vien WIN - 999.1
OISHI Snack vi Cookie kem vai 80g - 4.2
RELKON banh bo que socola pawpatrol 25G - 4.2
KM1 - 999.1
FAMI Soa dau nanh nguyen chat 200ml - 4.10
NUVI Jelly thach dao toi 110ml - 4.2
MIWON Bot chien gion them hat 100g - 4.11
KM1 - 999.1
Oishi Snack Bap Ngot Vi Pho Mai 34gr - 4.2
NEW CHOICE Thach re.cau trai cay 300g - 4.2
PLAYMORE Keo The Vi Dua Hau 22g - 4.2
*67409209b54f0bfbab006081 - 2
COM THIT HEO XAO LA QUE - 2.1
TRA OLONG TEA+ CHAI 450ML - 4.10
*674091dab17731c966008b07 - 4
CLOSEUP KDR WhiteNow khoang tu nhien100g - 4.8
RINDA Nuoc ngot chai 1.5L/1.75L - 4.10
COCA-COLA Nuoc ngot coca 2.25L - 4.10
TEA+ Tra Oolong Vi chanh 1L - 4.10
COLGATE BCDR cushion clean bo 2 - 4.8
FAMI Sua dau nanh canxi hop 1L - 4.10
VINAMILK Sua hat 9 loai hat 1L - 4.10
WONDERFARM Tra bi dao chai 440ml - 4.10
C2 Tra xanh huong chanh 455ml - 4.10

In [ ]:
gemini_responses

NameError: name 'gemini_responses' is not defined

In [ ]:
# # Đây là cái chạy tổng
# from google import genai
# from google.genai import types
# import time

# # List to store the model's responses
# gemini_responses = []

# # Iterate through the formatted data chunks and send to the model
# for i, chunk in enumerate(formatted_data_chunks):
#     try:
#         print(f"Processing chunk {i+1}/{len(formatted_data_chunks)}")
#         # Combine the prompt and the data chunk
#         full_prompt = prompt + "\n" + chunk
#         ## Gọi API Gemini
#         response = client.models.generate_content(
#             model="gemini-2.5-flash",
#             contents=full_prompt,
#             config=types.GenerateContentConfig(
#                 thinking_config=types.ThinkingConfig(thinking_budget=0)  # tắt "thinking"
#             ),
#         )

#         # Append the model's response to the list
#         gemini_responses.append(response.text)


#         # 🔹 Chỉ in ra response của chunk hiện tại
#         print(f"\n--- Response for chunk {i+1} ---")
#         print(response.text)
#         print("-" * 20)


#         # Pause 45s before next request
#         if i < len(formatted_data_chunks) - 1:
#             print("⏳ Waiting 45s to avoid rate limit...")
#             time.sleep(45)
#     except Exception as e:
#         print(f"Error processing chunk {i+1}: {e}")
#         gemini_responses.append(f"Error processing chunk {i+1}: {e}") # Append error message for tracking



# # You can now process the gemini_responses list as needed
# # For example, you could write it to a file or parse the results.

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
MUI RAU CU MEIZAN - 4.11
KEO DYNAMITE B.HA SO - 4.2
SNACK OISHI PHONG MU - 4.2
KEO DEO CHUPACHUPS - 4.2
CAI H-18 VG 250G - 4.1
SNACK DSTAR KHOAI TA - 4.2
CHAT HIA VG 250G - 4.1
SNACK OISHI BI DO 32 - 4.2
*6761a192e9d783f7240966bb - 4
Nuoc tinh khiet - 4.10
*6761a16cdc8c71174f0794f0 - 1
CB_HungKhoi M - Phin Sua Da M + BMQ Pate - 1.1
*67619f03b1f53b30690576f2 - 1
Da Me - 1.1
Yaourt Viet Quat - 1.1
Mi Ly - 1.2
Banh Flan - 1.2
Tra Sua Full - 1.4
*67619df3367987eb040e5d45 - 2
highball(chanh,bokbunja,mo) - 2.2
김치전 bánh kimchi - 2.1
계란찜 trứng hấp - 2.1
Set B,삼겹살+된장찌개+(600g)ba chỉ,vai giòn+thịt dê - 2.1
삼겹살(100g) thịt ba chỉ - 2.1
삼겹살(100g) thịt vai giòn - 2.1
콤라 coca - 2.2
맛밤비빔냉면 mỹ lạnh trộn size nhỏ - 2.1
맛밤비빔냉면 mỹ lạnh nước size nhỏ - 2.1
물냉 우설 냉면 mỹ lạnh nước size lớn - 2.1
*67619bf3b5b28a1e0002b112 - 1
CÀ PHÊ SỮA ĐÁ (M) - 1.1
TỨ QUÝ LONG NHÃN HẠT SEN KPM (M) - 1.1
*67619bcd106ee8e2ec0a2f23 - 4
Bút bi TL 079 - xanh - 4.6
*67619ad613b46eab7b0fad36 - 4
C2 Freeze Tra Den Huong Dua Luoi Bac Ha - 4.10
NW-Monthly Dec 24-Tiet kiem 50 p - 999
FUZE TEA Tra Chanh Sa 1L/1 Chai - 4.10
MILO So Co La Vien 30g/1 Goi - 4.10
*67619ab8369de5f7670fe9b0 - 1
Sua nong - 1.1
CaCao (Da/Nong) - 1.1
*67619a25b5b28a1e0002aff1 - 4
GIFT Nước giặt năng xuân 3,6kg*12 - 4.4
*67619a164c4ef56a5e0161e2 - 4
Đậu phu sống (khay 3 cái) 12368 - 4.1
Dừa xiêm (Dừa tiện lợi) 8938522789016 - 4.12
*676199f34ef04ccf8201c105 - 2
Lap xuong tuoi nuong - 2.1
*676199d24c4ef56a5e016190 - 8
Tui Xach Nho TXN844 Den - 8.3
Tui nylon - 999
Giay Sandal SD05104 Hong 35 - 8.2
*67619825367987eb040e5a06 - 1
Tra Chanh Mix Xoai (L) - 1.1
TRA SUA TRUYEN THONG (Size L) - 1.4
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 379/1435

--- Response for chunk 379 ---
*676196f187b1be4cb70481f2 - 8
ASM vai Sep.8 HN nt crop lai bau 2lui vuong A691 (TR) - 8.1
AT vua Dec.2 Sun co tron thieu voi 3559 (KN) - 8.1
QJ rong Sep.10 H2 tron 2tui xeo 5633 (XD/S) - 8.1
*6761968f369de5f7670fe763 - 999
Tien nuoc - 999
Thue VAT - 999
Phi MT rung - 999
Phi BVMT - 999
*676196124b309ee966073383 - 6
SANCOBA SANTEN 5ML - 6.2
SANLEN 0.1% SANTEN 5ML - 6.2
*6761958cb6ae1d864c0c8cac - 4
MEATDeli Chan ga - 4.1
*67619523e87e8821c80052ab - 4
Den doi moi - 4.4
Loc rac luoi - 4.4
Khan uot lau bep - 4.4
Cuon giay gau dau - 4.6
Chan ga rut xuong - 4.1
*676194c9e87e8821c8005274 - 4
Tao xay Up Hop - 4.12
*67619482a43d48cead06b2f9 - 999
Tiền nước - 999
Phí MT rừng - 999
Phí BVMT - 999
*67619426b6ae1d864c0c8bf4 - 4
Nuoc giat fily can 3kg5 - 4.4
Sua tam Hazelin - 4.8
Hat ngu coc granola - 4.11
*67619413369de5f7670fe5c0 - 1
Tra sua truyen thong (size M) - 1.4
Tran chau duong den - 1.5
70% duong - 1.5
*676193cf4ef04ccf8201bdd0 - 2
1ChOi W/Ri- OG - 2.1
1 FM Spag - 2.1
*6761936598f5c17e9807db4b - 4
Kem Banh Ca Tra Sua Tran Chau Snow Baby - 4.2
Kem Banh Ca Vani So Co La Snow Baby S 70 - 4.2
Banh Bao Chay 15g*12c An Phu C4C - 4.2
Xuc Xich TT Red CP 20x5 HN - 4.11
Mì Good Pho Ga 68G - 4.11
Khuyen Mai - 999
Bun Hang Nga Bo Hue 73GR - 4.11
Bun Hang Nga Bo Hue 73GR - 4.11
*67619338a43d48cead06b21c - 4
AEON Sushi 5000 - 4.11
Nuoc Tuong - 4.4
Mu Tac - 4.4
Sushi 5000 VND - 4.11
*676192f3b6ae1d864c0c8b17 - 4
Bánh Hàn Quốc - 4.2
Bánh Hàn Quốc Trà Xanh - 4.2
Obanyaki Nhân Đậu Đỏ - 4.2
Waffle Sữa Tươi - 4.2
*6761925d4ef04ccf8201bcdc - 4
CHIN-SU Tương ớt 1kg - 4.4
*676191f7e87e8821c80050f8 - 4
KOTEX BVS Style canh dem 28cm 4m - 4.8
*676191ec65e0e8602106bc83 - 8
Áo tay dài - 8.1
*676191aa7d08561de80093fc - 2
VM 1Chi W/Ri Soup - 2.1
1ChiCkn W/Rice - 2.1
Pumpkin Chicken - 2.1
1P Lrg 7up - 2.2
Fork - 2.3
Spoon - 2.3
*676191a94b309ee96607311b - 4
Karo cha bong gau nhan pho mai 98g - 4.2
Rong bien TKN BIG ROLL vi cay 3g (8 goi) - 4.2
FJM_Keo deo Mogu vi dao 50gr T40 - 4.2
FJM_Keo deo Mogu vi hong 50gr T40 - 4.2
Nuoc Chanh Vitamin C 140ml- C-Vitt - 4.10
Nuoc Luu Vitamin C 140ml - C-Vitt - 4.10
Nuoc Yen sao Green Bird lon 240ml T24 - 4.10
Sua chua uong it duong Morinaga 190ml - 4.10
Sua chua uong it duong dau Morinaga - 4.10
Tra sua thai - 4.10
*6761917ad00099363c01affc - 6
Chung nuoc mat - 6.2
Lo chit cum - 6.2
Lau 5 + 5 - 6.2
Bun - 6.2
Sua - 6.2
Bao - 6.2
Che do - 6.2
*676191617d08561de80093bc - 4
T3 Lay's vi tao bien 150g - 4.2
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 380/1435

--- Response for chunk 380 ---
*676191504ef04ccf8201bc0a - 4
CP Xuc xich Vealz goi 250g (MN) - 4.11
*6761913d7688feb91f06aaa2 - 2
CƠM NGHIÊU & THỊ - 2.1
*676190f7d00099363c01af7d - 4
Xuc xich Cheddar - 4.11
Banh kep Fine YEN MACH 178G - 4.2
Mi ly kho Cay Samyang 70g - 4.11
Bung Ga Lot - 4.11
Mi ly kho Cay Samyang vi Phu Mat 70G - 4.11
Bun Ga Lot Huyet Rong Bich Chi 200G - 4.11
Mi ly kho Cay Samyang Carborang - 4.11
Snack hai san tao gia vi Ot Duc Cay Bent - 4.2
Snack hai san voi Sot Cay Hai Duoc - 4.2
*676190a265e0e8602106bba6 - 4
KEM BANH CA TRA SUA TRAN CHAU SNOW BABY - 4.2
KEM BANH CA VANIS SO CO LA SNOW BABY - 4.2
BANH BAO CHAY 15G*12C AN PHO C40 - 4.11
XUC XICH TI RED CP 20X5 HN - 4.11
KHUYEN MAI MI GOOD PHO GA 68G - 4.11
BUN HANG NGA BO HUE 73GR - 4.11
BUN HANG NGA BO HUE 73GR - 4.11
*676190707d08561de800933a - 2
Nuoc Tuong - 2.3
Mo Tac - 2.3
Sushi 5000 VND - 2.1
Sushi 5000 VND - 2.1
*6761902dd00099363c01af0f - 4
CHIN-SU Tuong ot 1kg - 4.11
MEIZAN Mi trung Cao Cap Meizan 250g - 4.11
Ponni xuc xich xong khoi 450g - 4.11
*6761902525a8d272520dfe00 - 1
Banh Han Quoc - 1.3
Banh Han Quoc Tra Xanh - 1.3
Obanyaki Nhan Dau Do - 1.3
Waffle Sua Tuoi - 1.3
*67618ffc65e0e8602106bb52 - 2
VM 2Cj FFR UP Chili Chicke - 2.1
VM SpgCj - 2.1
*67618fe098f5c17e9807d8ef - 2
VM 1Chi W/Ri Soup 1Chickn W/Rice Pumpkin Chicken Reg Pepsi - 2.1
VM SWc GgionFFR Yum Swich GaGio Reg FF Reg Pepsi - 2.1
*67618fd2e87e8821c8004f9c - 1
SỮA TƯƠI TRÂN CHÂU HOA ĐẬU BIẾC - 1.4
*67618fc2e87e8821c8004f88 - 2
VM 2Chickn FFR - 2.1
Btl H2O - 2.2
*67618f914b309ee966072fd1 - 1
Lrg Ovaltines - 1.1
*67618f2f4d9c8b54170692d5 - 4
KITKAT Banh Socola Nestle 2F 17g - 4.2
KITKAT Socola 102g - 4.2
MILO Socola Thanh Chocobar 30G - 4.2
*67618d9821d476266c00b9ee - 2
SÉT GIA ĐÌNH - 2.1
*67618ced21d476266c00b95d - 8
ATM7004-GHI-M Áo Thun Đồng Nam GIÓ NHIỆT Cổ Tron - GHI - M - 8.1
PVM7011-GHI-M I Phao Vip Long Vu Nam Bé Đồng Phục Nhéch - GHI 90 - 8.1
*67618c28fb42cb6f1009802b - 2
Bánh Tráng Nướng Mắm Ruốc FULL - 2.1
CHÉN TRỨNG NƯỚNG - 2.1
Nem Chua Nướng - 2.1
*67618b83cf2b5497c6090933 - 4
BONCHA Tra Mat Ong Vi Dao 450ml - 4.10
NW-Monthly Dec 24-Tiet kiem 4k - 999
OTTO BM Tuoi Bo Sua 55g/1 Goi - 4.2
OTTO BM Tuoi SCL 55g/1 Goi - 4.2
NW-Monthly Dec 24-Mua 2 tang 1 - 999
LAFINA Nuoc Suoi Tinh Khiet 1.5L/1 Cha - 4.10
NW-Monthly Dec 24-Mua 2 tang 1 - 999
VITASOY SUA DAU Nanh 180ml/1 Hop - 4.10
NW Monthly Dec 24-Mua 1 tang 1 - 999
BONCHA Tra Mat Ong Vi Chanh 450ml - 4.10
*67618b15c251677a380bec94 - 4
Trai cay say VINAMIT - 4.11
Mi Omachi Xot Spaghe - 4.11
*67618ab463c097b693049407 - 4
Ly đá lớn x ly - 999
KIT KAT Socola Đen Đậm Vị 4F 35g X Thanh - 4.2
LOF sữa ngũ cốc dinh dưỡng g 180ml x hộp - 4.10
Jardin Cà Phê Americano Hạt Phí 400ml x chai - 4.10
*67618a889f39d30c460c8f42 - 4
CELANO Kem hop vani & hat scl 460ml\307g 89360-1772157 - 4.2
CELANO Kem hop caramen muoi 460ml\307g 89360-1772136 - 4.2
Lof Malto Malt Mint sua lua.mi 180ml 8936025774058 - 4.10
CLOSEUP BC\DR precision clean (bo 2) 89348\9133658 - 4.8
KM1 - 999
P/S KEM BAKING SODA & H.thao 180g 89348\9132135 - 4.8
KOKO V! Dai Mi xao 90 vi.hai san cay te95g 8936221042661 - 4.11
KOKO VI Dai Mi xao 90 vi bo xet ca 95g 8936221042676 - 4.11
GILLETTE Luoi dao VECTOR 2S 8888826016182 - 4.8
TEA+ Tra oolong chai 450ml 8934588870552 - 4.10
WMNK Cam ruot vang uc 2657221003105 - 4.12
Tiet Kiem Hoi Vien WIN - 999
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 381/1435

--- Response for chunk 381 ---
*67618984d2a53ced5e079b78 - 4
T3 Yen Sao 500ml - 4.10
*67618839915b66ede40b9c75 - 4
STK MINISTOP chai 1L - 4.10
*676187bef718d7fca503c687 - 4
KH.GIAY TEDDY BEAR M - 4.9
CHAO GAU DO THIT BAM - 4.11
CHAO GAU DO GA 50G - 4.11
MI XAO KHO INDOMIE B - 4.2
MI 3 MIEN REEVA TOM - 4.2
LO 5 MI KORENO VI LA - 4.2
XX COCKTAIL HEO XK C - 4.11
SANDWICH NHO 300G - 4.2
*676187be2fd5aa6159006eea - 2
Cơm thố ốp la - 2.1
*676185f4f718d7fca503c52e - 4
Bao Thach Bang Thun Y Te TR - 6.4
*67618596abdd06fbe901481d - 1
Espresso With Milk (S) - 1.1
Espresso With Milk (M) - 1.1
Phin Sữa (S) - 1.1
*6761849e915b66ede40b9a24 - 2
COMBO LỄ HỘI - 2.1
LTO GÀ SỐT CAY BBQ - 2.1
LTO - Gà sốt bơ tỏi - 2.1
Gà có xương (Không cay) - 2.1
Burger tôm (K Cay) - 2.1
Bắp cải trộn (S) - 2.3
Nước uống (M) - 2.2
GẤU BÔNG TUẦN LỘC - 4.7
*6761831d7d8edf0ca20c1d91 - 4
My Hao Hao Homeux Toc 30G - 4.2
Gao ST25 HG Big - 4.1
Tay Ao Dai Cu Mong Boi - 8.1
Goi Tom Giay Vi Huong - 4.2
NC La Oolong Tea Plus 6 - 4.10
Tam LT Thao Bac - 4.2
Nam My Cham Long HA1 - 4.1
NC La Oolong Tea K2 - 4.10
NC La Oolong Lao 1 - 4.10
Carot DA LA - 4.1
NC SS Mao Dui GA L 500 - 4.10
Canh Goi Vi MA - 4.2
Ngan 50 BR Heo - 4.1
Trung Vit Loan - 4.1
NC CB Dai My ND 100 - 4.10
Pho CB My Huong Trung - 4.2
*6761831bda3b0138e10cdd30 - 6
Marvelon - 6.2
*676182bc7d8edf0ca20c1d3f - 1
Tra Sua Phuc Long (M) - 1.4
*67617f576b70333fad0df27b - 4
chuoi gia giong nam my - 4.12
thit xay c.p - 4.1
chan gio heo c.p - 4.1
*67617f27a59c67c462039e8d - 4
Ca basa - 4.1
Cai ngot - 4.1
Quyt gio - 4.12
Cai thia - 4.1
*67617e55557b8181d8079d8a - 1
Hong Tra Chanh (M) - 1.1
*67617d2ff47da4224f0df2e9 - 1
Tra dao cam sa - 1.1
Socola da xay - 1.1
Huong duong - 1.2
*67617d00557b8181d8079c9e - 4
BIFESTA DAU TAY TRANG MAT (M.EYES) 30ML - 4.13
LUCIDO-L DAU DUONG TOC-SIEU MUOT 60ML-JP - 4.8
Thank you card_T923_Lazada - 999
*67617ce33fc199774206cffe - 2
CB1BigEx - 2.1
BPMai STD - 2.1
Pepsi L - 2.2
Dau Phong - 2.3
Vi Pho Mai - 2.3
*67617c33a59c67c462039cd5 - 10
Cuon giay hong da nang - 10.1
Luoc vuong to - 10.1
*67617b8a924f35d1590a01e2 - 2
St Vua, BBQ cat nho - 2.1
Mi bam pho - 2.1
7 Up 2 - 2.2
BLL - 2.1
Khan Lanh - 2.3
*67617b673fc199774206cf27 - 4
SDN ICHIBAN NG.CHAT IT NGOT 1L - 4.10
B.GAO JINJU GOLD H.COM SUA145G - 4.2
BANH AFC RAU CAI 300G/258G - 4.2
GUM XYLITOL LIME MINT 26.1G*1 - 4.2
OI CAT GOT 200GR - 4.12
MI HAI TOM CHUA CAY CC MILIKET75G - 4.2
MI HAI TOM SATE C.CAP MILIKET 75G - 4.2
MI KOKOMI DAI 90 TOM C.CAY 90G - 4.2
*67617b32f47da4224f0df1e9 - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X- MEN - 4.8
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 382/1435

--- Response for chunk 382 ---
*67617aabf2fa2579ff01a938 - 4
Bánh Xốp Ống Akiko Miniwaf Hải Hà Nhân Kem Dâu, Socola, Kem Cốm, Khoai Môn 330g - 4.2
Xà Bông Tắm X-Men - 4.8
*67617a713443d0083201a08c - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X- MEN - 4.8
*67617a49a8e296ea5e0e0b58 - 1
MATLATTE L - 1.1
50% DUONG SGR - 999
*67617a303443d0083201a04b - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X- MEN - 4.8
*67617981a8e296ea5e0e0ab4 - 4
Dưỡng sáng da VITC 400ML - 4.13
*6761796bf23091114902f58c - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X-MEN - 4.8
*67617959f2fa2579ff01a826 - 999
Nha VITC 400ML - 999
*6761794326f704f3640a32a1 - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X-MEN - 4.8
*676178daf2fa2579ff01a7ad - 4
BANH XOP ONG AKIKO MINIWAF HAI HA NHAN KEM DAU, SOCOLA, KEM COM, KHOAI MON 330G - 4.2
XA BONG TAM X-MEN - 4.8
*676178b5924f35d15909ffd1 - 4
GARNIER TAY TRANG SANG DA VITC 400ML - 4.13
*6761788df2fa2579ff01a771 - 999
LOSHERB TRI TRANG SANG DA WTC ADH M 1,2 - 999
*6761787926f704f3640a3204 - 2
Huda Lon - 2.2
Thuốc Exel - 6.2
Tiger Crystal Chai - 2.2
*676178653443d00832019ed9 - 4
GARNIER TAY TRANG SANG DA VITC 400ML - 4.13
*67617844f47da4224f0def7c - 4
GARNIER TAY TRANG SANG DA VITC 400ML - 4.13
*6761781a6b70333fad0dede0 - 2
Huda Lon - 2.2
Thuoc Exel - 6.2
Tiger Crystal Chai - 2.2
*67617806924f35d15909ff37 - 2
Chao Xa - 2.1
Nem Miho - 2.1
Tom Hinh LC - 2.1
Vien Phomai - 2.1
Cao Tam Giac - 2.1
XX Ngo - 2.1
Bo Vien - 2.1
XX Roi Do - 2.1
VTL Cac Mau - 2.1
Phomai Que - 2.1
*676177e53443d00832019e58 - 2
Huda Lon - 2.2
Thuốc Exel - 6.2
Tiger Crystal Chai - 2.2
*676177caa59c67c4620399ef - 2
HUDA LON - 2.2
Nước Exel - 6.2
TIGER CRYSTAL CHAI - 2.2
*676177b0f2fa2579ff01a6ac - 2
Huda Lon - 2.2
Thuoc Exel - 6.2
Tiger Crystal Chai - 2.2
*6761763d6b70333fad0dec2c - 2
Bào ngư sốt trứng muối (bánh mì) - 2.1
Hầu nướng mỡ hành - 2.1
Căng ghẹ rang muối - 2.1
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 383/1435

--- Response for chunk 383 ---
*6761760d466aaae6630dc217 - 1.1
Sipotea1 - 1.1
*67617584f47da4224f0decea - 4
Suong 1 men YAKULT ltd 10x65 - 4.10
Cachua tray NB1ch Coop Select - 4.1
Tao do Cripps Nam Phi nho kg - 4.12
Banh xep xa xiu TOPV 300g - 4.2
Dui ga CN t.khop 500g-Lebouch - 4.1
File ga cn htep 500g-Lebouch - 4.1
Ca bong bien lam sach kg - 4.1
TPS sua lmach MILO ltd bc 6x180 - 4.10
Sua dac Ong Tho chu xanh 380g - 4.10
Ntlec Rockstar lon 250ml - 4.10
Tuong ot Srir. CHOLI. pet 520g - 4.11
Dam tron salad CHOLI. 270g - 4.11
Caphe ht G7-3in1 bich 2goi x1 - 4.10
Duong mia khoang chat BH 1kg - 4.11
Ca nuc x.ca 3CGAI ck 3x155g - 4.11
Mit ron DEN HATS xuon xao ch. - 4.12
Banh mi tuoi floss otto 55g - 4.2
Bot tamkho c.gion Aji-quick - 4.11
Mi dd OMACHI bap bo r. cua 80g - 4.2
*67617525622e3f9c9a042ded - 1.1
MATLATTE - 1.1
TRA THANH XUAN - 1.1
30% DA - 1.5
MATLATTE - 1.1
*676174f8f23091114902f25b - 1.1
OL THAO MOC L - 1.1
30% DUONG SGR - 1.5
*6761717d8aa8d48d3c0332fd - 2
Bucket 3 COB - 2.1
3 Fried Chicken - 2.1
NSC Mix - 2.1
HS Mix - 2.1
M1 Y Pop (New) - 2.1
CL(R) & MP(R) - 2.1
Pepsi R - 2.2
MK Bucket3COB - 2.1
*6761713680f75aee070751a6 - 4.1
rau tần ô - 4.1
*676170ec74f9ea1fbf0396a4 - 4.1
rau tân ô 0.404 kg - 4.1
*676170daae1f931bf304f434 - 2
COMBO LỚN - 2.1
*676170c3ae1f931bf304f413 - 4.1
rau tần ô (kg) - 4.1
*676170a69ac1d65f8f020648 - 999
Ve xe buyt - 999
*676170948aa8d48d3c033224 - 4.1
rau tần ô - 4.1
*6761707180f75aee070750c0 - 999
Vé xe buýt - 999
*67617054c7500474f60d02e6 - 4.1
rau tần ô (kg) - 4.1
*67617016c7500474f60d028b - 4.1
rau tân ô - 4.1
*67616fedfb185e7d59038be7 - 4.1
Rau tan o (kg) - 4.1
*67616ef1fb185e7d59038b39 - 4
OMO Bot giat thong minh 800g/770g - 4.4
TUONG AN Dau me chai 400ml - 4.11
Tiet Kiem Hoi Vien WIN - 999
ALPENLIEBE Keo Sua Caramen 115.5g - 4.2
Than bo - 4.1
*67616c2d0e795973d90cc484 - 1.4
Tra Ngoc Trai Dau Tam L - 1.4
REBTATE_NAPAS_20KOFF - 999
*67616ba36887be25c308fab5 - 1.4
Milo Dam Kem Trung Oreo (L) - 1.4
*67616b7e52e1e8468c071f8f - 1.1
Trà Kiwi Nho Xanh (L) - 1.1
Trà sữa Thái Xanh Kem Trứng (L) - 1.4
*67616b58e00afac02a0503f1 - 1.1
Ca Phe Sua (M) - 1.1
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 384/1435

--- Response for chunk 384 ---
*67616b3b74f9ea1fbf039286 - 1
Siêu Cam Ép Mật Ong - 1.1
Oolong Nhài Sữa (S) - 1.1
*676169c58aa8d48d3c032d4c - 1
Trà sữa Nướng Yihetang (L) - 1.4
Xanh sữa Nướng Yihetang (L) - 1.4
*676169a70e795973d90cc273 - 1
Cà phê sữa - 1.1
Cà phê muối - 1.1
Bạc Xỉu - 1.1
*6761688e8aa8d48d3c032c5c - 999
2 VM 2Chik FFR - 999
*6761678a7cad655536005d1b - 11
SAC BASEUS SUPER SI 1 CONG 25W KEM CAP TYPE-C - 11.3
APPLE IPHONE 15 PLUS DAN CHONG VA DAP MOCOLL - 11.1
*67616617459a6d3e7902cefd - 1
CFL_Americano (N) - 1.1
KM doi nuoc TL8 (-54%) - 999
*676165e46d7ad2e66002c586 - 999
Cookies & Dream - 999
KMGH.OPHED.DIS20K - 999
*676165df03486a51720ac9ff - 4
Sprite chai 600ml - 4.10
SDNGreensoy kbsduong - 4.10
Ly Coke Xmas KM - 4.10
*676165b403486a51720ac9d1 - 4
XitGladeHoaLavender - 4.4
Xitcontrung ProX ARS - 4.4
*676165b2707bdd810d05d2fe - 2
Cha Gio - 2.1
Ca Tam Com Dep - 2.1
*6761659288a8b2bfae0f2a8e - 4
TO ganuong - 4.11
TO cahoi mayo - 4.11
Keo FF Cam Chanh 25g - 4.2
Keocaycontaubacha25g - 4.2
Keo cay con tau tao - 4.2
Chocolate milo 30g - 4.2
Oreo mini Vani 20.4g - 4.2
Oreo mini socola 20.4g - 4.2
OREO CHOCOLATE 64.4g - 4.2
*6761659003486a51720ac994 - 1
Tra Kiwi Nho Xanh (L) - 1.1
Tra sua Thai Xanh Kem Trung (L) - 1.4
*6761656c84929a498d03c2a9 - 1
Cà Phê Sữa (M) - 1.1
*6761655bf03c718a1d0ef6f2 - 4
BG OMO COMFORT TDT H - 4.4
DX DOVE DUONG ONG TU - 4.8
DG DOVE NGAN GAY RUN - 4.8
ST HAZELINE YEN MACH - 4.8
H.NEM KNORR HEO 900G - 4.4
*6761654ba9240034990dbd5c - 1
Tra Xoai Nam Phi (L) - 1.1
Tra Dua Nhiet Doi (L) - 1.1
Bac Xiu (M) - 1.1
*67616475b34b1bf64e0f164b - 1
Tra Kiwi Nho Xanh (L) - 1.1
Tra sua Thai Xanh Kem Trung (L) - 1.4
*6761644957721679b907de53 - 1
Tra Xoai Nam Phi (L) - 1.1
Tra Dua Nhiet Doi (L) - 1.1
Bac Xiu (M) - 1.1
*6761640803486a51720ac85e - 1
Ca Phe Sua (M) - 1.1
*6761639188a8b2bfae0f28d8 - 1
Olong Nguyen Ban - 1.1
*67616381707bdd810d05d120 - 1
Milo Dằm Kem Trứng Oreo (L) - 1.1
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 385/1435

--- Response for chunk 385 ---
*6761600bda2505aad009aaef - 2
Kimbab - 2.1
Cơm Cá ngừ - 2.1
Mì Chajang - 2.1
Meun Sangyeopsal - 2.1
Gà rán C.C2 - 2.1
Gà CC thêm - 2.1
Lẩu Bulgogi - 2.1
Lẩu Kimchi Heo - 2.1
Japchae - 2.1
Pepsi Không Calo - 2.2
*67615f12ed3ed01628061071 - 999
OP-MEO THAI TO - 999
SUN-GANG NHON PHS - 999
*67615eeded3ed01628061045 - 4
LO 2 BVS NGAY YEON - 4.8
*67615d0f452261dce4088af4 - 6
VIÊN NGẬM HOTEXCOL VỈ - 6.2
ACEMUC 200MG VIÊN - 6.2
*67615cbce64506447106f944 - 1
MATCHA LATTE - 1.1
MATCHA DUA DUA - 1.1
*67615bc99ff779ba4606c10e - 1
Matcha latte (L) - 1.1
Matcha latte (L) - 1.1
Matcha latte (L) - 1.1
Matcha latte (L) - 1.1
*67615abd701fc9867b08f5c9 - 4
CR36570 - Tap giay mau cao cap 10 to cung mau kho A4 CR36570 Grass green (297mm x 210mm) 31k (STAED) - 4.6
CR36571 - Tap giay mau cao cap 10 to cung mau kho A4 CR36571 Christmas green (297mm x 210mm) 31k (STAED) - 4.6
CR36558 - Tap giay mau cao cap 10 to cung mau kho A4 CR36558 G (297mm x 210mm) 31k (STAED) - 4.6
*676159e783e8fd4e10045286 - 999
Tui giang sinh dung size M+ - 999
*676159be52f6c13aea089d74 - 999
Tui giang sinh dung size M+ - 999
*6761593de64506447106f6f6 - 999
[COMBO 10 GOI] Pate cho meo Lam Dam: Ca Ngu mix Ca Com - 999
*67615914bb187bd6fa08e24a - 4
1 KM nu LASHIE sang da 50ml - 4.13
SATO145 - 999
Ly melamin 10 - 4.4
Chen inox 201 cn hiet mau 11cm - 4.4
*676158cf17ac2f9ef40155b9 - 4
Máy bay DKTX - Trực thăng tác chiến, DKB1313 - 346k (DCML) - 4.7
*676157f68523bb33070be5fb - 4
Giay A4 Exccel Dinh Luong 80GSM/A4 Loai 70GSM - 4.6
*676157305f782010750eb3f8 - 999
Mobifone 10.000 - 999
*676155f65f782010750eb309 - 999
Mobifone 10.000 - 999
*67615564b1904a5af7025665 - 4
Khay da vỉn kon - 4.4
*676154e384dbf0923200a05b - 999
ĐC Hoa hồng Robotime TW041 - 999
ĐC Hoa hồng đỏ Robotime TW042 - 999
ĐCLR Khu Vươn Trà Chiều Robotime DS038 - 999
ĐCLR Tiệm Sách Nắng Thơ Robotime DS040 - 999
Túi xốp - Túi xốp size vừa 30x42 - 999
*6761540784dbf09232009f9e - 1
Sua Tuoi Tran Chau Duong Den - 1.4
*676153708002f7ad5103654e - 999
DEONAULLE SAP KM NU S - 999
*6761533bee1698c15009b7c0 - 999
ROOM 1-2 - 999
--------------------
⏳ Waiting 45s to avoid rate limit...
Processing chunk 386/1435

--- Response for chunk 386 ---
*676152533b9b5ef1ca01b0a8 - 4
Mi ly Accoo Cay Kay vi bo 66g - 4.2
Xuc xich tieu Hung Visan 3 Bong Mai Bo 105g - 4.11
*67614f9eb75407c7d907908c - 2
Bò lúc - 2.1
C2 TRÀ ĐÀO - 2.2
Sữa chua đá - 2.2
Cà phê sữa phin - 2.2
Bò húc - 2.2
*67614f6bb75407c7d907905f - 1
Nuoc cam nguyen chat - 1.1
Sinh to viet quat - 1.1
Ca phe den phin - 1.1
Ca phe nuoi - 1.1
*67614f4c8cc0443b0207d15d - 1
Nuoc cam nguyen chat - 1.1
Sinh to voi quat - 1.1
Ca phe den phin - 1.1
Ca phe muoi - 1.1
*67614f26454b016479086118 - 1
Thuc Meo (goi) - 1.2
Nuoc Chanh - 1.1
Bai - 1.2
Ca phe sua phin - 1.1
*67614eee0130604e7704c3d1 - 4
Banh King Marine boy 56gr/20 - 4.2
Banh my cha bong Staff 60g/60 - 4.2
Banh Corn Chip vi bap nuong bo Orion 35gr/80 - 4.2
Xuc xich tion deu xot BBQ vissan 62g/48 - 4.11
Sua dau nach Nuti nguyen chat bich 200ml/36 - 4.10
Cai ngot Lang Son - 4.1
Bap cai - 4.1

KeyboardInterrupt:

In [ ]:
# Cái này là bản cũ
# List to store the model's responses
# gemini_responses = []

# # Iterate through the formatted data chunks and send to the model
# for i, chunk in enumerate(formatted_data_chunks):
#     try:
#         print(f"Processing chunk {i+1}/{len(formatted_data_chunks)}")
#         # Combine the prompt and the data chunk
#         full_prompt = prompt + "\n" + chunk
#         # Send the prompt to the Gemini model
#         response = gemini_model.generate_content(full_prompt)

#         # Append the model's response to the list
#         gemini_responses.append(response.text)

#         # 🔹 Chỉ in ra response của chunk hiện tại
#         print(f"\n--- Response for chunk {i+1} ---")
#         print(response.text)
#         print("-" * 20)

#         # Pause 45s before next request
#         if i < len(formatted_data_chunks) - 1:
#             print("⏳ Waiting 45s to avoid rate limit...")
#             time.sleep(45)

#     except Exception as e:
#         print(f"Error processing chunk {i+1}: {e}")
#         gemini_responses.append(f"Error processing chunk {i+1}: {e}") # Append error message for tracking

Processing chunk 1/1435

KeyboardInterrupt:

In [ ]:
# # Cái này để thử in ra 1 chunk coi thế nào
# # List to store the model's responses
# gemini_responses = []

# # Chỉ chạy thử với chunk đầu tiên
# try:
#     i = 0
#     chunk = formatted_data_chunks[i]
#     print(f"Processing chunk {i+1}/{len(formatted_data_chunks)}")

#     # Combine the prompt and the data chunk
#     full_prompt = prompt + "\n" + chunk

#     # Send the prompt to the Gemini model
#     response = gemini_model.generate_content(full_prompt)

#     # Append the model's response to the list
#     gemini_responses.append(response.text)

#     # Display the response
#     print("\n--- Example Gemini Responses ---")
#     print(f"--- Response {i+1} ---")
#     print(response.text)
#     print("-" * 20)

# except Exception as e:
#     print(f"Error processing chunk {i+1}: {e}")
#     gemini_responses.append(f"Error processing chunk {i+1}: {e}") # Append error message for tracking

Processing chunk 1/1435

KeyboardInterrupt:

In [ ]:
# import time
# try:
#     i = 0
#     chunk = formatted_data_chunks[i]
#     print(f"Processing chunk {i+1}/{len(formatted_data_chunks)}")
#     full_prompt = prompt + "\n" + chunk

#     start = time.time()
#     response = gemini_model.generate_content(full_prompt)
#     elapsed = time.time() - start

#     gemini_responses.append(response.text)

#     print(f"\n--- Response for chunk {i+1} (took {elapsed:.2f} sec) ---")
#     print(response.text[:500])  # chỉ in 500 ký tự đầu để test
#     print("-" * 20)

# except Exception as e:
#     print(f"Error processing chunk {i+1}: {e}")
#     gemini_responses.append(f"Error processing chunk {i+1}: {e}") # Append error message for tracking

Processing chunk 1/1435

KeyboardInterrupt:

---
4.Xử lý dữ liệu được label
---

In [ ]:
import pandas as pd
import re

def parse_receipt_blocks(data_list):
    parsed_data = []

    # Ghép list thành chuỗi rồi tách theo dấu *
    data_str = "".join(data_list)
    blocks = data_str.split("*")

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Lấy BillID và IndusLabel từ dòng đầu
        header_match = re.match(r'([0-9a-f]+)\s*-\s*(\d+)', block)
        if not header_match:
            continue
        bill_id = header_match.group(1)
        indus_label = header_match.group(2)

        # Tách các dòng sản phẩm (bỏ dòng đầu header)
        lines = block.split("\n")[1:]
        for line in lines:
            line = line.strip()
            if not line:
                continue
            # Sản phẩm dạng "Tên - Sector"
            prod_match = re.match(r'^(.*?)\s*-\s*([\d\.]+)$', line)
            if prod_match:
                product = prod_match.group(1).strip()
                sector = prod_match.group(2)
                parsed_data.append([bill_id, product, indus_label, sector])

    df = pd.DataFrame(parsed_data, columns=["BillID", "Product", "IndusLabel", "SectorLabel"])
    return df

In [ ]:
# ==== Test ====
df = parse_receipt_blocks(gemini_responses)
print(df.head(10))

                     BillID                                 Product  \
0  678fa2bcc81cf2c7e5059ff2                     Tra xoai hat chia S
1  678fa2bcc81cf2c7e5059ff2                  Tra oi hong dieu tay S
2  678fa2bcc81cf2c7e5059ff2                         Yogurt trai cay
3  678fa2bcc81cf2c7e5059ff2                         Matcha Da xay S
4  678fa29b6cebc373bb047d9a  Bánh đậu xanh sen vàng Từ vị RVHG 400g
5  678fa29b6cebc373bb047d9a        MIRINDA Nước ngọt soda kem 320ml
6  678fa29b6cebc373bb047d9a          COCA-COLA Nước ngọt coca 390ml
7  678fa29b6cebc373bb047d9a                  LỘC XUÂN an khang 663g
8  678fa29b6cebc373bb047d9a              TH Trà xanh vị chanh 350ml
9  678fa29b6cebc373bb047d9a     OISHI Snack tôm cay db gói 68g/ 73g

  IndusLabel SectorLabel
0          1         1.1
1          1         1.1
2          1         1.1
3          1         1.1
4          4         4.2
5          4        4.10
6          4        4.10
7          4         4.2
8          4        4.10
9          4         4.2

In [ ]:
# Export the DataFrame to an Excel file
output_file_path = 'labeled_data.xlsx'
df.to_excel(output_file_path, index=False)

print(f"DataFrame successfully exported to {output_file_path}")