In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

---
1.Nhập dữ liệu vào
---

In [ ]:
import pandas as pd

# Assuming the file is a CSV or similar format that pandas can read directly from the Drive path
file_path = '/content/drive/MyDrive/TT_DAIntern_Vidimi/Bản sao của Bản sao của bill_output.xlsx'

# You might need to adjust the read function based on the actual file type
try:
    df = pd.read_excel(file_path)
    display(df.head())
except Exception as e:
    print(f"Error reading file: {e}")
    print("Please check the file path and ensure the file is in a format pandas can read directly.")

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Tra xoai hat chia S,1.0,32000.0,NaN,NaN
1,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Tra oi hong dieu tay S,1.0,32000.0,NaN,NaN
2,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Yogurt trai cay,1.0,32000.0,NaN,NaN
3,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.0,NaN,2.0,678fa1f675c47814f10fe16f,NaN,NaN,1.0,NaN,NaN,Matcha Da xay S,1.0,39000.0,NaN,NaN
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.0,NaN,2.0,678fa1cf7fe852c11305676f,NaN,NaN,5.0,NaN,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.0,99000.0,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98322 entries, 0 to 98321
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Bill ID             98322 non-null  object
 1   Ngày                98322 non-null  datetime64[ns]
 2   User ID             98322 non-null  object
 3   Gender ID           75035 non-null  float64
 4   Unnamed: 4          0 non-null      float64
 5   Age ID              50305 non-null  float64
 6   Place ID            98322 non-null  object
 7   Vendor Brand ID     0 non-null      float64
 8   Original Brand Id   0 non-null      float64
 9   Nganh Hang ID       95352 non-null  float64
 10  Spend ID            0 non-null      float64
 11  Khu vực ID          96416 non-null  object
 12  Item Name           98172 non-null  object
 13  Item Number         98265 non-null  float64
 14  Item Price          98265 non-null  float64
 15  Item Number Clean   0 non-null      float64
 16  Item Price Clean    0 non-null      float64
 17  Ngày_only           98322 non-null  object
dtypes: datetime64[ns](1), float64(11), object(6)
memory usage: 13.5+ MB

---
2.EDA
---

In [ ]:
df['Item Price'].max()

1374882569.0

In [ ]:
max_price = df['Item Price'].max()
max_price_rows = df[df['Item Price'] == max_price]
display(max_price_rows)

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean,Ngày_only
43240,67506cd5e32725fd7a060aa6,2024-12-04 21:53:09,674e75425a588e17040fb569,NaN,NaN,NaN,674318ec2a8b20624604d627,NaN,NaN,1.0,NaN,5016fd6b7f8b9ac842000000,Cau lac bo,1.0,1.374883e+09,NaN,NaN,2024-12-04

count    9.826500e+04
mean     9.570630e+04
std      4.584854e+06
min     -2.301000e+06
25%      1.170000e+04
50%      2.850000e+04
75%      5.700000e+04
max      1.374883e+09
Name: Item Price, dtype: float64

In [ ]:
# Lọc ra những dòng có Item Price <= 0
price_items = df[df['Item Price'] > 0]
display(price_items)

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean,Ngày_only
0,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,NaN,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra xoai hat chia S,1.00,32000.00,NaN,NaN,2025-01-21
1,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,NaN,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Tra oi hong dieu tay S,1.00,32000.00,NaN,NaN,2025-01-21
2,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,NaN,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Yogurt trai cay,1.00,32000.00,NaN,NaN,2025-01-21
3,678fa2bcc81cf2c7e5059ff2,2025-01-21 20:35:56,678fa27a7fe852c1130568c8,1.00,NaN,2.00,678fa1f675c47814f10fe16f,NaN,NaN,1.00,NaN,NaN,Matcha Da xay S,1.00,39000.00,NaN,NaN,2025-01-21
4,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.00,NaN,2.00,678fa1cf7fe852c11305676f,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac842000027,Bánh đậu xanh sen vàng Từ vị RVHG 400g,1.00,99000.00,NaN,NaN,2025-01-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98317,66ab3dcf47abf7a4110ccc33,2024-08-01 14:48:31,659cc57f7da6ca614509ddc6,2.00,NaN,NaN,66ab3cf90840182e0a04367d,NaN,NaN,5.00,NaN,5016fd6b7f8b9ac842000000,sữa trái cây vị dầu vnm hero 110ml lốc 4,1.00,15800.00,NaN,NaN,2024-08-01
98318,66ab3dcf47abf7a4110ccc33,2024-08-01 14:48:31,659cc57f7da6ca614509ddc6,2.00,NaN,NaN,66ab3cf90840182e0a04367d,NaN,NaN,5.00,NaN,5016fd6b7f8b9ac842000000,bánh quy cosy dừa 132g/135g/126g/117.6g,1.00,12500.00,NaN,NaN,2024-08-01
98319,66a84505a75ea9001406cd44,2024-07-30 08:42:29,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66a4b965c3b84e2af30087d9,NaN,NaN,1.00,NaN,5016fd6b7f8b9ac842000000,Lẩu gà lá é size nhỏ,1.00,260000.00,NaN,NaN,2024-07-30
98320,66a84505a75ea9001406cd44,2024-07-30 08:42:29,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66a4b965c3b84e2af30087d9,NaN,NaN,1.00,NaN,5016fd6b7f8b9ac842000000,Nước suối,1.00,15000.00,NaN,NaN,2024-07-30
98321,66a84505a75ea9001406cd44,2024-07-30 08:42:29,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66a4b965c3b84e2af30087d9,NaN,NaN,1.00,NaN,5016fd6b7f8b9ac842000000,Bún thêm,1.00,15000.00,NaN,NaN,2024-07-30

In [ ]:
# Thống kê mô tả cho cột 'Item Price'
description = price_items['Item Price'].describe()
display(description)

count        91508.00
mean        103152.93
std        4751007.09
min              0.16
25%          15000.00
50%          30000.00
75%          60000.00
max     1374882569.00
Name: Item Price, dtype: float64

In [ ]:
min_price =  price_items['Item Price'].min()
min_price_rows =  price_items[ price_items['Item Price'] == min_price]
display(min_price_rows)

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean,Ngày_only
26232,6762391364c3287d200d0a0c,2024-12-18 09:53:07,674a753bf6e0759c7e0f4313,1.00,NaN,NaN,6745d955f8dae975650304ca,NaN,NaN,3.00,NaN,5016fd6c7f8b9ac84200003e,BULK GSLA16,1.00,0.16,NaN,NaN,2024-12-18

In [ ]:
# Lọc ra những dòng có Item Price < 1
low_price_items = price_items[price_items['Item Price'] < 1]
display(low_price_items)

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean,Ngày_only
26230,6762391364c3287d200d0a0c,2024-12-18 09:53:07,674a753bf6e0759c7e0f4313,1.00,NaN,NaN,6745d955f8dae975650304ca,NaN,NaN,3.00,NaN,5016fd6c7f8b9ac84200003e,ROMA TOMATOES,1.00,0.98,NaN,NaN,2024-12-18
26231,6762391364c3287d200d0a0c,2024-12-18 09:53:07,674a753bf6e0759c7e0f4313,1.00,NaN,NaN,6745d955f8dae975650304ca,NaN,NaN,3.00,NaN,5016fd6c7f8b9ac84200003e,BROCCOLI CROWN,1.00,0.37,NaN,NaN,2024-12-18
26232,6762391364c3287d200d0a0c,2024-12-18 09:53:07,674a753bf6e0759c7e0f4313,1.00,NaN,NaN,6745d955f8dae975650304ca,NaN,NaN,3.00,NaN,5016fd6c7f8b9ac84200003e,BULK GSLA16,1.00,0.16,NaN,NaN,2024-12-18
26233,6762391364c3287d200d0a0c,2024-12-18 09:53:07,674a753bf6e0759c7e0f4313,1.00,NaN,NaN,6745d955f8dae975650304ca,NaN,NaN,3.00,NaN,5016fd6c7f8b9ac84200003e,BULK ORANGE LAR09,1.00,0.53,NaN,NaN,2024-12-18
30856,675c34732fa050b7800dd423,2024-12-13 20:19:47,674aa1416afbe6500304f879,1.00,NaN,3.00,66b08f60ec8c709e6c050d33,NaN,NaN,NaN,NaN,5016fd6b7f8b9ac842000000,Phim Fujifilm Instant Colorfilm mini (10x2 pk)...,1.00,0.50,NaN,NaN,2024-12-13
33077,67594df9cd5ec437250bfe66,2024-12-11 15:31:53,67373ac6ce180aef5c07202d,1.00,NaN,NaN,673c972476cf067aad0dedf3,NaN,NaN,4.00,NaN,5016fd6b7f8b9ac842000000,Aioli Sauce Tub,1.00,0.60,NaN,NaN,2024-12-11
63259,67457a9e30d65e0a5a074e73,2024-11-26 14:37:02,67373ac6ce180aef5c07202d,1.00,NaN,NaN,67457a9223b613cd60091410,NaN,NaN,2.00,NaN,5016fd6b7f8b9ac842000000,Y MED BOOKS,1.00,0.99,NaN,NaN,2024-11-26
63590,6745531a6fee8e17fc0f5f00,2024-11-26 11:48:26,67382b70a090aa71dc079638,2.00,NaN,3.00,67375823c8e4e61801047f35,NaN,NaN,5.00,NaN,5016fd6b7f8b9ac842000000,Mi WAIWAI chay 60g,10.00,0.20,NaN,NaN,2024-11-26
65067,67444974438ce98f7e00219a,2024-11-25 16:55:00,67373ac6ce180aef5c07202d,1.00,NaN,NaN,67444964cc824aca26009200,NaN,NaN,4.00,NaN,NaN,Sweet & Sour Sce,1.00,0.50,NaN,NaN,2024-11-25

In [ ]:
len(low_price_items)

9

In [ ]:
# Calculate the 90th percentile of 'Item Price'
percentile_90 = df['Item Price'].quantile(0.99)
print(f"90% dữ liệu của Item Price nằm ở mốc: {percentile_90}")

90% dữ liệu của Item Price nằm ở mốc: 620000.0

In [ ]:
# Calculate Q1, Q3, and IQR for 'Item Price'
Q1 = price_items['Item Price'].quantile(0.25)
Q3 = price_items['Item Price'].quantile(0.75)
IQR = Q3 - Q1

# Define lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = price_items[(price_items['Item Price'] < lower_bound) | (price_items['Item Price'] > upper_bound)]

print(f"Lower bound for outliers: {lower_bound}")
print(f"Upper bound for outliers: {upper_bound}")
print(f"Number of outliers detected: {len(outliers)}")

# Display the outliers
display(outliers)

Lower bound for outliers: -52500.0
Upper bound for outliers: 127500.0
Number of outliers detected: 9303

,Bill ID,Ngày,User ID,Gender ID,Unnamed: 4,Age ID,Place ID,Vendor Brand ID,Original Brand Id,Nganh Hang ID,Spend ID,Khu vực ID,Item Name,Item Number,Item Price,Item Number Clean,Item Price Clean,Ngày_only
7,678fa29b6cebc373bb047d9a,2025-01-21 20:35:23,677e5bc6a48a0fc903087979,2.00,NaN,2.00,678fa1cf7fe852c11305676f,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac842000027,LỘC XUÂN an khang 663g,1.00,154000.00,NaN,NaN,2025-01-21
34,678f9ab3c8ab5063c90708e1,2025-01-21 20:01:39,674700bc4b2dc6e4d10f7f0d,NaN,NaN,2.00,6754ededacdb5fc83e0da53e,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac84200003e,NG XA MAXKLEEN HUYEN,2.00,130000.00,NaN,NaN,2025-01-21
56,678f9823a93aacb7bc0e2bdd,2025-01-21 19:50:43,673747178b714b73f70f26da,NaN,NaN,2.00,67616ee2be44905e5209d230,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac84200000f,KOKOLA Banh quy hon hop 700g,1.00,129000.00,NaN,NaN,2025-01-21
61,678f9823a93aacb7bc0e2bdd,2025-01-21 19:50:43,673747178b714b73f70f26da,NaN,NaN,2.00,67616ee2be44905e5209d230,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac84200000f,MEAT DELI Thit heo xay,0.37,146900.00,NaN,NaN,2025-01-21
62,678f9823a93aacb7bc0e2bdd,2025-01-21 19:50:43,673747178b714b73f70f26da,NaN,NaN,2.00,67616ee2be44905e5209d230,NaN,NaN,5.00,NaN,5016fd6c7f8b9ac84200000f,MEAT Deli Tim ga,0.45,185900.00,NaN,NaN,2025-01-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98295,66dd24465ce585c76609b18f,2024-09-08 11:12:54,646f04a3bed136fdd408f996,1.00,NaN,3.00,66dd17976832af76b202c1a0,NaN,NaN,2.00,NaN,5016fd6b7f8b9ac842000000,Kid's Mini Trio,1.00,140400.00,NaN,NaN,2024-09-08
98296,66dd24465ce585c76609b18f,2024-09-08 11:12:54,646f04a3bed136fdd408f996,1.00,NaN,3.00,66dd17976832af76b202c1a0,NaN,NaN,2.00,NaN,5016fd6b7f8b9ac842000000,Double Scoop,1.00,172800.00,NaN,NaN,2024-09-08
98311,66c9c5c3b828649bc20b07e9,2024-08-24 18:36:35,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66c9c59d00666eea96030573,NaN,NaN,2.00,NaN,5016fd6b7f8b9ac842000000,"9"" Thin Crust Madness (Madness Cheesy)",1.00,175000.00,NaN,NaN,2024-08-24
98312,66c9c5c3b828649bc20b07e9,2024-08-24 18:36:35,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66c9c59d00666eea96030573,NaN,NaN,2.00,NaN,5016fd6b7f8b9ac842000000,"9"" Thin Crust Pepper (Pepperoni Feast)",1.00,205000.00,NaN,NaN,2024-08-24
98319,66a84505a75ea9001406cd44,2024-07-30 08:42:29,5d9adf839d9b35e5318b4567,1.00,NaN,4.00,66a4b965c3b84e2af30087d9,NaN,NaN,1.00,NaN,5016fd6b7f8b9ac842000000,Lẩu gà lá é size nhỏ,1.00,260000.00,NaN,NaN,2024-07-30

---
2.Tiền xử lý và gian lận cũ
---

In [ ]:
# Chuyển cột "Ngày" sang datetime
df["Ngày"] = pd.to_datetime(df["Ngày"])

# Tạo thêm cột chỉ chứa ngày (YYYY-MM-DD)
df["Ngày_only"] = df["Ngày"].dt.date

In [ ]:
# Gom list sản phẩm cho từng bill
grouped = (
    df.groupby(["user_id", "bill_id", "Ngày_only", "Place ID"])["product_name"]
      .apply(set)  # dùng set để loại trùng sp trong 1 bill
      .reset_index()
)

In [ ]:
fraud_cases = []

def jaccard(a, b):
    return len(a & b) / len(a | b) if (a | b) else 0

threshold = 0.9  # ngưỡng giống nhau

# Lặp từng user
for (user, day, place), subdf in grouped.groupby(["user_id", "Ngày_only", "Place ID"]):
    bills = subdf.to_dict("records")
    for i in range(len(bills)):
        for j in range(i+1, len(bills)):
            sim = jaccard(bills[i]["product_name"], bills[j]["product_name"])
            if sim > threshold:
                fraud_cases.append({
                    "user_id": user,
                    "Ngày": day,
                    "Place ID": place,
                    "bill_id1": bills[i]["bill_id"],
                    "bill_id2": bills[j]["bill_id"],
                    "similarity": sim
                })

In [ ]:
def jaccard(a, b):
    return len(a & b) / len(a | b)

fraud_cases_sim = []
threshold = 0.9

for user, subdf in grouped.groupby("User ID"):
    bills = subdf.to_dict("records")
    for i in range(len(bills)):
        for j in range(i+1, len(bills)):
            sim = jaccard(bills[i]["Item Name"], bills[j]["Item Name"])
            if sim > threshold:
                fraud_cases_sim.append((user, bills[i]["Bill ID"], bills[j]["Bill ID"], sim))

In [ ]:
fraud_cases_sim[0]

('5ce2c3ee277035ae7332a134',
 '674d0bcdc92912e8660c16ec',
 '675036e6f073b0785e03be55',
 1.0)

---
2.Hàm check gian lận
---

In [ ]:
def detect_fraud(df, threshold=0.9, export_csv=False, csv_path="fraud_detected.csv"):
    """
    Detect gian lận hóa đơn dựa trên user_id, sản phẩm, ngày, place_id.
    Điều kiện:
        - Cùng user_id
        - Cùng ngày (YYYY-MM-DD)
        - Cùng Place ID
        - Tập sản phẩm trong bill giống nhau (theo Jaccard similarity > threshold)

    Parameters
    ----------
    df : pandas.DataFrame
        Yêu cầu có các cột:
            - "user_id"
            - "bill_id"
            - "product_name"
            - "Ngày" (datetime hoặc string)
            - "Place ID"
    threshold : float, optional
        Ngưỡng Jaccard similarity (0-1), mặc định = 0.9
    export_csv : bool, optional
        Nếu True thì export kết quả ra file CSV
    csv_path : str, optional
        Đường dẫn file csv xuất ra

    Returns
    -------
    fraud_df : pandas.DataFrame
        DataFrame chứa các cặp bill nghi ngờ gian lận
    """

    # --- 1. Chuẩn hóa cột Ngày ---
    df = df.copy()
    df["Ngày"] = pd.to_datetime(df["Ngày"])
    df["Ngày_only"] = df["Ngày"].dt.date

    # --- 2. Gom sản phẩm theo bill ---
    grouped = (
        df.groupby(["User ID", "Bill ID", "Ngày_only", "Place ID"])["Item Name"]
          .apply(set)  # tập sản phẩm để loại trùng trong 1 bill
          .reset_index()
    )

    # --- 3. Hàm tính Jaccard ---
    def jaccard(a, b):
        return len(a & b) / len(a | b) if (a | b) else 0

    # --- 4. So sánh trong từng (user, ngày, place) ---
    fraud_cases = []
    for (user, day, place), subdf in grouped.groupby(["User ID", "Ngày_only", "Place ID"]):
        bills = subdf.to_dict("records")
        for i in range(len(bills)):
            for j in range(i+1, len(bills)):
                sim = jaccard(bills[i]["Item Name"], bills[j]["Item Name"])
                if sim > threshold:
                    fraud_cases.append({
                        "User ID": user,
                        "Ngày_only": day,
                        "Place ID": place,
                        "bill_id1": bills[i]["Bill ID"],
                        "bill_id2": bills[j]["Bill ID"],
                        "similarity": sim
                    })

    fraud_df = pd.DataFrame(fraud_cases)

    # --- 5. Export nếu cần ---
    if export_csv and not fraud_df.empty:
      fraud_df.to_excel("fraud_cases.xlsx", index=False)
      print("Đã xuất file fraud_cases.xlsx")

    return fraud_df

In [ ]:
import pandas as pd

def detect_fraud(df, threshold=0.9, export_excel=False, excel_path="fraud_cases.xlsx"):

    # --- 1. Chuẩn hóa cột Ngày ---
    df = df.copy()
    df["Ngày"] = pd.to_datetime(df["Ngày"])
    df["Ngày_only"] = df["Ngày"].dt.date

    # --- 2. Gom sản phẩm theo bill ---
    grouped = (
        df.groupby(["User ID", "Bill ID", "Ngày_only", "Place ID"])["Item Name"]
          .apply(set)  # tập sản phẩm để loại trùng trong 1 bill
          .reset_index()
    )

    # --- 3. Hàm tính Jaccard ---
    def jaccard(a, b):
        return len(a & b) / len(a | b) if (a | b) else 0

    # --- 4. So sánh trong từng (user, ngày, place) ---
    fraud_groups = []
    for (user, day, place), subdf in grouped.groupby(["User ID", "Ngày_only", "Place ID"]):
        bills = subdf.to_dict("records")
        suspicious_bills = set()

        for i in range(len(bills)):
            for j in range(i+1, len(bills)):
                sim = jaccard(bills[i]["Item Name"], bills[j]["Item Name"])
                if sim > threshold:
                    suspicious_bills.add(bills[i]["Bill ID"])
                    suspicious_bills.add(bills[j]["Bill ID"])

        if suspicious_bills:  # chỉ lưu nếu có gian lận
            fraud_groups.append({
                "User ID": user,
                "Ngày_only": day,
                "Place ID": place,
                "bill_problem": list(suspicious_bills)  # danh sách bill
            })

    fraud_df = pd.DataFrame(fraud_groups)

    # --- 5. Export nếu cần ---
    if export_excel and not fraud_df.empty:
        fraud_df.to_excel(excel_path, index=False)
        print(f"Đã xuất file {excel_path}")

    return fraud_df

In [ ]:
result = detect_fraud(df, threshold=0.9, export_excel=True)
print(result)

Đã xuất file fraud_cases.xlsx
                      User ID   Ngày_only                  Place ID  \
0    5ed144dc408a530b088b4568  2025-01-04  6777839cd95b0c5a860880b4
1    643e6a450b819b09920cae65  2024-09-12  66e284bd1aed5e44ca0342fa
2    643e6a450b819b09920cae65  2024-09-17  66e284bd1aed5e44ca0342fa
3    643e6a450b819b09920cae65  2024-09-30  66e284bd1aed5e44ca0342fa
4    646f04a3bed136fdd408f996  2024-11-02  671eebef9392f10f680cdd86
..                        ...         ...                       ...
669  6778b374312b1aa4fd0f962f  2025-01-11  6736a9ad11b48879e2033a40
670  6779392e38617ea3bc0cfb9e  2025-01-04  677939d0150b3b383d04e609
671  677f80277e8e09358300f1ca  2025-01-09  677f85b379bf11f5660c2dd4
672  677f80277e8e09358300f1ca  2025-01-10  677f85b379bf11f5660c2dd4
673  67863927c34291d72b0ecf41  2025-01-14  678639f4689c6506e20718fb

                                          bill_problem
0    [677953ac76f9aa67f50d2bbd, 6779544e01f65365140...
1    [66e286f2c6bd30306f03b6bc, 66e2871b6f99b2191a0...
2    [66e911f72a5a119e45068843, 66e91143910d3599050...
3    [66fa156e3007298524070338, 66fa15a1c38c7f77670...
4    [6725a510289fd6811408a295, 6725a5506124cf56c30...
..                                                 ...
669  [678230d03e42ce91710c3e7b, 67822ff1fdcb68816e0...
670  [67793a71a099e65cf50a375b, 67793c0bb427b3d8a70...
671  [677f85b9806d51fcea034b9c, 677f862c07a33c10fa0...
672  [678098f7eb21f24aab0c49a5, 678097fe0b8fc7ff880...
673  [67863cfe5514f8f29403a200, 67863ccf5514f8f2940...

[674 rows x 4 columns]