In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

---
1.Nhập dữ liệu vào
---

In [ ]:
import pandas as pd

# Assuming the file is a CSV or similar format that pandas can read directly from the Drive path
file_path = '/content/Du-Lieu-Place.1758705431.xls'

# You might need to adjust the read function based on the actual file type
try:
    df = pd.read_excel(file_path)
    display(df.head())
except Exception as e:
    print(f"Error reading file: {e}")
    print("Please check the file path and ensure the file is in a format pandas can read directly.")

,ID,Trùng với ID,Tên,Lĩnh vực ID,Lĩnh vực Name,Tỉnh thành ID,Tỉnh thành Name,Brand ID,Brand Name,Địa chỉ
0,68d2de42cc9361574c028970,NaN,CGV Saigonres Nguyen Xi,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN
1,68d2db50ea440018b406378d,NaN,Lotte Cinema Gò Vấp,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN
2,68d2da3aa5272c273c0d4ec2,NaN,Dabaco Cinema Quế Võ,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN
3,68d2d9e2277ef09e45011bcc,NaN,Rạp Chiếu Phim Beta Thanh Hóa,14.0,Rạp phim,5016fd6c7f8b9ac842000036,Thanh Hóa,NaN,NaN,NaN
4,68d2c6e5946e8664910eb20d,NaN,Liberty Centre Point,NaN,NaN,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN

---
2.2.Biến đổi dữ liệu file output
---

In [ ]:
# Lọc ra cột ID với cột Tên
df1 = df[['ID', 'Tên']]

# Hiển thị 5 dòng đầu sau khi lọc cột
display(df1.head())

                         ID                            Tên
0  68d2de42cc9361574c028970        CGV Saigonres Nguyen Xi
1  68d2db50ea440018b406378d            Lotte Cinema Gò Vấp
2  68d2da3aa5272c273c0d4ec2           Dabaco Cinema Quế Võ
3  68d2d9e2277ef09e45011bcc  Rạp Chiếu Phim Beta Thanh Hóa
4  68d2c6e5946e8664910eb20d           Liberty Centre Point

In [ ]:
df1 = df1.copy()

In [ ]:
# Tạo cột mới dạng "ID-Tên"
df1["ID_Ten"] = df1["ID"].astype(str) + "-" + df1["Tên"]

In [ ]:
# Nếu bạn chỉ muốn lấy danh sách
result = df1["ID_Ten"].tolist()

In [ ]:
result

['68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi',
 '68d2db50ea440018b406378d-Lotte Cinema Gò Vấp',
 '68d2da3aa5272c273c0d4ec2-Dabaco Cinema Quế Võ',
 '68d2d9e2277ef09e45011bcc-Rạp Chiếu Phim Beta Thanh Hóa',
 '68d2c6e5946e8664910eb20d-Liberty Centre Point',
 '68d2bd489536bef0610f07ec-MUJI',
 '68d2820411e9c8fc800cabc6-Piccolo Coffee 36A Kỳ Đồng',
 '68d182be90af06000c00ec7e-Rau Má Mix',
 '68cffc5774460d688509885d-Hệ Thống Sửa Laptop - Macbook',
 '68cf612c4abd09b9ac0841f5-Start Coffee',
 '68cd2fc29a19853b4c04449f-Hasaki',
 '68cbf86fb8fcf295eb0c3f93-FUKATSU',
 '68ca5a8b5d2f4e819f0eb3fd-    ',
 '68ca2ba4ba74969dfe02d803-Hhh',
 '68ca2b42ba74969dfe02d764-Absabs',
 '68ca2b0f0d2d981b75013f82-     ',
 '68c6cc0d147524863503cd1c-Một Góc Hà Nội - 243/1 Tô Hiến Thành',
 '68c6c3e158b6baba290ee9fe-Naan & Masala',
 '68c5383f5c960e35620353c8-Lol',
 '68c536c34f0804d6a90b609e-Chưa có ',
 '68c536b66510354e5a020556-     ',
 '68c38ca8489f5f39fe0f509d-Jiangnam',
 '68c3839d9b95188c1d0fc005-Léhem Cafe',
 '68c29955d54529257a07d0d9-Vi Tính Thủ đức',
 '68c298a7869f7f2fd500109f-Nhà Sách Book Plaza',
 '68c2341eaf9aaaa0f60b78cb-Circle K - 105 Lê Trọng Tấn',
 '68c185348535c6282e0b41a6-Trà Sữa Phi Phi',
 '68bebeb4fda51f613e077dee-Gia Lam Sport',
 '68be3d703488457daa0096c4-CA TP HCM',
 '68bd877ed81c38f0c507fe93-Matsuya Phan Văn Trị',
 '68bc376217b3f3043e0481de-Z88 Phúc Hải',
 '68bc36090c49c85d9c0fa893-Sớm Khuya',
 '68bbdc81e97cd061ae0a40ee-24/24 Coffee D5',
 '68bbb114d5bc2ab0b503af21-LUX COFFEE - ĐẮK LẮK',
 '68bbb085fd0e93c1020bc56d-30Shine',
 '68b6693a1f97c15acd035a9a-Gà Tươi Mạnh Hoạch ',
 '68b5482c22ab44a0900f95fb-Bánh Canh Long Hương - Thúy',
 '68b45fefeffcea1bbb0b3d5a-Nhà Sách FAHASA Tiền Giang',
 '68b4540f91e7c24ed1038f37-Mr.Tôm Sushi',
 '68b3afd2c5755fae5a0dc01d-Karaoke Nốt Nhạc Vui Lê Văn Sỹ',
 '68b3397450fc16960409d117-Apple Store Online',
 '68b15d8a5b94ac50350fe761-GAIGARDEN',
 '68b061655c48502cf203035f-The Wish Coffee',
 '68af042bb55dccca9a089da3-Fahasa Vincom Quận 9',
 '68af029589bde9ccb601f1a4-Divine Shop',
 '68af01cdbefad4c5620da10f-Vựa Gym',
 '68aef8e3013b2d322a0a9d74-NS Biên Hòa',
 '68aed236b721098524042aae-Texas Chicken - Nguyễn Văn Cừ',
 '68aec39769d9b749810fb332-CSID',
 '68aea42c482ad27da40bf7b8-TMART',
 '68aea246281c2d9cad0787b0-PĐM MART',
 '68ae78d0f322d39afb019311-The Art Tea Lounge',
 '68adce41cd479cca410d3f52-LA FEE Tea & Coffee',
 '68adc32a6e93ef6a570e6f06-Trà Sữa Viên Viên',
 '68ad9473032a348e040d829f-Highlands',
 '68ac636545e4efb527006773-Co.opmart Bình Tân',
 '68aae512f38459b5d000635e-Co.opmart Nhiêu Lộc',
 '68aac2f18e52a7d6b30d77f2-Tâm Tâm Vegetarian Restaurant',
 '68aabbf17ed4ac8531050a9c-Bách Hóa Xanh',
 '68aa9b842e6779cffc04a301-Z88',
 '68aa8ef321cf66075a0b47ff-Nhà Sách Biên Hòa',
 '68a947b309cce1bfe305e0b6-Bách Hóa Xanh',
 '68a912f13b8633e8ba03df75-QandA',
 '68a81977187eb5dcf9033522-Thái Yên Coffee',
 '68a6f6fd9b8ec943c20a9d14-Kingfood ',
 '68a69c649c8aed49e00b9e5f-Highand Coffe',
 '68a5eba8517b8ec71a04d122-Lục Trà Thăng Hoa ',
 '68a5e9c8207942c5ee06076c-Lục Trà Thăng Hoa',
 '68a5e984e555046b4909badc-Lục Trà Thăng Hoa ',
 '68a5e95ee555046b4909b9bb-Lục Trà Thăng Hoa',
 '68a5a5688dfb7650550fa587-Shopee',
 '68a53fbe218916ea4000bf9d-Decathlon',
 '68a4163f7eaa63978b03a0af-Pharmacity Dương Thị Mười',
 '68a2f141222988aa050a4c78-Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép',
 '68a2e43bb14ec0d93400e6c3-Tiệm Nước Túi Bình Yên',
 '68a2d379d507f6d01a07ef36-Công Ty CP MetaUni',
 '68a2b45fcca87d0dc70119ce-SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM',
 '68a2895496a22ee1fc01dea8-HT CLB Doanh Nông',
 '68a14d0113735dda4707dbd6-Thegioixedapvt',
 '68a0b729f40057460600b7d8-MIXUE - NGUYỄN ẢNH THỦ',
 '689fe74254f229df2a0b3f6f-BHX',
 '689ee7916a484917e101fd14-Sync Coffee',
 '689ee19dc0ce6590c80fb6cd-Trường Đại Học Nguyễn Tất Thành',
 '689c29bdff2ba94f4703eb02-Nhà Hàng Chay Làng Ta',
 '689c0bb1f905e9bb170a2836-Guardian Bình Thới',
 '689c09d8c8d146721d0b6381-Cơm Niêu Bình Dân',
 '689b361188bc117512014afa-Sun Pet',
 '689b1edc01fe904a55071952-Tmart ',
 '689b16747ee34bb055007504-Trà/Bánh Tráng',
 '689acdefe21c7d9a6d0ea950-Haseyo Nguyễn Gia Trí',
 '689ac37f0223b5babc008ba4-GS25 - 511 HUỲNH VĂN BÁNH',
 '689a149f102266797901c9ea-Lục Trà Thăng Hoa  - Hoàng Diệu 2',
 '6899f39d01406402130c8d5f-Góc Của Tùng',
 '689747c4f1be0790590284c2-Cơm Ngon Đà Lạt',
 '689704cfaecef7e7bc0746ab-Warning Zone Nguyễn Văn Trỗi',
 '6896e8f215f7da2bf306c2a4-Quán Ăn Gia Đình Fresh',
 '6896cd885dc3e0f8d70dd9c4-Better Food Corner',
 '6896a709c0090dae09058df1-Better Food Corner CN1',
 '6895c98faaf5cb641503bd60-Better Food Corner CN2',
 '68958dfad0655801020bdfbe-Cơm Bắc Lan Hương',
 '689576222ee57988a6005b04-Không Gian Khởi Nghiệp Phú Nhuận',
 '68948dc152ace8706c011bf7-Tao Ngộ - Lẩu Gà Lá É Gà Đồi Tây Nguyên',
 '68936b853f6abc21c70cf2d8-Pharmacity',
 '68933578858144b97b0812cd-FamilyMart',
 '6892ce59d23883624309b4d6-Trà Sữa Phi Phi',
 '68921aa71a08a3b6e80e8fc6-Mì Cay Sasin - Bình Trị Đông B',
 '68915d8e77d83af8bd09302a-Pharmacity',
 '688f6d970627912011054936-Yori ',
 '688e19094738cbc72b0f41f3-HIFA',
 '688e18367b781467610280de-Circle K - 13 Tôn Đản',
 '688dd3b09fb4fc028b0f2110-Hej Matcha',
 '688c9f05d00b11a97f00a1dd-HAN Tea',
 '688b0ff74b2e0895c30e25fe-GUTA CAFE - 549 Điện Biên Phủ',
 '688af23589caa594190d86a7-Cơm Gà Giòn Giòn',
 '688a6cf86ecf05b30f03f542-Trà Sữa Thăng Hoa - Hoàng Diệu 2',
 '6889b9942bc907204a05089f-Mixue',
 '6889b3a5c63504ad350dd1c1-Another Space',
 '68898b6f61cb9fbfcd0201e6-Thành Coffee',
 '6888ce043b47ff0f6d06ea0d-Casio HCM',
 '68873fef243409325703d595-MV Food & Drink',
 '6887105d9b76753f950b2694-Mr.Eco Salad Healthy',
 '688601b4d4a8c0fa3f0afc83-Pizza Có Tâm',
 '68820fa5413cb1dfa002207d-Nhà Của Thời Thanh Xuân',
 "687e4b4c832afb99c901e42a-Lyn's Chicken",
 '687e2dfc4b84bd27d602f671-Cháo Ếch Singapo',
 '687cc4bdb60896ca2c08d90a-Phamacity',
 '687ca27b95cc713e1a069c68-HIGHLANDS - LÝ CHÍNH THẮNG',
 '687b3ca60cd23608eb01ba92-BÁCH HOÁ XANH - 234 HOÀNG HOA THÁM',
 '687b1b445757ebed1e0a01d0-HIGHLANDS COFFEE - ĐỨC TRỌNG',
 '6878f4accc12d6e77f0d6651-Famarcity ',
 '6878f490cc12d6e77f0d662b-Famarcity ',
 '6878e499e131880aae086f21-Lục Coffee & Tea',
 '6878df6989e0b7a3980dc8ef-Mì Quảng Ăn Là Nhớ',
 '6878c7f1d08042df55085a61-My Cafe',
 '6877c23d2cc7b484f205a688-Hằng Lê Trà Sữa ',
 '6877973dfa0fc330f0058328-Lẩu Cá Kèo Chị Tôi',
 '687771fc4f2307d1780564e9-Sowee Space',
 '68767a43d15605ecd00ac765-MINISTOP -  87 VẠN KIẾP',
 '68762acf6328af071207bf4d-Khách Sạn Sân Vườn Hà Giang 2',
 '6874f4fcd47d97f2de00aaaa-Cộng đồng Design Thinking - Techfest VN',
 '687330ef00ec32366706bb39-Thè M Cafe',
 '6873238908538e0e540d09cf-Coop Mart',
 '687305620fa540ae4203d4f1-Cafe Amazon',
 '686f7986d0071401cd047f22-Demo',
 '686f656be89127d1230221d9-CO',
 '686f52955ef920311b05dc29-Cá Ơi Làng Chài',
 '686dff07f262f568fc06df4d-Jollibee Vạn Hạnh Mall',
 '686dfee887f39ff57c0ed64f-Jollibee Vạn Hạnh Mall',
 '686dc9441dfb73a7e70dc5e8-HIGHLANDS COFFEE - PHẠM VĂN ĐỒNG',
 '686cd280c43efc0888069b30-Xịn House Design ',
 '686c9afb6384edb1be0d4351-Xịn House Design ',
 '686c92bdae2402127603c856-Xịn House Design ',
 '686b4a51d8831e60f80b6437-HIGHLANDS COFFEE - VINWONDERS',
 '686b3ec2a3f83eacd90b53f2-Vị Cà Phê',
 '686a38523d153c07720483b2-BÁCH HOÁ XANH - 173 BÙI ĐÌNH TUÝ',
 '686a35b7ffca6b6b4f0a2263-Mangrove',
 '6869426f5095b2086e0ddbd8-Pharmacity',
 '68692c07d7593087810221f6-Ăn Vặt 148',
 '6868d73bb2cb722fb00b5058-CLB ROPOLY',
 '6866119d9ff61d515d01a29b-Tiệm Cà Phê Xứ Nam Kỳ',
 '68654ef63375be60d904d2ff-Pharnacity',
 '68649b159aa2165a0d05352b-Cafe 24/24',
 '68648987c26933c0d2008f7d-Circle K - 106 Hoàng Diệu',
 '6863b544c9eb3c10b60f75ab-Fuji Mart Tân Mai',
 '68629331580df7b7c5065536-Starbuck - Quang Trung',
 '68629274e63af9122503659a-Sun Pet',
 '6862905fe24909a5f707a408-Lẩu Gật Gù',
 '68627d93cf0eeeb8720397cb-KYO WATAMI Grill & Sushi',
 '686233b641b885e5b30a656c-Phát Đạt Dental',
 '68614cdd498b547dc706b370-7 Map',
 '686135f6c940db29c801aabf-Lẩu Cá Mang Về 69k',
 '6860e8a5767a67702e052dfe-Xịn House',
 '685ff5fd01db61a6560451c1-Lẩu Phong Vị 24H',
 '685ff595fee372bf2c0cd43d-Lẩu Phong Vị 24H',
 '685f8161f1d049f2360bf326-COCÉVI Coffee And Chill',
 '685e724a672f1fc415008b3d-B-S Mart',
 '685e0cd4358056f736072355-COCÉVI Coffee And Chill',
 '685d2ec992503ebd140a9ed3-Circle K - D5',
 '685cd2f4d635521ddf09d881-Haga',
 '685cd2b5d635521ddf09d81c-Anc',
 '685cd15deb90e320be003d1d-Trà Sữa Shiney',
 '685cd09dc93ab13cda012bad-Trà Sữa Shiney',
 '685c09859a93e297e30be332-Tacos Labubu',
 '685bd92db1a548fad10bedd7-Takashimaya',
 '685bd725b49528302c0b873b-Cây Đầu To',
 '685bd71aff05da42680b6bf6-Cây Đầu To',
 '685bc3f06c348405ef03dd5c-Cà Rề Cafe',
 '685aad92653f27aea70bea19-Vinamilk',
 '685a9f1844d2b42c1f09686c-Yolo BBQ',
 '685a926eaeba1bed9f0383a4-Metro Khu Công Nghệ Cao',
 '685a74557a005a2c150d0141-Street Coffee ',
 '685a62b5d19a80e1e109a02b-HIGHLANDS COFFEE - MENAS MALL',
 '685a622ca63f105b680ac5dd-HIGHLANDS COFFEE - MENAS MALL',
 '685a36d28bbba8fd49008bb8-Metro Bến Thành',
 '685a2ee244b9eb49bc0ba6ac-Kim Đô',
 '6859f1053a9a1712b30ad750-Nhà Sách Mực Tím',
 '6859977cdcea1abe2e05f658-Bách Hóa Xanh',
 '68592110c1b0c4fea3024722-Blue Dream',
 '6857e2fc283acb45060de9e3-Monstera Roastery Coffee',
 '6857a57694d4f594fb04d822-Hutong Hotspot',
 '6856b58368ced4e4ae0dc958-FamilyMart',
 '6856b4f67e991d6aa30929fb-Gà Hầm Thố đá',
 '68568fdf37dffc60fe004cd7-KingCross',
 '685687c12850751427027028-KAI COFFEE K300, Cong Hoa',
 '68566f0dac34588a9e02d4f3-Bách Hóa Xanh',
 '68554663be2053c1fd09b5ba-Xù Food',
 '6854bc9842c79443da07ba6c-BELL CLUB',
 '6853c521f0b657214900ed07-Aeon Mall Long Biên',
 '6853a7c0f0ef27e43b0f13c5-Higland Coffee',
 '6852c0b3fe5899bf6a050073-Năm Ánh',
 '6852af9fdcc037284f0921f8-Demo',
 '68528c6011126a5182070891-Circles Cafe',
 '68527d1d7fe1725eac0cb897-Traffee Tea & Coffee',
 '685242e4b24f9855b204e964-Lotteria Coopmart Cam Ranh',
 '68516e2eab22c7d0db0c0ff5-Trà Sữa Viên Viên',
 '684fdf46b9fb72530d09f3b9-Ấp Cafe ',
 '684fbcdcf1be16dc630d5812-Novo Cafe',
 '684e7f77f34875596c0ef094-LÀ VIỆT COFFEE - PHÓ ĐỨC CHINH',
 '684e4a907e6ef61f8d03a81d-Beanthere Cafe - Hoàng Sa',
 '684e31bbb5ec250bea0fe274-Cầu Đất Showroom',
 '684e2526130191680800d1db-The Casca Coffee',
 '684d2ab487f1ba96330bb9bf-Cafe Phuc Long',
 '684d18880d31ec4c7c0913c6-Phuc Long Coffee & Tea - 352 Võ Văn Ngân',
 '684c3464d40dcf8e6303c39f-Nhà Hàng Hương Cau 2',
 '684ba23363c01bc71309f825-Kingfood',
 '684a6d285caf3ca2f901810a-Teamax',
 '684a4a61c5588ab4e90aded8-POLA COFFEE & TEA',
 '6849665247df3e85fa0cb3e7-Beer Đức Jaderborner',
 '6849542fae03cd62b40f47bf-Cây Cột Điện Coffee Books',
 '6849540dd6f5fd1a9f032fcb-Cây Cột Điện Coffee Books',
 '68494b00dc5d7248d00adaf0-Passio Coffee To Go',
 '68494ae93a4722399e01e3bd-Passio Coffee',
 '6847eafb54a62352700c5b2c-Trà Sữa Thái Lan Songkran',
 '6847e2fcd1ba7916850e6096-Saigon Centre',
 '6847a6b06597efdf5d095b02-HIGHLANDS COFFEE - ĐẠI LỘ BÌNH DƯƠNG',
 '6846e875b9f8d1fee601665a-Meta Cafe',
 '68468c156d2c3f8b00039270-HE Tea & Coffee',
 '68468bd1f6614a4cde0a881b-HE Tea & Coffee',
 '68468a18679da347af0b9823-HE Tea & Coffee',
 '684689fb714b3a51ce07cd04-HE Tea & Coffee',
 '684689af4d4690a18c077cc6-HE Tea & Coffee',
 '684689923cd32ac85704ec59-HE Tea & Coffee',
 '6846896dcc27367f620f2f58-HE Tea & Coffee',
 '684689516a227f160305a329-HE Tea & Coffee',
 '6846890c0cf7b50d490d4734-He Tea & Coffee',
 '68465c3bfb8229b8ab0c8824-Dtel Office',
 '68465a78dd86dd042c0a894e-BlueTechX Office',
 '68443802dae5d17a8c0762ce-Nhi Đồng 315 Và Tiêm Chủng',
 '6843ed7ec67491a4b30fbef0-Hiên Nhà Coffee',
 '6843ed38eb8376415e008eb7-Hiên Nhà',
 '6843ec4e266bb7a40b07761b-Hiên Nhà Coffee',
 '6843cc232e86e5cbcb0d3e62-Hủ Tiếu Ghẹ Muối Ớt Đỏ',
 '6843983ecb9dd8b8df0ba16a-Trường Đại Học Khoa Học Tự Nhiên TP HCM',
 '68430d23bb5138814f0406a8-Tiệm Sa Chuỷ 80s',
 '6842eb82101bca96ac019df5-Lotteria Thường Tín',
 '6842eb718714eb32ee0147c7-Loterria Thường Tín',
 '6842c0c06087b08ee609fc46-Gd',
 '68427bdbd317116bd30e2e27-Saigon Innovation Hub - SIHUB ',
 '6842431977516023f20a5f22-F Coffer',
 '6841b6ffa3675578860183c5-Gon Cake',
 '6841b698752f1f0b2b09f162-Gon Cake',
 '6841b66aec3d8cc7ac0a2fc3-Gôn Cake',
 '6841a2fac07a7554a30fc6a7-Tra Sữa Viên Viên',
 '68413f238e92e677a8062311-Nhà Hàng Đức Dương Palace ',
 '68401e12f664053102030fd3-Hội Trường Trịnh Công Sơn - Trường Đại Học Văn Lang ',
 '68400b987f3f136dd20cc69b-Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI - Diamond Brand Institute)',
 '683eb363e302ccd57307be52-MetaUni',
 '683d98e5296533f6b208d42a-Golden Bakery 2',
 '683d98abde408c11180fcbac-Golden Bakeryvungx',
 '683d6e866c8412d2890a5506-Hongkong Baley ',
 '683c597e4c2ed87da5005283-Kingfoodmart Era Town',
 '683c596679098ab3020d7379-Kingfood Mart Era Town',
 '683c58724e514b86ec0d0506-Ông Chủ Nhỏ',
 '683c544e5b6b821e1608c857-Cà Phê ông Bầu Quận 7',
 '683c4c9d58e39aead4098c92-Vĩnh Phát Dimsum',
 '683bdab0d2df8ae62405966b-Kohaku',
 '683acfc0a8d4f18de1012e12-Bách Gia Tinh Hoa',
 '683ab8a2428268c54306b0d3-BGTH - Vương Gia',
 '683ab87f89174d5d560e8953-BGTH - Trịnh Gia',
 '683ab8549abbd61a8509cf1b-BGTH - Tạ Gia',
 '683ab797e66aa434c50b6414-BGTH - Phan Gia',
 '683ab778c9f032db410d8f21-BGTH - Mai Gia',
 '683ab75ee8e19aced80b5bd0-BGTH - Lý Gia',
 '683ab737ff1b00948b035d7c-BGTH - Hà Gia',
 '683ab6d4f052541029038e2b-BGTH - Đào Gia',
 '683ab6b09a42d108d70c5b56-BGTH - Cao Gia',
 '683ab65f225aa4f5c30ca27b-BGTH - Vân Gia',
 '683ab630f73dbbd1a105f2e7-BGTH - Trương Gia',
 '683ab5dae6ee4af69e050d77-BGTH - Tô Gia',
 '683ab5811bbb06973f0e7db7-BGTH - Ngô Gia',
 '683ab4cef3ddb7e29b0c243e-BGTH - Lưu Gia',
 '683ab49c38752ac8a4068eeb-BGTH - Lê Gia',
 '683ab4816ae159015101025c-BGTH - Hồ Gia',
 '683ab461c3cbe7e57003b0b9-BGTH - Đinh Gia',
 '683ab4042e1683525b0992c0-BGTH - Chử Gia',
 '683ab3e7bbca5ce1cf04d7fc-BGTH - Đặng Gia',
 '683ab3c4406571cb2c0f61cb-BGTH - Từ Gia',
 '683ab20c1533eceeb60cdff0-BGTH - Thiều Gia',
 '683ab1dbc133b842d400c85b-BGTH - Phùng Gia',
 '683ab19a368db808ec080fe6-BGTH - Nguyễn Gia',
 '683ab1664d89f1b25a0ee919-BGTH - Lại Gia',
 '683ab1377e670949b40c8f7c-BGTH - Khúc Gia',
 '683ab1047e670949b40c8ea4-BGTH - Đỗ Gia',
 '683ab0eafcb3f9ea710fdaba-BGTH - Đồng Gia',
 '683ab0c3ae671a5c4609996f-BGTH - Bạch Gia',
 '683ab08a3ed711641e0aff5f-BGTH - Vũ/Võ Gia',
 '683ab06842f49fdf0f03499c-BGTH - Thân Gia',
 '683ab04d42f49fdf0f03491f-BGTH - Trần Gia',
 '683aaff741af7d4acf0459e8-BGTH - Phạm Gia',
 '683aafac885e550f3d0cc0ce-BGTH - Mạc Gia',
 '683aaf1f5907e95a070b4967-BGTH - Lương Gia',
 '683aae402758ad7f730ad1a9-BGTH - Hoàng/Huỳnh Gia',
 '683aae0f9879e5c7d20af2bf-BGTH - Đoàn Gia',
 '683aaddb70b8daaabc0c4e77-BGTH - Dương Gia',
 '683aad712b1523c5e305799f-BGTH - Bùi Gia',
 '683a9e2a10d8f55a2e0cf71a-MINISTOP - 34 LÊ VĂN THỌ',
 '683a9d5d42c52be0e80f3eba-Hoa Yêu Thương Long An',
 '683a9d2e314c74876f096edc-Hoa Yêu Thương Vĩnh Long',
 '683a9caac0dc2f2ca50f82d3-Hoa Yêu Thương Tây Ninh',
 '683a94f550e019acf500c5e5-Hoa Yêu Thương Vũng Tàu',
 '683a94903357d9f4280426b3-Hoa Yêu Thương Nha Trang',
 '683a9450bf701dd0370fc3e7-Hoa Yêu Thương Kiên Giang',
 '683a940d43795cf8ea00becc-Hoa Yêu Thương Biên Hòa Đồng Nai',
 '683a938d5af2ab2958004dfc-Hoa Yêu Thương Bình Dương',
 '683a9323e61414fd5b0348e3-Hoa Yêu Thương Lâm Đồng',
 '683a92d29cbb3ac2450066a2-Hoa Yêu Thương Huế ',
 '683a929d5caf7d9a99030367-Hoa Yêu Thương Đà Nẵng',
 '683a92055ff6c14986051df2-Hoa Yêu Thương Cần Thơ',
 '683a8bc8ed8b40b4220e4456-Hoa Yêu Thương ',
 '683a5d834669ba4d9102c9bd-Xưa & Nay Coffee & Tea',
 '6839d52d954e5860bb00eba5-Otaku Yuki Shop',
 '6839071750d847c8530478a8-Dose Saigon Pearl',
 '68382898a1332cc4610b38cb-KingFood',
 '683807d39821b68b9607e49b-UEH - Cơ Sở Nha Trang',
 '683807907e0d75964c0e332b-UEH - Phân Hiệu Vĩnh Long',
 '6838075a2574da2a6b053f3a-UEH - Cơ Sở N - Nguyễn Văn Linh',
 '683806fc9665d72ec5064bd6-UEH - Cơ Sở V - Võ Thị Sáu',
 '683805d59232cdf210042e36-UEH - Cơ Sở I - Phạm Ngọc Thạch',
 '6838057466fa0b74320a22a6-UEH - Cơ Sở H - Hoàng Diệu',
 "68380539aec73f46440db42c-THREE O'CLOCK – Lữ Gia",
 '683804bccc704fab3c0532f8-UEH - Cơ Sở E - Nguyễn Văn Thủ',
 '6838047f9cdde72aa409f4f9-UEH - Cơ Sở D - Trần Quang Khải',
 '6838042ca053874536076e80-UEH - Cơ Sở C - Đường 3 Tháng 2',
 '683803cb99ffbacda80183bf-UEH - Cơ Sở B - Nguyễn Tri Phương',
 '68380294f32476f9740f34ea-UEH - Cơ Sở A - Nguyễn Đình Chiểu',
 '683730cbd10f15f0b90ce06e-Đen Đá Coffee - Hồng Bàng',
 '6836c03b5b0d72bc2b0360da-Tui Bán Trà - Tiệm Trà Hong Kong',
 '683691c207f78980af030110-Starbucks - Nguyễn Hữu Cảnh',
 '683590b607e774b7b705247d-Ngọc Dung Beauty Cần Thơ',
 '68359081973fbe1c2d0d1e08-Ngọc Dung Beauty Bà Rịa – Vũng Tàu',
 '6835904893314347440071d8-Ngọc Dung Beauty Biên Hòa - Đồng Nai',
 '68358fe57564e46df304ea0c-Ngọc Dung Beauty Bình Dương',
 '68358faeb10ff453e502b7ab-Ngọc Dung Beauty Vinh',
 '68358f7ab325e31e530d92e3-Ngọc Dung Beauty Buôn Mê Thuột',
 '68358f3b71fb8850c40a91a4-Ngọc Dung Beauty Phan Thiết',
 '68358f110437f5403e0419fb-Ngọc Dung Beauty Đà Nẵng',
 '68358ee3b325e31e530d90d7-Ngọc Dung Beauty Nha Trang',
 '68358eac05e71e32a20a8bfe-Ngọc Dung Beauty Hải Phòng',
 '68358e520437f5403e04177d-Ngọc Dung Beauty Quảng Ninh',
 '68358de073ec9b035207341c-Ngọc Dung Beauty Hà Nội 2',
 '68358d9aa18ff20838069eed-Ngọc Dung Beauty Hà Nội 1',
 '68358a41c399ca522d076fe7-Ngọc Dung Beauty Quận 7',
 '683589a54ad4dd91b007255b-Ngọc Dung Beauty Quận 10',
 '6835892fc9dc449f150c02fc-Ngọc Dung Beauty Trụ Sở Chính',
 '683568827fd6d19fb1068525-Spa Ngọc Dung',
 '68351a1cdcfdfede550d0f1e-Volvo Showroom',
 '68350a77accaae5d440f36c9-Kingfood Mart',
 '6834284666fe6673a50df49b-Pharmacity',
 '68341c0cced29368a60ec627-Phúc Long',
 '683321b445832b7eb90a99be-Trà Sữa Gia Truyền',
 '6832f5313d53f5f0b10d52e5-The Cloudest - Swim, Dine & Vibe',
 '6831c455965a04b5330edb85-Panda BBQ',
 '6831b473f3bda9a9e70ea9a4-Sacombank Nam Kỳ Khởi Nghĩa ',
 '683153fc44a0779a2704ed76-Hana BBQ Buffet',
 '683069b5f3affbb7130e0939-Papa Lee’s',
 '6830696d3bd4bf6d0908ab7a-Papa Lee’s',
 '6830006687cea7266d0fa82d-Aeon Long Biên',
 '682d97c712c93146580711d8-Hi Go Go',
 '682d3cc87c1b528fa60c2b3a-VIVA STAR COFFEE - PHÚ MỸ',
 '682d3cb0fd95da17cc064ab7-VIVA STAR COFFEE - CAO LÃNH',
 '682d3c89da5fa1f5ec042f9a-VIVA RESERVE CẦN THƠ',
 '682caeba85df56e8f906611a-Dr Quy Billiards',
 '682c11464cbef54557068c0c-VIVA TO GO - ĐÀO DUY TỪ',
 '682c1131f6eb4e0a980b01e5-VIVA TO GO KINGDOM - ĐƯỜNG D1',
 '682c111d30fb581b350371a9-VIVA TO GO - LÊ TRUNG NGHĨA',
 '682c110954893ffb910ef64a-VIVA TO GO - XUÂN THUỶ',
 '682c10f430fb581b350370e2-VIVA TO GO - ƯU LONG',
 '682c10db54893ffb910ef548-VIVA STAR - HOÀ BÌNH',
 '682c1082415586f1bf0f7e5b-VIVA STAR - 345/15 LÝ THƯỜNG KIỆT',
 '682c106ac51523e9ea0ad945-VIVA STAR ĐÔNG HỒ',
 '682c0fea252933c3930d13b6-VIVA STAR COFFEE HƯƠNG LỘ 2',
 '682c0fcc7477f8c68f02a7a4-VIVA STAR COFFEE VƯỜN LÀI',
 '682c0fabf4d6d856070c2a62-VIVA STAR COFFEE NGUYỄN TRỌNG TUYỂN',
 '682c0f8fda8526c85a0ef392-VIVA STAR COFFEE 84 THÀNH THÁI',
 '682c0f71800b47ebd0002f7c-VIVA STAR COFFEE LÊ HỒNG PHONG',
 '682c0f43ecbcb9773e001996-Viva Star Coffee Đất Thánh',
 '682c0f18f4d6d856070c2829-VIVA STAR COFFEE TRẦN VĂN KHÉO',
 '682c0edcecbcb9773e00178f-Viva Star 53 Thành Thái',
 '682c0e96f8200fbdbc03bfb1-VIVA STAR BÀ HẠT',
 '682c0ce100f26a33b5053065-Viva Star Bà Hạt',
 '682c041d5d5a176a200f1bf2-MINISTOP - 120 VÕ THÀNH TRANG',
 '682aecf83d85fc346e02e9dc-Poc Poc',
 '6829d829e84282d11d0a191c-Yody Lê Văn Việt',
 '6829cd2b1c3f9e2e2605bc10-Vincom Giga Mall',
 '682975d69bc96de781087908-Quán Cơm Đào',
 '6827720ad74361e40b0e37ab-Rạp đống đa',
 '6826e9d4a635e3790f0841a1-Nhà Hàng Chay Bà Xã ',
 '6825b7e6b95fff4d9b0957da-MINISTOP - 96 CAO THẮNG',
 '68247178fb9a1d78bf0c9b05-Comeco',
 '6823ffba8c01563214062831-Viva Star Coffee Khuông Việt ',
 '682318fd06887236c108866b-TTTM GO THÁI BÌNH ',
 '68203c4fe4863eb7dd0881f5-South Ground',
 '68202e45528cef8fb10ff619-Vidimi Demo',
 '681f5f8a2d9648eb0f048ba9-Công Ty TNHH May Thêu Giày An Phước',
 '681f5e36d5d864bbf2019c65-Fast Feel',
 '681cd9c7745ec99bd80d7617-F5 Test Business',
 '681b7b7235698a57d40fc93d-Mỳ Cay Seoul',
 '6819c8b5be7ba880e102c720-Trung',
 '6819c6abc6cca0c30e03d72e-Trung',
 '68199cc635289ef8f30c5c1c-Tommy Shop',

In [ ]:
def chunk_list(data, chunk_size):
    """Chia list thành các chunk có kích thước chunk_size"""
    for i in range(0, len(data), chunk_size):
        yield data[i:i + chunk_size]

In [ ]:
# Người dùng nhập số lượng phần tử trong mỗi chunk
chunk_size = int(input("Nhập số lượng phần tử mỗi chunk: "))
formatted_data_chunks = list(chunk_list(result, chunk_size))

Nhập số lượng phần tử mỗi chunk: 70

In [ ]:
# In kết quả
for idx, c in enumerate(formatted_data_chunks, 1):
        print(f"Chunk {idx}: {c}")

Chunk 1: ['68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi', '68d2db50ea440018b406378d-Lotte Cinema Gò Vấp', '68d2da3aa5272c273c0d4ec2-Dabaco Cinema Quế Võ', '68d2d9e2277ef09e45011bcc-Rạp Chiếu Phim Beta Thanh Hóa', '68d2c6e5946e8664910eb20d-Liberty Centre Point', '68d2bd489536bef0610f07ec-MUJI', '68d2820411e9c8fc800cabc6-Piccolo Coffee 36A Kỳ Đồng', '68d182be90af06000c00ec7e-Rau Má Mix', '68cffc5774460d688509885d-Hệ Thống Sửa Laptop - Macbook', '68cf612c4abd09b9ac0841f5-Start Coffee', '68cd2fc29a19853b4c04449f-Hasaki', '68cbf86fb8fcf295eb0c3f93-FUKATSU', '68ca5a8b5d2f4e819f0eb3fd-    ', '68ca2ba4ba74969dfe02d803-Hhh', '68ca2b42ba74969dfe02d764-Absabs', '68ca2b0f0d2d981b75013f82-     ', '68c6cc0d147524863503cd1c-Một Góc Hà Nội - 243/1 Tô Hiến Thành', '68c6c3e158b6baba290ee9fe-Naan & Masala', '68c5383f5c960e35620353c8-Lol', '68c536c34f0804d6a90b609e-Chưa có ', '68c536b66510354e5a020556-     ', '68c38ca8489f5f39fe0f509d-Jiangnam', '68c3839d9b95188c1d0fc005-Léhem Cafe', '68c29955d54529257a07d0d9-Vi Tính Thủ đức', '68c298a7869f7f2fd500109f-Nhà Sách Book Plaza', '68c2341eaf9aaaa0f60b78cb-Circle K - 105 Lê Trọng Tấn', '68c185348535c6282e0b41a6-Trà Sữa Phi Phi', '68bebeb4fda51f613e077dee-Gia Lam Sport', '68be3d703488457daa0096c4-CA TP HCM', '68bd877ed81c38f0c507fe93-Matsuya Phan Văn Trị', '68bc376217b3f3043e0481de-Z88 Phúc Hải', '68bc36090c49c85d9c0fa893-Sớm Khuya', '68bbdc81e97cd061ae0a40ee-24/24 Coffee D5', '68bbb114d5bc2ab0b503af21-LUX COFFEE - ĐẮK LẮK', '68bbb085fd0e93c1020bc56d-30Shine', '68b6693a1f97c15acd035a9a-Gà Tươi Mạnh Hoạch ', '68b5482c22ab44a0900f95fb-Bánh Canh Long Hương - Thúy', '68b45fefeffcea1bbb0b3d5a-Nhà Sách FAHASA Tiền Giang', '68b4540f91e7c24ed1038f37-Mr.Tôm Sushi', '68b3afd2c5755fae5a0dc01d-Karaoke Nốt Nhạc Vui Lê Văn Sỹ', '68b3397450fc16960409d117-Apple Store Online', '68b15d8a5b94ac50350fe761-GAIGARDEN', '68b061655c48502cf203035f-The Wish Coffee', '68af042bb55dccca9a089da3-Fahasa Vincom Quận 9', '68af029589bde9ccb601f1a4-Divine Shop', '68af01cdbefad4c5620da10f-Vựa Gym', '68aef8e3013b2d322a0a9d74-NS Biên Hòa', '68aed236b721098524042aae-Texas Chicken - Nguyễn Văn Cừ', '68aec39769d9b749810fb332-CSID', '68aea42c482ad27da40bf7b8-TMART', '68aea246281c2d9cad0787b0-PĐM MART', '68ae78d0f322d39afb019311-The Art Tea Lounge', '68adce41cd479cca410d3f52-LA FEE Tea & Coffee', '68adc32a6e93ef6a570e6f06-Trà Sữa Viên Viên', '68ad9473032a348e040d829f-Highlands', '68ac636545e4efb527006773-Co.opmart Bình Tân', '68aae512f38459b5d000635e-Co.opmart Nhiêu Lộc', '68aac2f18e52a7d6b30d77f2-Tâm Tâm Vegetarian Restaurant', '68aabbf17ed4ac8531050a9c-Bách Hóa Xanh', '68aa9b842e6779cffc04a301-Z88', '68aa8ef321cf66075a0b47ff-Nhà Sách Biên Hòa', '68a947b309cce1bfe305e0b6-Bách Hóa Xanh', '68a912f13b8633e8ba03df75-QandA', '68a81977187eb5dcf9033522-Thái Yên Coffee', '68a6f6fd9b8ec943c20a9d14-Kingfood ', '68a69c649c8aed49e00b9e5f-Highand Coffe', '68a5eba8517b8ec71a04d122-Lục Trà Thăng Hoa ', '68a5e9c8207942c5ee06076c-Lục Trà Thăng Hoa', '68a5e984e555046b4909badc-Lục Trà Thăng Hoa ', '68a5e95ee555046b4909b9bb-Lục Trà Thăng Hoa']
Chunk 2: ['68a5a5688dfb7650550fa587-Shopee', '68a53fbe218916ea4000bf9d-Decathlon', '68a4163f7eaa63978b03a0af-Pharmacity Dương Thị Mười', '68a2f141222988aa050a4c78-Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép', '68a2e43bb14ec0d93400e6c3-Tiệm Nước Túi Bình Yên', '68a2d379d507f6d01a07ef36-Công Ty CP MetaUni', '68a2b45fcca87d0dc70119ce-SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM', '68a2895496a22ee1fc01dea8-HT CLB Doanh Nông', '68a14d0113735dda4707dbd6-Thegioixedapvt', '68a0b729f40057460600b7d8-MIXUE - NGUYỄN ẢNH THỦ', '689fe74254f229df2a0b3f6f-BHX', '689ee7916a484917e101fd14-Sync Coffee', '689ee19dc0ce6590c80fb6cd-Trường Đại Học Nguyễn Tất Thành', '689c29bdff2ba94f4703eb02-Nhà Hàng Chay Làng Ta', '689c0bb1f905e9bb170a2836-Guardian Bình Thới', '689c09d8c8d146721d0b6381-Cơm Niêu Bình Dân', '689b361188bc117512014afa-Sun Pet', '689b1edc01fe904a55071952-Tmart ', '689b16747ee34bb055007504-Trà/Bánh Tráng', '689acdefe21c7d9a6d0ea950-Haseyo Nguyễn Gia Trí', '689ac37f0223b5babc008ba4-GS25 - 511 HUỲNH VĂN BÁNH', '689a149f102266797901c9ea-Lục Trà Thăng Hoa  - Hoàng Diệu 2', '6899f39d01406402130c8d5f-Góc Của Tùng', '689747c4f1be0790590284c2-Cơm Ngon Đà Lạt', '689704cfaecef7e7bc0746ab-Warning Zone Nguyễn Văn Trỗi', '6896e8f215f7da2bf306c2a4-Quán Ăn Gia Đình Fresh', '6896cd885dc3e0f8d70dd9c4-Better Food Corner', '6896a709c0090dae09058df1-Better Food Corner CN1', '6895c98faaf5cb641503bd60-Better Food Corner CN2', '68958dfad0655801020bdfbe-Cơm Bắc Lan Hương', '689576222ee57988a6005b04-Không Gian Khởi Nghiệp Phú Nhuận', '68948dc152ace8706c011bf7-Tao Ngộ - Lẩu Gà Lá É Gà Đồi Tây Nguyên', '68936b853f6abc21c70cf2d8-Pharmacity', '68933578858144b97b0812cd-FamilyMart', '6892ce59d23883624309b4d6-Trà Sữa Phi Phi', '68921aa71a08a3b6e80e8fc6-Mì Cay Sasin - Bình Trị Đông B', '68915d8e77d83af8bd09302a-Pharmacity', '688f6d970627912011054936-Yori ', '688e19094738cbc72b0f41f3-HIFA', '688e18367b781467610280de-Circle K - 13 Tôn Đản', '688dd3b09fb4fc028b0f2110-Hej Matcha', '688c9f05d00b11a97f00a1dd-HAN Tea', '688b0ff74b2e0895c30e25fe-GUTA CAFE - 549 Điện Biên Phủ', '688af23589caa594190d86a7-Cơm Gà Giòn Giòn', '688a6cf86ecf05b30f03f542-Trà Sữa Thăng Hoa - Hoàng Diệu 2', '6889b9942bc907204a05089f-Mixue', '6889b3a5c63504ad350dd1c1-Another Space', '68898b6f61cb9fbfcd0201e6-Thành Coffee', '6888ce043b47ff0f6d06ea0d-Casio HCM', '68873fef243409325703d595-MV Food & Drink', '6887105d9b76753f950b2694-Mr.Eco Salad Healthy', '688601b4d4a8c0fa3f0afc83-Pizza Có Tâm', '68820fa5413cb1dfa002207d-Nhà Của Thời Thanh Xuân', "687e4b4c832afb99c901e42a-Lyn's Chicken", '687e2dfc4b84bd27d602f671-Cháo Ếch Singapo', '687cc4bdb60896ca2c08d90a-Phamacity', '687ca27b95cc713e1a069c68-HIGHLANDS - LÝ CHÍNH THẮNG', '687b3ca60cd23608eb01ba92-BÁCH HOÁ XANH - 234 HOÀNG HOA THÁM', '687b1b445757ebed1e0a01d0-HIGHLANDS COFFEE - ĐỨC TRỌNG', '6878f4accc12d6e77f0d6651-Famarcity ', '6878f490cc12d6e77f0d662b-Famarcity ', '6878e499e131880aae086f21-Lục Coffee & Tea', '6878df6989e0b7a3980dc8ef-Mì Quảng Ăn Là Nhớ', '6878c7f1d08042df55085a61-My Cafe', '6877c23d2cc7b484f205a688-Hằng Lê Trà Sữa ', '6877973dfa0fc330f0058328-Lẩu Cá Kèo Chị Tôi', '687771fc4f2307d1780564e9-Sowee Space', '68767a43d15605ecd00ac765-MINISTOP -  87 VẠN KIẾP', '68762acf6328af071207bf4d-Khách Sạn Sân Vườn Hà Giang 2', '6874f4fcd47d97f2de00aaaa-Cộng đồng Design Thinking - Techfest VN']
Chunk 3: ['687330ef00ec32366706bb39-Thè M Cafe', '6873238908538e0e540d09cf-Coop Mart', '687305620fa540ae4203d4f1-Cafe Amazon', '686f7986d0071401cd047f22-Demo', '686f656be89127d1230221d9-CO', '686f52955ef920311b05dc29-Cá Ơi Làng Chài', '686dff07f262f568fc06df4d-Jollibee Vạn Hạnh Mall', '686dfee887f39ff57c0ed64f-Jollibee Vạn Hạnh Mall', '686dc9441dfb73a7e70dc5e8-HIGHLANDS COFFEE - PHẠM VĂN ĐỒNG', '686cd280c43efc0888069b30-Xịn House Design ', '686c9afb6384edb1be0d4351-Xịn House Design ', '686c92bdae2402127603c856-Xịn House Design ', '686b4a51d8831e60f80b6437-HIGHLANDS COFFEE - VINWONDERS', '686b3ec2a3f83eacd90b53f2-Vị Cà Phê', '686a38523d153c07720483b2-BÁCH HOÁ XANH - 173 BÙI ĐÌNH TUÝ', '686a35b7ffca6b6b4f0a2263-Mangrove', '6869426f5095b2086e0ddbd8-Pharmacity', '68692c07d7593087810221f6-Ăn Vặt 148', '6868d73bb2cb722fb00b5058-CLB ROPOLY', '6866119d9ff61d515d01a29b-Tiệm Cà Phê Xứ Nam Kỳ', '68654ef63375be60d904d2ff-Pharnacity', '68649b159aa2165a0d05352b-Cafe 24/24', '68648987c26933c0d2008f7d-Circle K - 106 Hoàng Diệu', '6863b544c9eb3c10b60f75ab-Fuji Mart Tân Mai', '68629331580df7b7c5065536-Starbuck - Quang Trung', '68629274e63af9122503659a-Sun Pet', '6862905fe24909a5f707a408-Lẩu Gật Gù', '68627d93cf0eeeb8720397cb-KYO WATAMI Grill & Sushi', '686233b641b885e5b30a656c-Phát Đạt Dental', '68614cdd498b547dc706b370-7 Map', '686135f6c940db29c801aabf-Lẩu Cá Mang Về 69k', '6860e8a5767a67702e052dfe-Xịn House', '685ff5fd01db61a6560451c1-Lẩu Phong Vị 24H', '685ff595fee372bf2c0cd43d-Lẩu Phong Vị 24H', '685f8161f1d049f2360bf326-COCÉVI Coffee And Chill', '685e724a672f1fc415008b3d-B-S Mart', '685e0cd4358056f736072355-COCÉVI Coffee And Chill', '685d2ec992503ebd140a9ed3-Circle K - D5', '685cd2f4d635521ddf09d881-Haga', '685cd2b5d635521ddf09d81c-Anc', '685cd15deb90e320be003d1d-Trà Sữa Shiney', '685cd09dc93ab13cda012bad-Trà Sữa Shiney', '685c09859a93e297e30be332-Tacos Labubu', '685bd92db1a548fad10bedd7-Takashimaya', '685bd725b49528302c0b873b-Cây Đầu To', '685bd71aff05da42680b6bf6-Cây Đầu To', '685bc3f06c348405ef03dd5c-Cà Rề Cafe', '685aad92653f27aea70bea19-Vinamilk', '685a9f1844d2b42c1f09686c-Yolo BBQ', '685a926eaeba1bed9f0383a4-Metro Khu Công Nghệ Cao', '685a74557a005a2c150d0141-Street Coffee ', '685a62b5d19a80e1e109a02b-HIGHLANDS COFFEE - MENAS MALL', '685a622ca63f105b680ac5dd-HIGHLANDS COFFEE - MENAS MALL', '685a36d28bbba8fd49008bb8-Metro Bến Thành', '685a2ee244b9eb49bc0ba6ac-Kim Đô', '6859f1053a9a1712b30ad750-Nhà Sách Mực Tím', '6859977cdcea1abe2e05f658-Bách Hóa Xanh', '68592110c1b0c4fea3024722-Blue Dream', '6857e2fc283acb45060de9e3-Monstera Roastery Coffee', '6857a57694d4f594fb04d822-Hutong Hotspot', '6856b58368ced4e4ae0dc958-FamilyMart', '6856b4f67e991d6aa30929fb-Gà Hầm Thố đá', '68568fdf37dffc60fe004cd7-KingCross', '685687c12850751427027028-KAI COFFEE K300, Cong Hoa', '68566f0dac34588a9e02d4f3-Bách Hóa Xanh', '68554663be2053c1fd09b5ba-Xù Food', '6854bc9842c79443da07ba6c-BELL CLUB', '6853c521f0b657214900ed07-Aeon Mall Long Biên', '6853a7c0f0ef27e43b0f13c5-Higland Coffee', '6852c0b3fe5899bf6a050073-Năm Ánh']
Chunk 4: ['6852af9fdcc037284f0921f8-Demo', '68528c6011126a5182070891-Circles Cafe', '68527d1d7fe1725eac0cb897-Traffee Tea & Coffee', '685242e4b24f9855b204e964-Lotteria Coopmart Cam Ranh', '68516e2eab22c7d0db0c0ff5-Trà Sữa Viên Viên', '684fdf46b9fb72530d09f3b9-Ấp Cafe ', '684fbcdcf1be16dc630d5812-Novo Cafe', '684e7f77f34875596c0ef094-LÀ VIỆT COFFEE - PHÓ ĐỨC CHINH', '684e4a907e6ef61f8d03a81d-Beanthere Cafe - Hoàng Sa', '684e31bbb5ec250bea0fe274-Cầu Đất Showroom', '684e2526130191680800d1db-The Casca Coffee', '684d2ab487f1ba96330bb9bf-Cafe Phuc Long', '684d18880d31ec4c7c0913c6-Phuc Long Coffee & Tea - 352 Võ Văn Ngân', '684c3464d40dcf8e6303c39f-Nhà Hàng Hương Cau 2', '684ba23363c01bc71309f825-Kingfood', '684a6d285caf3ca2f901810a-Teamax', '684a4a61c5588ab4e90aded8-POLA COFFEE & TEA', '6849665247df3e85fa0cb3e7-Beer Đức Jaderborner', '6849542fae03cd62b40f47bf-Cây Cột Điện Coffee Books', '6849540dd6f5fd1a9f032fcb-Cây Cột Điện Coffee Books', '68494b00dc5d7248d00adaf0-Passio Coffee To Go', '68494ae93a4722399e01e3bd-Passio Coffee', '6847eafb54a62352700c5b2c-Trà Sữa Thái Lan Songkran', '6847e2fcd1ba7916850e6096-Saigon Centre', '6847a6b06597efdf5d095b02-HIGHLANDS COFFEE - ĐẠI LỘ BÌNH DƯƠNG', '6846e875b9f8d1fee601665a-Meta Cafe', '68468c156d2c3f8b00039270-HE Tea & Coffee', '68468bd1f6614a4cde0a881b-HE Tea & Coffee', '68468a18679da347af0b9823-HE Tea & Coffee', '684689fb714b3a51ce07cd04-HE Tea & Coffee', '684689af4d4690a18c077cc6-HE Tea & Coffee', '684689923cd32ac85704ec59-HE Tea & Coffee', '6846896dcc27367f620f2f58-HE Tea & Coffee', '684689516a227f160305a329-HE Tea & Coffee', '6846890c0cf7b50d490d4734-He Tea & Coffee', '68465c3bfb8229b8ab0c8824-Dtel Office', '68465a78dd86dd042c0a894e-BlueTechX Office', '68443802dae5d17a8c0762ce-Nhi Đồng 315 Và Tiêm Chủng', '6843ed7ec67491a4b30fbef0-Hiên Nhà Coffee', '6843ed38eb8376415e008eb7-Hiên Nhà', '6843ec4e266bb7a40b07761b-Hiên Nhà Coffee', '6843cc232e86e5cbcb0d3e62-Hủ Tiếu Ghẹ Muối Ớt Đỏ', '6843983ecb9dd8b8df0ba16a-Trường Đại Học Khoa Học Tự Nhiên TP HCM', '68430d23bb5138814f0406a8-Tiệm Sa Chuỷ 80s', '6842eb82101bca96ac019df5-Lotteria Thường Tín', '6842eb718714eb32ee0147c7-Loterria Thường Tín', '6842c0c06087b08ee609fc46-Gd', '68427bdbd317116bd30e2e27-Saigon Innovation Hub - SIHUB ', '6842431977516023f20a5f22-F Coffer', '6841b6ffa3675578860183c5-Gon Cake', '6841b698752f1f0b2b09f162-Gon Cake', '6841b66aec3d8cc7ac0a2fc3-Gôn Cake', '6841a2fac07a7554a30fc6a7-Tra Sữa Viên Viên', '68413f238e92e677a8062311-Nhà Hàng Đức Dương Palace ', '68401e12f664053102030fd3-Hội Trường Trịnh Công Sơn - Trường Đại Học Văn Lang ', '68400b987f3f136dd20cc69b-Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI - Diamond Brand Institute)', '683eb363e302ccd57307be52-MetaUni', '683d98e5296533f6b208d42a-Golden Bakery 2', '683d98abde408c11180fcbac-Golden Bakeryvungx', '683d6e866c8412d2890a5506-Hongkong Baley ', '683c597e4c2ed87da5005283-Kingfoodmart Era Town', '683c596679098ab3020d7379-Kingfood Mart Era Town', '683c58724e514b86ec0d0506-Ông Chủ Nhỏ', '683c544e5b6b821e1608c857-Cà Phê ông Bầu Quận 7', '683c4c9d58e39aead4098c92-Vĩnh Phát Dimsum', '683bdab0d2df8ae62405966b-Kohaku', '683acfc0a8d4f18de1012e12-Bách Gia Tinh Hoa', '683ab8a2428268c54306b0d3-BGTH - Vương Gia', '683ab87f89174d5d560e8953-BGTH - Trịnh Gia', '683ab8549abbd61a8509cf1b-BGTH - Tạ Gia']
Chunk 5: ['683ab797e66aa434c50b6414-BGTH - Phan Gia', '683ab778c9f032db410d8f21-BGTH - Mai Gia', '683ab75ee8e19aced80b5bd0-BGTH - Lý Gia', '683ab737ff1b00948b035d7c-BGTH - Hà Gia', '683ab6d4f052541029038e2b-BGTH - Đào Gia', '683ab6b09a42d108d70c5b56-BGTH - Cao Gia', '683ab65f225aa4f5c30ca27b-BGTH - Vân Gia', '683ab630f73dbbd1a105f2e7-BGTH - Trương Gia', '683ab5dae6ee4af69e050d77-BGTH - Tô Gia', '683ab5811bbb06973f0e7db7-BGTH - Ngô Gia', '683ab4cef3ddb7e29b0c243e-BGTH - Lưu Gia', '683ab49c38752ac8a4068eeb-BGTH - Lê Gia', '683ab4816ae159015101025c-BGTH - Hồ Gia', '683ab461c3cbe7e57003b0b9-BGTH - Đinh Gia', '683ab4042e1683525b0992c0-BGTH - Chử Gia', '683ab3e7bbca5ce1cf04d7fc-BGTH - Đặng Gia', '683ab3c4406571cb2c0f61cb-BGTH - Từ Gia', '683ab20c1533eceeb60cdff0-BGTH - Thiều Gia', '683ab1dbc133b842d400c85b-BGTH - Phùng Gia', '683ab19a368db808ec080fe6-BGTH - Nguyễn Gia', '683ab1664d89f1b25a0ee919-BGTH - Lại Gia', '683ab1377e670949b40c8f7c-BGTH - Khúc Gia', '683ab1047e670949b40c8ea4-BGTH - Đỗ Gia', '683ab0eafcb3f9ea710fdaba-BGTH - Đồng Gia', '683ab0c3ae671a5c4609996f-BGTH - Bạch Gia', '683ab08a3ed711641e0aff5f-BGTH - Vũ/Võ Gia', '683ab06842f49fdf0f03499c-BGTH - Thân Gia', '683ab04d42f49fdf0f03491f-BGTH - Trần Gia', '683aaff741af7d4acf0459e8-BGTH - Phạm Gia', '683aafac885e550f3d0cc0ce-BGTH - Mạc Gia', '683aaf1f5907e95a070b4967-BGTH - Lương Gia', '683aae402758ad7f730ad1a9-BGTH - Hoàng/Huỳnh Gia', '683aae0f9879e5c7d20af2bf-BGTH - Đoàn Gia', '683aaddb70b8daaabc0c4e77-BGTH - Dương Gia', '683aad712b1523c5e305799f-BGTH - Bùi Gia', '683a9e2a10d8f55a2e0cf71a-MINISTOP - 34 LÊ VĂN THỌ', '683a9d5d42c52be0e80f3eba-Hoa Yêu Thương Long An', '683a9d2e314c74876f096edc-Hoa Yêu Thương Vĩnh Long', '683a9caac0dc2f2ca50f82d3-Hoa Yêu Thương Tây Ninh', '683a94f550e019acf500c5e5-Hoa Yêu Thương Vũng Tàu', '683a94903357d9f4280426b3-Hoa Yêu Thương Nha Trang', '683a9450bf701dd0370fc3e7-Hoa Yêu Thương Kiên Giang', '683a940d43795cf8ea00becc-Hoa Yêu Thương Biên Hòa Đồng Nai', '683a938d5af2ab2958004dfc-Hoa Yêu Thương Bình Dương', '683a9323e61414fd5b0348e3-Hoa Yêu Thương Lâm Đồng', '683a92d29cbb3ac2450066a2-Hoa Yêu Thương Huế ', '683a929d5caf7d9a99030367-Hoa Yêu Thương Đà Nẵng', '683a92055ff6c14986051df2-Hoa Yêu Thương Cần Thơ', '683a8bc8ed8b40b4220e4456-Hoa Yêu Thương ', '683a5d834669ba4d9102c9bd-Xưa & Nay Coffee & Tea', '6839d52d954e5860bb00eba5-Otaku Yuki Shop', '6839071750d847c8530478a8-Dose Saigon Pearl', '68382898a1332cc4610b38cb-KingFood', '683807d39821b68b9607e49b-UEH - Cơ Sở Nha Trang', '683807907e0d75964c0e332b-UEH - Phân Hiệu Vĩnh Long', '6838075a2574da2a6b053f3a-UEH - Cơ Sở N - Nguyễn Văn Linh', '683806fc9665d72ec5064bd6-UEH - Cơ Sở V - Võ Thị Sáu', '683805d59232cdf210042e36-UEH - Cơ Sở I - Phạm Ngọc Thạch', '6838057466fa0b74320a22a6-UEH - Cơ Sở H - Hoàng Diệu', "68380539aec73f46440db42c-THREE O'CLOCK – Lữ Gia", '683804bccc704fab3c0532f8-UEH - Cơ Sở E - Nguyễn Văn Thủ', '6838047f9cdde72aa409f4f9-UEH - Cơ Sở D - Trần Quang Khải', '6838042ca053874536076e80-UEH - Cơ Sở C - Đường 3 Tháng 2', '683803cb99ffbacda80183bf-UEH - Cơ Sở B - Nguyễn Tri Phương', '68380294f32476f9740f34ea-UEH - Cơ Sở A - Nguyễn Đình Chiểu', '683730cbd10f15f0b90ce06e-Đen Đá Coffee - Hồng Bàng', '6836c03b5b0d72bc2b0360da-Tui Bán Trà - Tiệm Trà Hong Kong', '683691c207f78980af030110-Starbucks - Nguyễn Hữu Cảnh', '683590b607e774b7b705247d-Ngọc Dung Beauty Cần Thơ', '68359081973fbe1c2d0d1e08-Ngọc Dung Beauty Bà Rịa – Vũng Tàu']
Chunk 6: ['6835904893314347440071d8-Ngọc Dung Beauty Biên Hòa - Đồng Nai', '68358fe57564e46df304ea0c-Ngọc Dung Beauty Bình Dương', '68358faeb10ff453e502b7ab-Ngọc Dung Beauty Vinh', '68358f7ab325e31e530d92e3-Ngọc Dung Beauty Buôn Mê Thuột', '68358f3b71fb8850c40a91a4-Ngọc Dung Beauty Phan Thiết', '68358f110437f5403e0419fb-Ngọc Dung Beauty Đà Nẵng', '68358ee3b325e31e530d90d7-Ngọc Dung Beauty Nha Trang', '68358eac05e71e32a20a8bfe-Ngọc Dung Beauty Hải Phòng', '68358e520437f5403e04177d-Ngọc Dung Beauty Quảng Ninh', '68358de073ec9b035207341c-Ngọc Dung Beauty Hà Nội 2', '68358d9aa18ff20838069eed-Ngọc Dung Beauty Hà Nội 1', '68358a41c399ca522d076fe7-Ngọc Dung Beauty Quận 7', '683589a54ad4dd91b007255b-Ngọc Dung Beauty Quận 10', '6835892fc9dc449f150c02fc-Ngọc Dung Beauty Trụ Sở Chính', '683568827fd6d19fb1068525-Spa Ngọc Dung', '68351a1cdcfdfede550d0f1e-Volvo Showroom', '68350a77accaae5d440f36c9-Kingfood Mart', '6834284666fe6673a50df49b-Pharmacity', '68341c0cced29368a60ec627-Phúc Long', '683321b445832b7eb90a99be-Trà Sữa Gia Truyền', '6832f5313d53f5f0b10d52e5-The Cloudest - Swim, Dine & Vibe', '6831c455965a04b5330edb85-Panda BBQ', '6831b473f3bda9a9e70ea9a4-Sacombank Nam Kỳ Khởi Nghĩa ', '683153fc44a0779a2704ed76-Hana BBQ Buffet', '683069b5f3affbb7130e0939-Papa Lee’s', '6830696d3bd4bf6d0908ab7a-Papa Lee’s', '6830006687cea7266d0fa82d-Aeon Long Biên', '682d97c712c93146580711d8-Hi Go Go', '682d3cc87c1b528fa60c2b3a-VIVA STAR COFFEE - PHÚ MỸ', '682d3cb0fd95da17cc064ab7-VIVA STAR COFFEE - CAO LÃNH', '682d3c89da5fa1f5ec042f9a-VIVA RESERVE CẦN THƠ', '682caeba85df56e8f906611a-Dr Quy Billiards', '682c11464cbef54557068c0c-VIVA TO GO - ĐÀO DUY TỪ', '682c1131f6eb4e0a980b01e5-VIVA TO GO KINGDOM - ĐƯỜNG D1', '682c111d30fb581b350371a9-VIVA TO GO - LÊ TRUNG NGHĨA', '682c110954893ffb910ef64a-VIVA TO GO - XUÂN THUỶ', '682c10f430fb581b350370e2-VIVA TO GO - ƯU LONG', '682c10db54893ffb910ef548-VIVA STAR - HOÀ BÌNH', '682c1082415586f1bf0f7e5b-VIVA STAR - 345/15 LÝ THƯỜNG KIỆT', '682c106ac51523e9ea0ad945-VIVA STAR ĐÔNG HỒ', '682c0fea252933c3930d13b6-VIVA STAR COFFEE HƯƠNG LỘ 2', '682c0fcc7477f8c68f02a7a4-VIVA STAR COFFEE VƯỜN LÀI', '682c0fabf4d6d856070c2a62-VIVA STAR COFFEE NGUYỄN TRỌNG TUYỂN', '682c0f8fda8526c85a0ef392-VIVA STAR COFFEE 84 THÀNH THÁI', '682c0f71800b47ebd0002f7c-VIVA STAR COFFEE LÊ HỒNG PHONG', '682c0f43ecbcb9773e001996-Viva Star Coffee Đất Thánh', '682c0f18f4d6d856070c2829-VIVA STAR COFFEE TRẦN VĂN KHÉO', '682c0edcecbcb9773e00178f-Viva Star 53 Thành Thái', '682c0e96f8200fbdbc03bfb1-VIVA STAR BÀ HẠT', '682c0ce100f26a33b5053065-Viva Star Bà Hạt', '682c041d5d5a176a200f1bf2-MINISTOP - 120 VÕ THÀNH TRANG', '682aecf83d85fc346e02e9dc-Poc Poc', '6829d829e84282d11d0a191c-Yody Lê Văn Việt', '6829cd2b1c3f9e2e2605bc10-Vincom Giga Mall', '682975d69bc96de781087908-Quán Cơm Đào', '6827720ad74361e40b0e37ab-Rạp đống đa', '6826e9d4a635e3790f0841a1-Nhà Hàng Chay Bà Xã ', '6825b7e6b95fff4d9b0957da-MINISTOP - 96 CAO THẮNG', '68247178fb9a1d78bf0c9b05-Comeco', '6823ffba8c01563214062831-Viva Star Coffee Khuông Việt ', '682318fd06887236c108866b-TTTM GO THÁI BÌNH ', '68203c4fe4863eb7dd0881f5-South Ground', '68202e45528cef8fb10ff619-Vidimi Demo', '681f5f8a2d9648eb0f048ba9-Công Ty TNHH May Thêu Giày An Phước', '681f5e36d5d864bbf2019c65-Fast Feel', '681cd9c7745ec99bd80d7617-F5 Test Business', '681b7b7235698a57d40fc93d-Mỳ Cay Seoul', '6819c8b5be7ba880e102c720-Trung', '6819c6abc6cca0c30e03d72e-Trung', '68199cc635289ef8f30c5c1c-Tommy Shop']

In [ ]:
formatted_data_chunks[0]

['68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi',
 '68d2db50ea440018b406378d-Lotte Cinema Gò Vấp',
 '68d2da3aa5272c273c0d4ec2-Dabaco Cinema Quế Võ',
 '68d2d9e2277ef09e45011bcc-Rạp Chiếu Phim Beta Thanh Hóa',
 '68d2c6e5946e8664910eb20d-Liberty Centre Point',
 '68d2bd489536bef0610f07ec-MUJI',
 '68d2820411e9c8fc800cabc6-Piccolo Coffee 36A Kỳ Đồng',
 '68d182be90af06000c00ec7e-Rau Má Mix',
 '68cffc5774460d688509885d-Hệ Thống Sửa Laptop - Macbook',
 '68cf612c4abd09b9ac0841f5-Start Coffee',
 '68cd2fc29a19853b4c04449f-Hasaki',
 '68cbf86fb8fcf295eb0c3f93-FUKATSU',
 '68ca5a8b5d2f4e819f0eb3fd-    ',
 '68ca2ba4ba74969dfe02d803-Hhh',
 '68ca2b42ba74969dfe02d764-Absabs',
 '68ca2b0f0d2d981b75013f82-     ',
 '68c6cc0d147524863503cd1c-Một Góc Hà Nội - 243/1 Tô Hiến Thành',
 '68c6c3e158b6baba290ee9fe-Naan & Masala',
 '68c5383f5c960e35620353c8-Lol',
 '68c536c34f0804d6a90b609e-Chưa có ',
 '68c536b66510354e5a020556-     ',
 '68c38ca8489f5f39fe0f509d-Jiangnam',
 '68c3839d9b95188c1d0fc005-Léhem Cafe',
 '68c29955d54529257a07d0d9-Vi Tính Thủ đức',
 '68c298a7869f7f2fd500109f-Nhà Sách Book Plaza',
 '68c2341eaf9aaaa0f60b78cb-Circle K - 105 Lê Trọng Tấn',
 '68c185348535c6282e0b41a6-Trà Sữa Phi Phi',
 '68bebeb4fda51f613e077dee-Gia Lam Sport',
 '68be3d703488457daa0096c4-CA TP HCM',
 '68bd877ed81c38f0c507fe93-Matsuya Phan Văn Trị',
 '68bc376217b3f3043e0481de-Z88 Phúc Hải',
 '68bc36090c49c85d9c0fa893-Sớm Khuya',
 '68bbdc81e97cd061ae0a40ee-24/24 Coffee D5',
 '68bbb114d5bc2ab0b503af21-LUX COFFEE - ĐẮK LẮK',
 '68bbb085fd0e93c1020bc56d-30Shine',
 '68b6693a1f97c15acd035a9a-Gà Tươi Mạnh Hoạch ',
 '68b5482c22ab44a0900f95fb-Bánh Canh Long Hương - Thúy',
 '68b45fefeffcea1bbb0b3d5a-Nhà Sách FAHASA Tiền Giang',
 '68b4540f91e7c24ed1038f37-Mr.Tôm Sushi',
 '68b3afd2c5755fae5a0dc01d-Karaoke Nốt Nhạc Vui Lê Văn Sỹ',
 '68b3397450fc16960409d117-Apple Store Online',
 '68b15d8a5b94ac50350fe761-GAIGARDEN',
 '68b061655c48502cf203035f-The Wish Coffee',
 '68af042bb55dccca9a089da3-Fahasa Vincom Quận 9',
 '68af029589bde9ccb601f1a4-Divine Shop',
 '68af01cdbefad4c5620da10f-Vựa Gym',
 '68aef8e3013b2d322a0a9d74-NS Biên Hòa',
 '68aed236b721098524042aae-Texas Chicken - Nguyễn Văn Cừ',
 '68aec39769d9b749810fb332-CSID',
 '68aea42c482ad27da40bf7b8-TMART',
 '68aea246281c2d9cad0787b0-PĐM MART',
 '68ae78d0f322d39afb019311-The Art Tea Lounge',
 '68adce41cd479cca410d3f52-LA FEE Tea & Coffee',
 '68adc32a6e93ef6a570e6f06-Trà Sữa Viên Viên',
 '68ad9473032a348e040d829f-Highlands',
 '68ac636545e4efb527006773-Co.opmart Bình Tân',
 '68aae512f38459b5d000635e-Co.opmart Nhiêu Lộc',
 '68aac2f18e52a7d6b30d77f2-Tâm Tâm Vegetarian Restaurant',
 '68aabbf17ed4ac8531050a9c-Bách Hóa Xanh',
 '68aa9b842e6779cffc04a301-Z88',
 '68aa8ef321cf66075a0b47ff-Nhà Sách Biên Hòa',
 '68a947b309cce1bfe305e0b6-Bách Hóa Xanh',
 '68a912f13b8633e8ba03df75-QandA',
 '68a81977187eb5dcf9033522-Thái Yên Coffee',
 '68a6f6fd9b8ec943c20a9d14-Kingfood ',
 '68a69c649c8aed49e00b9e5f-Highand Coffe',
 '68a5eba8517b8ec71a04d122-Lục Trà Thăng Hoa ',
 '68a5e9c8207942c5ee06076c-Lục Trà Thăng Hoa',
 '68a5e984e555046b4909badc-Lục Trà Thăng Hoa ',
 '68a5e95ee555046b4909b9bb-Lục Trà Thăng Hoa']

In [ ]:
# Đếm số chunk
print(f"Tổng số chunk được tạo ra: {len(formatted_data_chunks)}")

Tổng số chunk được tạo ra: 208

---
3.Nhập API key của Gemini
---

In [ ]:
from google import genai
from google.genai import types

In [ ]:
# Khởi tạo Gemini client với API key
client = genai.Client(api_key="AIzaSyB8BRvLl4UosxXH3q4TZXJK5GQ-L5HbHhk")

In [ ]:
import time

In [ ]:
prompt= """
Bạn là một hệ thống gán nhãn thương hiệu theo tên cửa hàng sản phẩm theo đơn hàng.
Nhiệm vụ: Điền tên thương hiệu tương ứng với tên các cửa hàng theo đúng định dạng dưới đây.
⚠️ QUY TẮC BẮT BUỘC:
1. Các mã ID và tên cửa hàng bắt đầu bằng dòng:
   *<Mã ID> - <Tên cửa hàng>
   (ví dụ: '68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi')
2. Trả về tên thương hiệu dựa vào các kí tự trong tên cửa hàng, phần địa chỉ sau dấu phẩy(,) hoặc dấu gạch ngang(-) thì bỏ
   <Mã ID> - <Nhãn phụ> = <Tên thương hiệu>
   (ví dụ: 68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi=CGV)
3. không được bỏ sót chữ cái khi đánh giá tên thương hiệu, không được bịa ra tên thương hiệu mà không có trong tên cửa hàng
   (ví dụ: 68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi=Lottle là sai vì trong tên cửa hàng không có Lottle)
4. Hãy dựa vào danh sách các thương hiệu lớn trước (Những thương hiệu nổi bật ở Việt Nam); nếu không có thì lấy nguyên phần Tên cửa hàng làm Tên thương hiệu, phần địa chỉ sau dấu phẩy(,) hoặc dấu gạch ngang(-) thì bỏ
5. LUÔN phải tuân thủ đúng format như ví dụ.
6. Không được bỏ sót tất cả các dòng input nào được cho (Cho 500 dòng thì phải trả về 500 dòng)
--- Ví dụ ---
Input:
'68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi', '68d2db50ea440018b406378d-Lotte Cinema Gò Vấp'
Output:
'68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi=CGV', '68d2db50ea440018b406378d-Lotte Cinema Gò Vấp=Lotte Cinema'
--- Hết ví dụ ---
--- DANH SÁCH THƯƠNG HIỆU ---
Rau Má Mix
Highlands Coffee
Phúc Long Coffee & Tea
The Coffee House
Trung Nguyên Legend / Trung Nguyên E-Coffee
Starbucks
Gong Cha
TocoToco
Trà Sữa Ding Tea
Sharetea
Koi Thé
Mixue
Hồng Trà Ngô Gia
KFC
Lotteria
McDonald’s
Burger King
Texas Chicken
Jollibee
Pizza Hut
Domino’s Pizza
Popeyes
Gogi House
Kichi Kichi
Manwah
The Pizza Company
Co.opmart
GO
Lotte Mart
WinMart
Bách Hóa Xanh
Mega Market
Aeon Mall
Emart
Circle K
7-Eleven
Ministop
FamilyMart
Điện Máy Xanh
Thế giới di động
CellphoneS
Phong Vũ
Nhà thuốc Pharmacity
Nhà thuốc Long Châu
Nhà sách Fahasa
Muji
30Shine
Tmart
Mì Cay Sasin
Fuji Mart
Kingfood Mart
Viva Star Coffee
Mỳ Cay Seoul
Mỳ Cay Korea
GS 25
Bingxue
Lục Coffee & Tea
Hasaki
Lak Tea
Maycha
TH True Mart
Subin BBQ
Cinestar
Shan Tea
Yody
Vincom
Nhà Sách Fabico
Co.op Food
Trà Sữa Viên Viên
Lan Chi Mart
Nhà sách Bạch Đằng
Siêu Thị Con Cưng
Haidilao
Galaxy Cinema
Satrafoods
Big C
D' Maris
Ministop
MM Mega Market
Katinat
Kids Plaza
GUTA CAFE
Nhà Sách Nguyễn Văn Cừ
Dookki
Aha Cafe
Milano Coffee
Pizza Hut
Mỳ Cay Haseyo
Mì Cay Naga
Wulao
Uniqlo
Chè Chang Hi
Co.op Smile
Phê La
Nhà sách Tiền Phong
Bamos Coffee
Cinestar
Adidas
--- HẾT DANH SÁCH NHÃN ---
Bây giờ hãy xử lý dữ liệu sau theo đúng format ở trên:
{input_text}
"""

---
3.Bắt đầu dán nhãn

In [ ]:
# List to store the model's responses
gemini_responses = []

gemini_responses

In [ ]:
import datetime
import time

# Nhập phạm vi chunk muốn chạy (tính từ 1 cho dễ nhìn)
start_chunk = int(input("Nhập số chunk bắt đầu: "))
end_chunk = int(input("Nhập số chunk kết thúc: "))

# Đảm bảo không vượt ngoài phạm vi
start_chunk = max(1, start_chunk)
end_chunk = min(len(formatted_data_chunks), end_chunk)

# Tính số lượng dữ liệu trong 1 chunk
chunk_size = len(formatted_data_chunks[0]) if formatted_data_chunks else 0

# Tạo tên file với timestamp và chunk size
timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
log_filename = f"gemini_log_chunk{chunk_size}_range{start_chunk}-{end_chunk}_{timestamp}.txt"

# Mở file để ghi log
with open(log_filename, 'w', encoding='utf-8') as log_file:
    # Ghi header
    log_file.write(f"=== Gemini API Processing Log ===\n")
    log_file.write(f"Start time: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    log_file.write(f"Chunk size: {chunk_size} items\n")
    log_file.write(f"Processing range: Chunk {start_chunk} to {end_chunk}\n")
    log_file.write(f"Total chunks: {len(formatted_data_chunks)}\n")
    log_file.write("=" * 50 + "\n\n")

    # Duyệt qua range cần chạy (chú ý: index trong Python bắt đầu từ 0)
    for i in range(start_chunk-1, end_chunk):
        try:
            status_msg = f"Processing chunk {i+1}/{len(formatted_data_chunks)}"
            print(status_msg)
            log_file.write(status_msg + "\n")

            # Combine the prompt and the data chunk
            full_prompt = prompt + "\n".join(formatted_data_chunks[i])

            # Gọi API Gemini mô hình 2.0
            response = client.models.generate_content(
                model="gemini-2.0-flash-lite",
                contents=full_prompt,
                config=types.GenerateContentConfig(
                    thinking_config=types.ThinkingConfig(thinking_budget=0)
                ),
            )

            # Append the model's response to the list
            gemini_responses.append(response.text)

            # Chỉ in ra response của chunk hiện tại
            response_header = f"\n--- Response for chunk {i+1} ---"
            print(response_header)
            print(response.text)
            print("-" * 20)

            # Ghi vào log file
            log_file.write(response_header + "\n")
            log_file.write(response.text + "\n")
            log_file.write("-" * 20 + "\n")

            # Pause 60s before next request
            if i < end_chunk - 1:
                wait_msg = "⏳ Waiting 60s to avoid rate limit..."
                print(wait_msg)
                log_file.write(wait_msg + "\n\n")
                log_file.flush()  # Đảm bảo ghi ngay vào file
                time.sleep(60)

        except Exception as e:
            error_msg = f"Error processing chunk {i+1}: {e}"
            print(error_msg)
            log_file.write(error_msg + "\n\n")
            gemini_responses.append(error_msg)

    # Ghi footer
    log_file.write("\n" + "=" * 50 + "\n")
    log_file.write(f"End time: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    log_file.write(f"Total chunks processed: {end_chunk - start_chunk + 1}\n")
    log_file.write(f"Log saved to: {log_filename}\n")

print(f"\n✅ Log file saved: {log_filename}")

Nhập số chunk bắt đầu: 1
Nhập số chunk kết thúc: 4
Processing chunk 1/208

--- Response for chunk 1 ---
```
68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi=CGV
68d2db50ea440018b406378d-Lotte Cinema Gò Vấp=Lotte Cinema
68d2da3aa5272c273c0d4ec2-Dabaco Cinema Quế Võ=Dabaco Cinema
68d2d9e2277ef09e45011bcc-Rạp Chiếu Phim Beta Thanh Hóa=Rạp Chiếu Phim Beta
68d2c6e5946e8664910eb20d-Liberty Centre Point=Liberty Centre Point
68d2bd489536bef0610f07ec-MUJI=MUJI
68d2820411e9c8fc800cabc6-Piccolo Coffee 36A Kỳ Đồng=Piccolo Coffee
68d182be90af06000c00ec7e-Rau Má Mix=Rau Má Mix
68cffc5774460d688509885d-Hệ Thống Sửa Laptop - Macbook=Hệ Thống Sửa Laptop
68cf612c4abd09b9ac0841f5-Start Coffee=Start Coffee
68cd2fc29a19853b4c04449f-Hasaki=Hasaki
68cbf86fb8fcf295eb0c3f93-FUKATSU=FUKATSU
68ca5a8b5d2f4e819f0eb3fd-=
68ca2ba4ba74969dfe02d803-Hhh=Hhh
68ca2b42ba74969dfe02d764-Absabs=Absabs
68ca2b0f0d2d981b75013f82-=
68c6cc0d147524863503cd1c-Một Góc Hà Nội - 243/1 Tô Hiến Thành=Một Góc Hà Nội
68c6c3e158b6baba290ee9fe-Naan & Masala=Naan & Masala
68c5383f5c960e35620353c8-Lol=Lol
68c536c34f0804d6a90b609e-Chưa có =Chưa có
68c536b66510354e5a020556-=
68c38ca8489f5f39fe0f509d-Jiangnam=Jiangnam
68c3839d9b95188c1d0fc005-Léhem Cafe=Léhem Cafe
68c29955d54529257a07d0d9-Vi Tính Thủ đức=Vi Tính Thủ đức
68c298a7869f7f2fd500109f-Nhà Sách Book Plaza=Nhà Sách Book Plaza
68c2341eaf9aaaa0f60b78cb-Circle K - 105 Lê Trọng Tấn=Circle K
68c185348535c6282e0b41a6-Trà Sữa Phi Phi=Trà Sữa Phi Phi
68bebeb4fda51f613e077dee-Gia Lam Sport=Gia Lam Sport
68be3d703488457daa0096c4-CA TP HCM=CA TP HCM
68bd877ed81c38f0c507fe93-Matsuya Phan Văn Trị=Matsuya
68bc376217b3f3043e0481de-Z88 Phúc Hải=Z88
68bc36090c49c85d9c0fa893-Sớm Khuya=Sớm Khuya
68bbdc81e97cd061ae0a40ee-24/24 Coffee D5=24/24 Coffee
68bbb114d5bc2ab0b503af21-LUX COFFEE - ĐẮK LẮK=LUX COFFEE
68bbb085fd0e93c1020bc56d-30Shine=30Shine
68b6693a1f97c15acd035a9a-Gà Tươi Mạnh Hoạch =Gà Tươi Mạnh Hoạch
68b5482c22ab44a0900f95fb-Bánh Canh Long Hương - Thúy=Bánh Canh Long Hương
68b45fefeffcea1bbb0b3d5a-Nhà Sách FAHASA Tiền Giang=Nhà Sách FAHASA
68b4540f91e7c24ed1038f37-Mr.Tôm Sushi=Mr.Tôm Sushi
68b3afd2c5755fae5a0dc01d-Karaoke Nốt Nhạc Vui Lê Văn Sỹ=Karaoke Nốt Nhạc Vui
68b3397450fc16960409d117-Apple Store Online=Apple Store Online
68b15d8a5b94ac50350fe761-GAIGARDEN=GAIGARDEN
68b061655c48502cf203035f-The Wish Coffee=The Wish Coffee
68af042bb55dccca9a089da3-Fahasa Vincom Quận 9=Fahasa
68af029589bde9ccb601f1a4-Divine Shop=Divine Shop
68af01cdbefad4c5620da10f-Vựa Gym=Vựa Gym
68aef8e3013b2d322a0a9d74-NS Biên Hòa=NS Biên Hòa
68aed236b721098524042aae-Texas Chicken - Nguyễn Văn Cừ=Texas Chicken
68aec39769d9b749810fb332-CSID=CSID
68aea42c482ad27da40bf7b8-TMART=TMART
68aea246281c2d9cad0787b0-PĐM MART=PĐM MART
68ae78d0f322d39afb019311-The Art Tea Lounge=The Art Tea Lounge
68adce41cd479cca410d3f52-LA FEE Tea & Coffee=LA FEE Tea & Coffee
68adc32a6e93ef6a570e6f06-Trà Sữa Viên Viên=Trà Sữa Viên Viên
68ad9473032a348e040d829f-Highlands=Highlands Coffee
68ac636545e4efb527006773-Co.opmart Bình Tân=Co.opmart
68aae512f38459b5d000635e-Co.opmart Nhiêu Lộc=Co.opmart
68aac2f18e52a7d6b30d77f2-Tâm Tâm Vegetarian Restaurant=Tâm Tâm Vegetarian Restaurant
68aabbf17ed4ac8531050a9c-Bách Hóa Xanh=Bách Hóa Xanh
68aa9b842e6779cffc04a301-Z88=Z88
68aa8ef321cf66075a0b47ff-Nhà Sách Biên Hòa=Nhà Sách Biên Hòa
68a947b309cce1bfe305e0b6-Bách Hóa Xanh=Bách Hóa Xanh
68a912f13b8633e8ba03df75-QandA=QandA
68a81977187eb5dcf9033522-Thái Yên Coffee=Thái Yên Coffee
68a6f6fd9b8ec943c20a9d14-Kingfood =Kingfood
68a69c649c8aed49e00b9e5f-Highand Coffe=Highand Coffe
68a5eba8517b8ec71a04d122-Lục Trà Thăng Hoa =Lục Trà Thăng Hoa
68a5e9c8207942c5ee06076c-Lục Trà Thăng Hoa=Lục Trà Thăng Hoa
68a5e984e555046b4909badc-Lục Trà Thăng Hoa=Lục Trà Thăng Hoa
68a5e95ee555046b4909b9bb-Lục Trà Thăng Hoa=Lục Trà Thăng Hoa
```
--------------------
⏳ Waiting 60s to avoid rate limit...
Processing chunk 2/208

--- Response for chunk 2 ---
```
68a5a5688dfb7650550fa587-Shopee=Shopee
68a53fbe218916ea4000bf9d-Decathlon=Decathlon
68a4163f7eaa63978b03a0af-Pharmacity Dương Thị Mười=Pharmacity
68a2f141222988aa050a4c78-Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép=Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép
68a2e43bb14ec0d93400e6c3-Tiệm Nước Túi Bình Yên=Tiệm Nước Túi Bình Yên
68a2d379d507f6d01a07ef36-Công Ty CP MetaUni=Công Ty CP MetaUni
68a2b45fcca87d0dc70119ce-SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM=SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM
68a2895496a22ee1fc01dea8-HT CLB Doanh Nông=HT CLB Doanh Nông
68a14d0113735dda4707dbd6-Thegioixedapvt=Thegioixedapvt
68a0b729f40057460600b7d8-MIXUE - NGUYỄN ẢNH THỦ=Mixue
689fe74254f229df2a0b3f6f-BHX=Bách Hóa Xanh
689ee7916a484917e101fd14-Sync Coffee=Sync Coffee
689ee19dc0ce6590c80fb6cd-Trường Đại Học Nguyễn Tất Thành=Trường Đại Học Nguyễn Tất Thành
689c29bdff2ba94f4703eb02-Nhà Hàng Chay Làng Ta=Nhà Hàng Chay Làng Ta
689c0bb1f905e9bb170a2836-Guardian Bình Thới=Guardian
689c09d8c8d146721d0b6381-Cơm Niêu Bình Dân=Cơm Niêu Bình Dân
689b361188bc117512014afa-Sun Pet=Sun Pet
689b1edc01fe904a55071952-Tmart=Tmart
689b16747ee34bb055007504-Trà/Bánh Tráng=Trà/Bánh Tráng
689acdefe21c7d9a6d0ea950-Haseyo Nguyễn Gia Trí=Haseyo
689ac37f0223b5babc008ba4-GS25 - 511 HUỲNH VĂN BÁNH=GS 25
689a149f102266797901c9ea-Lục Trà Thăng Hoa  - Hoàng Diệu 2=Lục Coffee & Tea
6899f39d01406402130c8d5f-Góc Của Tùng=Góc Của Tùng
689747c4f1be0790590284c2-Cơm Ngon Đà Lạt=Cơm Ngon Đà Lạt
689704cfaecef7e7bc0746ab-Warning Zone Nguyễn Văn Trỗi=Warning Zone
6896e8f215f7da2bf306c2a4-Quán Ăn Gia Đình Fresh=Quán Ăn Gia Đình Fresh
6896cd885dc3e0f8d70dd9c4-Better Food Corner=Better Food Corner
6896a709c0090dae09058df1-Better Food Corner CN1=Better Food Corner
6895c98faaf5cb641503bd60-Better Food Corner CN2=Better Food Corner
68958dfad0655801020bdfbe-Cơm Bắc Lan Hương=Cơm Bắc Lan Hương
689576222ee57988a6005b04-Không Gian Khởi Nghiệp Phú Nhuận=Không Gian Khởi Nghiệp Phú Nhuận
68948dc152ace8706c011bf7-Tao Ngộ - Lẩu Gà Lá É Gà Đồi Tây Nguyên=Tao Ngộ
68936b853f6abc21c70cf2d8-Pharmacity=Pharmacity
68933578858144b97b0812cd-FamilyMart=FamilyMart
6892ce59d23883624309b4d6-Trà Sữa Phi Phi=Trà Sữa Phi Phi
68921aa71a08a3b6e80e8fc6-Mì Cay Sasin - Bình Trị Đông B=Mì Cay Sasin
68915d8e77d83af8bd09302a-Pharmacity=Pharmacity
688f6d970627912011054936-Yori=Yori
688e19094738cbc72b0f41f3-HIFA=HIFA
688e18367b781467610280de-Circle K - 13 Tôn Đản=Circle K
688dd3b09fb4fc028b0f2110-Hej Matcha=Hej Matcha
688c9f05d00b11a97f00a1dd-HAN Tea=HAN Tea
688b0ff74b2e0895c30e25fe-GUTA CAFE - 549 Điện Biên Phủ=GUTA CAFE
688af23589caa594190d86a7-Cơm Gà Giòn Giòn=Cơm Gà Giòn Giòn
688a6cf86ecf05b30f03f542-Trà Sữa Thăng Hoa - Hoàng Diệu 2=Trà Sữa Thăng Hoa
6889b9942bc907204a05089f-Mixue=Mixue
6889b3a5c63504ad350dd1c1-Another Space=Another Space
68898b6f61cb9fbfcd0201e6-Thành Coffee=Thành Coffee
6888ce043b47ff0f6d06ea0d-Casio HCM=Casio HCM
68873fef243409325703d595-MV Food & Drink=MV Food & Drink
6887105d9b76753f950b2694-Mr.Eco Salad Healthy=Mr.Eco Salad Healthy
688601b4d4a8c0fa3f0afc83-Pizza Có Tâm=Pizza Có Tâm
68820fa5413cb1dfa002207d-Nhà Của Thời Thanh Xuân=Nhà Của Thời Thanh Xuân
687e4b4c832afb99c901e42a-Lyn's Chicken=Lyn's Chicken
687e2dfc4b84bd27d602f671-Cháo Ếch Singapo=Cháo Ếch Singapo
687cc4bdb60896ca2c08d90a-Phamacity=Phamacity
687ca27b95cc713e1a069c68-HIGHLANDS - LÝ CHÍNH THẮNG=Highlands Coffee
687b3ca60cd23608eb01ba92-BÁCH HOÁ XANH - 234 HOÀNG HOA THÁM=Bách Hóa Xanh
687b1b445757ebed1e0a01d0-HIGHLANDS COFFEE - ĐỨC TRỌNG=Highlands Coffee
6878f4accc12d6e77f0d6651-Famarcity=Famarcity
6878f490cc12d6e77f0d662b-Famarcity=Famarcity
6878e499e131880aae086f21-Lục Coffee & Tea=Lục Coffee & Tea
6878df6989e0b7a3980dc8ef-Mì Quảng Ăn Là Nhớ=Mì Quảng Ăn Là Nhớ
6878c7f1d08042df55085a61-My Cafe=My Cafe
6877c23d2cc7b484f205a688-Hằng Lê Trà Sữa=Hằng Lê Trà Sữa
6877973dfa0fc330f0058328-Lẩu Cá Kèo Chị Tôi=Lẩu Cá Kèo Chị Tôi
687771fc4f2307d1780564e9-Sowee Space=Sowee Space
68767a43d15605ecd00ac765-MINISTOP -  87 VẠN KIẾP=Ministop
68762acf6328af071207bf4d-Khách Sạn Sân Vườn Hà Giang 2=Khách Sạn Sân Vườn Hà Giang 2
6874f4fcd47d97f2de00aaaa-Cộng đồng Design Thinking - Techfest VN=Cộng đồng Design Thinking - Techfest VN
```
--------------------
⏳ Waiting 60s to avoid rate limit...
Processing chunk 3/208

--- Response for chunk 3 ---
```
687330ef00ec32366706bb39-Thè M Cafe=Thè M Cafe
6873238908538e0e540d09cf-Coop Mart=Co.opmart
687305620fa540ae4203d4f1-Cafe Amazon=Cafe Amazon
686f7986d0071401cd047f22-Demo=Demo
686f656be89127d1230221d9-CO=CO
686f52955ef920311b05dc29-Cá Ơi Làng Chài=Cá Ơi Làng Chài
686dff07f262f568fc06df4d-Jollibee Vạn Hạnh Mall=Jollibee
686dfee887f39ff57c0ed64f-Jollibee Vạn Hạnh Mall=Jollibee
686dc9441dfb73a7e70dc5e8-HIGHLANDS COFFEE - PHẠM VĂN ĐỒNG=HIGHLANDS COFFEE
686cd280c43efc0888069b30-Xịn House Design=Xịn House Design
686c9afb6384edb1be0d4351-Xịn House Design=Xịn House Design
686c92bdae2402127603c856-Xịn House Design=Xịn House Design
686b4a51d8831e60f80b6437-HIGHLANDS COFFEE - VINWONDERS=HIGHLANDS COFFEE
686b3ec2a3f83eacd90b53f2-Vị Cà Phê=Vị Cà Phê
686a38523d153c07720483b2-BÁCH HOÁ XANH - 173 BÙI ĐÌNH TUÝ=Bách Hóa Xanh
686a35b7ffca6b6b4f0a2263-Mangrove=Mangrove
6869426f5095b2086e0ddbd8-Pharmacity=Pharmacity
68692c07d7593087810221f6-Ăn Vặt 148=Ăn Vặt 148
6868d73bb2cb722fb00b5058-CLB ROPOLY=CLB ROPOLY
6866119d9ff61d515d01a29b-Tiệm Cà Phê Xứ Nam Kỳ=Tiệm Cà Phê Xứ Nam Kỳ
68654ef63375be60d904d2ff-Pharnacity=Pharmacity
68649b159aa2165a0d05352b-Cafe 24/24=Cafe 24/24
68648987c26933c0d2008f7d-Circle K - 106 Hoàng Diệu=Circle K
6863b544c9eb3c10b60f75ab-Fuji Mart Tân Mai=Fuji Mart
68629331580df7b7c5065536-Starbuck - Quang Trung=Starbuck
68629274e63af9122503659a-Sun Pet=Sun Pet
6862905fe24909a5f707a408-Lẩu Gật Gù=Lẩu Gật Gù
68627d93cf0eeeb8720397cb-KYO WATAMI Grill & Sushi=KYO WATAMI Grill & Sushi
686233b641b885e5b30a656c-Phát Đạt Dental=Phát Đạt Dental
68614cdd498b547dc706b370-7 Map=7 Map
686135f6c940db29c801aabf-Lẩu Cá Mang Về 69k=Lẩu Cá Mang Về 69k
6860e8a5767a67702e052dfe-Xịn House=Xịn House
685ff5fd01db61a6560451c1-Lẩu Phong Vị 24H=Lẩu Phong Vị 24H
685ff595fee372bf2c0cd43d-Lẩu Phong Vị 24H=Lẩu Phong Vị 24H
685f8161f1d049f2360bf326-COCÉVI Coffee And Chill=COCÉVI Coffee And Chill
685e724a672f1fc415008b3d-B-S Mart=B-S Mart
685e0cd4358056f736072355-COCÉVI Coffee And Chill=COCÉVI Coffee And Chill
685d2ec992503ebd140a9ed3-Circle K - D5=Circle K
685cd2f4d635521ddf09d881-Haga=Haga
685cd2b5d635521ddf09d81c-Anc=Anc
685cd15deb90e320be003d1d-Trà Sữa Shiney=Trà Sữa Shiney
685cd09dc93ab13cda012bad-Trà Sữa Shiney=Trà Sữa Shiney
685c09859a93e297e30be332-Tacos Labubu=Tacos Labubu
685bd92db1a548fad10bedd7-Takashimaya=Takashimaya
685bd725b49528302c0b873b-Cây Đầu To=Cây Đầu To
685bd71aff05da42680b6bf6-Cây Đầu To=Cây Đầu To
685bc3f06c348405ef03dd5c-Cà Rề Cafe=Cà Rề Cafe
685aad92653f27aea70bea19-Vinamilk=Vinamilk
685a9f1844d2b42c1f09686c-Yolo BBQ=Yolo BBQ
685a926eaeba1bed9f0383a4-Metro Khu Công Nghệ Cao=Metro Khu Công Nghệ Cao
685a74557a005a2c150d0141-Street Coffee=Street Coffee
685a62b5d19a80e1e109a02b-HIGHLANDS COFFEE - MENAS MALL=HIGHLANDS COFFEE
685a622ca63f105b680ac5dd-HIGHLANDS COFFEE - MENAS MALL=HIGHLANDS COFFEE
685a36d28bbba8fd49008bb8-Metro Bến Thành=Metro Bến Thành
685a2ee244b9eb49bc0ba6ac-Kim Đô=Kim Đô
6859f1053a9a1712b30ad750-Nhà Sách Mực Tím=Nhà Sách Mực Tím
6859977cdcea1abe2e05f658-Bách Hóa Xanh=Bách Hóa Xanh
68592110c1b0c4fea3024722-Blue Dream=Blue Dream
6857e2fc283acb45060de9e3-Monstera Roastery Coffee=Monstera Roastery Coffee
6857a57694d4f594fb04d822-Hutong Hotspot=Hutong Hotspot
6856b58368ced4e4ae0dc958-FamilyMart=FamilyMart
6856b4f67e991d6aa30929fb-Gà Hầm Thố đá=Gà Hầm Thố đá
68568fdf37dffc60fe004cd7-KingCross=KingCross
685687c12850751427027028-KAI COFFEE K300, Cong Hoa=KAI COFFEE
68566f0dac34588a9e02d4f3-Bách Hóa Xanh=Bách Hóa Xanh
68554663be2053c1fd09b5ba-Xù Food=Xù Food
6854bc9842c79443da07ba6c-BELL CLUB=BELL CLUB
6853c521f0b657214900ed07-Aeon Mall Long Biên=Aeon Mall
6853a7c0f0ef27e43b0f13c5-Higland Coffee=Higland Coffee
6852c0b3fe5899bf6a050073-Năm Ánh=Năm Ánh
```
--------------------
⏳ Waiting 60s to avoid rate limit...
Processing chunk 4/208

--- Response for chunk 4 ---
```
6852af9fdcc037284f0921f8-Demo=Demo
68528c6011126a5182070891-Circles Cafe=Circles Cafe
68527d1d7fe1725eac0cb897-Traffee Tea & Coffee=Traffee Tea & Coffee
685242e4b24f9855b204e964-Lotteria Coopmart Cam Ranh=Lotteria
68516e2eab22c7d0db0c0ff5-Trà Sữa Viên Viên=Trà Sữa Viên Viên
684fdf46b9fb72530d09f3b9-Ấp Cafe =Ấp Cafe
684fbcdcf1be16dc630d5812-Novo Cafe=Novo Cafe
684e7f77f34875596c0ef094-LÀ VIỆT COFFEE - PHÓ ĐỨC CHINH=LÀ VIỆT COFFEE
684e4a907e6ef61f8d03a81d-Beanthere Cafe - Hoàng Sa=Beanthere Cafe
684e31bbb5ec250bea0fe274-Cầu Đất Showroom=Cầu Đất Showroom
684e2526130191680800d1db-The Casca Coffee=The Casca Coffee
684d2ab487f1ba96330bb9bf-Cafe Phuc Long=Phuc Long Coffee
684d18880d31ec4c7c0913c6-Phuc Long Coffee & Tea - 352 Võ Văn Ngân=Phuc Long Coffee
684c3464d40dcf8e6303c39f-Nhà Hàng Hương Cau 2=Nhà Hàng Hương Cau 2
684ba23363c01bc71309f825-Kingfood=Kingfood
684a6d285caf3ca2f901810a-Teamax=Teamax
684a4a61c5588ab4e90aded8-POLA COFFEE & TEA=POLA COFFEE
6849665247df3e85fa0cb3e7-Beer Đức Jaderborner=Beer Đức Jaderborner
6849542fae03cd62b40f47bf-Cây Cột Điện Coffee Books=Cây Cột Điện Coffee Books
6849540dd6f5fd1a9f032fcb-Cây Cột Điện Coffee Books=Cây Cột Điện Coffee Books
68494b00dc5d7248d00adaf0-Passio Coffee To Go=Passio Coffee
68494ae93a4722399e01e3bd-Passio Coffee=Passio Coffee
6847eafb54a62352700c5b2c-Trà Sữa Thái Lan Songkran=Trà Sữa Thái Lan Songkran
6847e2fcd1ba7916850e6096-Saigon Centre=Saigon Centre
6847a6b06597efdf5d095b02-HIGHLANDS COFFEE - ĐẠI LỘ BÌNH DƯƠNG=Highlands Coffee
6846e875b9f8d1fee601665a-Meta Cafe=Meta Cafe
68468c156d2c3f8b00039270-HE Tea & Coffee=HE Tea
68468bd1f6614a4cde0a881b-HE Tea & Coffee=HE Tea
68468a18679da347af0b9823-HE Tea & Coffee=HE Tea
684689fb714b3a51ce07cd04-HE Tea & Coffee=HE Tea
684689af4d4690a18c077cc6-HE Tea & Coffee=HE Tea
684689923cd32ac85704ec59-HE Tea & Coffee=HE Tea
6846896dcc27367f620f2f58-HE Tea & Coffee=HE Tea
684689516a227f160305a329-HE Tea & Coffee=HE Tea
6846890c0cf7b50d490d4734-He Tea & Coffee=He Tea
68465c3bfb8229b8ab0c8824-Dtel Office=Dtel Office
68465a78dd86dd042c0a894e-BlueTechX Office=BlueTechX Office
68443802dae5d17a8c0762ce-Nhi Đồng 315 Và Tiêm Chủng=Nhi Đồng 315 Và Tiêm Chủng
6843ed7ec67491a4b30fbef0-Hiên Nhà Coffee=Hiên Nhà Coffee
6843ed38eb8376415e008eb7-Hiên Nhà=Hiên Nhà
6843ec4e266bb7a40b07761b-Hiên Nhà Coffee=Hiên Nhà Coffee
6843cc232e86e5cbcb0d3e62-Hủ Tiếu Ghẹ Muối Ớt Đỏ=Hủ Tiếu Ghẹ Muối Ớt Đỏ
6843983ecb9dd8b8df0ba16a-Trường Đại Học Khoa Học Tự Nhiên TP HCM=Trường Đại Học Khoa Học Tự Nhiên TP HCM
68430d23bb5138814f0406a8-Tiệm Sa Chuỷ 80s=Tiệm Sa Chuỷ 80s
6842eb82101bca96ac019df5-Lotteria Thường Tín=Lotteria
6842eb718714eb32ee0147c7-Loterria Thường Tín=Loterria
6842c0c06087b08ee609fc46-Gd=Gd
68427bdbd317116bd30e2e27-Saigon Innovation Hub - SIHUB =Saigon Innovation Hub
6842431977516023f20a5f22-F Coffer=F Coffer
6841b6ffa3675578860183c5-Gon Cake=Gon Cake
6841b698752f1f0b2b09f162-Gon Cake=Gon Cake
6841b66aec3d8cc7ac0a2fc3-Gôn Cake=Gôn Cake
6841a2fac07a7554a30fc6a7-Tra Sữa Viên Viên=Trà Sữa Viên Viên
68413f238e92e677a8062311-Nhà Hàng Đức Dương Palace =Nhà Hàng Đức Dương Palace
68401e12f664053102030fd3-Hội Trường Trịnh Công Sơn - Trường Đại Học Văn Lang =Hội Trường Trịnh Công Sơn
68400b987f3f136dd20cc69b-Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI - Diamond Brand Institute)=Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI
683eb363e302ccd57307be52-MetaUni=MetaUni
683d98e5296533f6b208d42a-Golden Bakery 2=Golden Bakery 2
683d98abde408c11180fcbac-Golden Bakeryvungx=Golden Bakeryvungx
683d6e866c8412d2890a5506-Hongkong Baley =Hongkong Baley
683c597e4c2ed87da5005283-Kingfoodmart Era Town=Kingfood Mart
683c596679098ab3020d7379-Kingfood Mart Era Town=Kingfood Mart
683c58724e514b86ec0d0506-Ông Chủ Nhỏ=Ông Chủ Nhỏ
683c544e5b6b821e1608c857-Cà Phê ông Bầu Quận 7=Cà Phê ông Bầu
683c4c9d58e39aead4098c92-Vĩnh Phát Dimsum=Vĩnh Phát Dimsum
683bdab0d2df8ae62405966b-Kohaku=Kohaku
683acfc0a8d4f18de1012e12-Bách Gia Tinh Hoa=Bách Gia Tinh Hoa
683ab8a2428268c54306b0d3-BGTH - Vương Gia=BGTH
683ab87f89174d5d560e8953-BGTH - Trịnh Gia=BGTH
683ab8549abbd61a8509cf1b-BGTH - Tạ Gia=BGTH
```
--------------------

✅ Log file saved: gemini_log_chunk70_range1-4_20251027_074948.txt

In [ ]:
gemini_responses

['68d2de42cc9361574c028970-CGV Saigonres Nguyen Xi=CGV\n68d2db50ea440018b406378d-Lotte Cinema Gò Vấp=Lotte Cinema\n68d2da3aa5272c273c0d4ec2-Dabaco Cinema Quế Võ=Dabaco Cinema\n68d2d9e2277ef09e45011bcc-Rạp Chiếu Phim Beta Thanh Hóa=Rạp Chiếu Phim Beta Thanh Hóa\n68d2c6e5946e8664910eb20d-Liberty Centre Point=Liberty Centre Point\n68d2bd489536bef0610f07ec-MUJI=MUJI\n68d2820411e9c8fc800cabc6-Piccolo Coffee 36A Kỳ Đồng=Piccolo Coffee\n68d182be90af06000c00ec7e-Rau Má Mix=Rau Má Mix\n68cffc5774460d688509885d-Hệ Thống Sửa Laptop - Macbook=Hệ Thống Sửa Laptop - Macbook\n68cf612c4abd09b9ac0841f5-Start Coffee=Start Coffee\n68cd2fc29a19853b4c04449f-Hasaki=Hasaki\n68cbf86fb8fcf295eb0c3f93-FUKATSU=FUKATSU\n68ca5a8b5d2f4e819f0eb3fd-=\n68ca2ba4ba74969dfe02d803-Hhh=Hhh\n68ca2b42ba74969dfe02d764-Absabs=Absabs\n68ca2b0f0d2d981b75013f82-=\n68c6cc0d147524863503cd1c-Một Góc Hà Nội - 243/1 Tô Hiến Thành=Một Góc Hà Nội\n68c6c3e158b6baba290ee9fe-Naan & Masala=Naan & Masala\n68c5383f5c960e35620353c8-Lol=Lol\n68c536c34f0804d6a90b609e-Chưa có =Chưa có \n68c536b66510354e5a020556-=\n68c38ca8489f5f39fe0f509d-Jiangnam=Jiangnam\n68c3839d9b95188c1d0fc005-Léhem Cafe=Léhem Cafe\n68c29955d54529257a07d0d9-Vi Tính Thủ đức=Vi Tính Thủ đức\n68c298a7869f7f2fd500109f-Nhà Sách Book Plaza=Nhà Sách Book Plaza\n68c2341eaf9aaaa0f60b78cb-Circle K - 105 Lê Trọng Tấn=Circle K\n68c185348535c6282e0b41a6-Trà Sữa Phi Phi=Trà Sữa Phi Phi\n68bebeb4fda51f613e077dee-Gia Lam Sport=Gia Lam Sport\n68be3d703488457daa0096c4-CA TP HCM=CA TP HCM\n68bd877ed81c38f0c507fe93-Matsuya Phan Văn Trị=Matsuya\n68bc376217b3f3043e0481de-Z88 Phúc Hải=Z88 Phúc Hải\n68bc36090c49c85d9c0fa893-Sớm Khuya=Sớm Khuya\n68bbdc81e97cd061ae0a40ee-24/24 Coffee D5=24/24 Coffee\n68bbb114d5bc2ab0b503af21-LUX COFFEE - ĐẮK LẮK=LUX COFFEE\n68bbb085fd0e93c1020bc56d-30Shine=30Shine\n68b6693a1f97c15acd035a9a-Gà Tươi Mạnh Hoạch=Gà Tươi Mạnh Hoạch\n68b5482c22ab44a0900f95fb-Bánh Canh Long Hương - Thúy=Bánh Canh Long Hương\n68b45fefeffcea1bbb0b3d5a-Nhà Sách FAHASA Tiền Giang=Nhà Sách FAHASA\n68b4540f91e7c24ed1038f37-Mr.Tôm Sushi=Mr.Tôm Sushi\n68b3afd2c5755fae5a0dc01d-Karaoke Nốt Nhạc Vui Lê Văn Sỹ=Karaoke Nốt Nhạc Vui\n68b3397450fc16960409d117-Apple Store Online=Apple Store Online\n68b15d8a5b94ac50350fe761-GAIGARDEN=GAIGARDEN\n68b061655c48502cf203035f-The Wish Coffee=The Wish Coffee\n68af042bb55dccca9a089da3-Fahasa Vincom Quận 9=Fahasa\n68af029589bde9ccb601f1a4-Divine Shop=Divine Shop\n68af01cdbefad4c5620da10f-Vựa Gym=Vựa Gym\n68aef8e3013b2d322a0a9d74-NS Biên Hòa=NS Biên Hòa\n68aed236b721098524042aae-Texas Chicken - Nguyễn Văn Cừ=Texas Chicken\n68aea42c482ad27da40bf7b8-TMART=TMART\n',
 '```\n68aea246281c2d9cad0787b0-PĐM MART=PĐM MART\n68ae78d0f322d39afb019311-The Art Tea Lounge=The Art Tea Lounge\n68adce41cd479cca410d3f52-LA FEE Tea & Coffee=LA FEE\n68adc32a6e93ef6a570e6f06-Trà Sữa Viên Viên=Trà Sữa Viên Viên\n68ad9473032a348e040d829f-Highlands=Highlands Coffee\n68ac636545e4efb527006773-Co.opmart Bình Tân=Co.opmart\n68aae512f38459b5d000635e-Co.opmart Nhiêu Lộc=Co.opmart\n68aac2f18e52a7d6b30d77f2-Tâm Tâm Vegetarian Restaurant=Tâm Tâm Vegetarian Restaurant\n68aabbf17ed4ac8531050a9c-Bách Hóa Xanh=Bách Hóa Xanh\n68aa9b842e6779cffc04a301-Z88=Z88\n68aa8ef321cf66075a0b47ff-Nhà Sách Biên Hòa=Nhà Sách Biên Hòa\n68a947b309cce1bfe305e0b6-Bách Hóa Xanh=Bách Hóa Xanh\n68a912f13b8633e8ba03df75-QandA=QandA\n68a81977187eb5dcf9033522-Thái Yên Coffee=Thái Yên Coffee\n68a6f6fd9b8ec943c20a9d14-Kingfood =Kingfood Mart\n68a69c649c8aed49e00b9e5f-Highand Coffe=Highlands Coffee\n68a5eba8517b8ec71a04d122-Lục Trà Thăng Hoa =Lục Coffee & Tea\n68a5e9c8207942c5ee06076c-Lục Trà Thăng Hoa=Lục Coffee & Tea\n68a5e984e555046b4909badc-Lục Trà Thăng Hoa =Lục Coffee & Tea\n68a5e95ee555046b4909b9bb-Lục Trà Thăng Hoa=Lục Coffee & Tea\n68a5a5688dfb7650550fa587-Shopee=Shopee\n68a53fbe218916ea4000bf9d-Decathlon=Decathlon\n68a4163f7eaa63978b03a0af-Pharmacity Dương Thị Mười=Nhà thuốc Pharmacity\n68a2f141222988aa050a4c78-Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép=Trung Tâm Dạy Trẻ Tự Kỷ - Chậm Nói Hoa Sen Kép\n68a2e43bb14ec0d93400e6c3-Tiệm Nước Túi Bình Yên=Tiệm Nước Túi Bình Yên\n68a2d379d507f6d01a07ef36-Công Ty CP MetaUni=Công Ty CP MetaUni\n68a2b45fcca87d0dc70119ce-SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM=SIHUB - Trung Tâm Khởi Nghiệp Sáng Tạo TP.HCM\n68a2895496a22ee1fc01dea8-HT CLB Doanh Nông=HT CLB Doanh Nông\n68a14d0113735dda4707dbd6-Thegioixedapvt=Thegioixedapvt\n68a0b729f40057460600b7d8-MIXUE - NGUYỄN ẢNH THỦ=Mixue\n689fe74254f229df2a0b3f6f-BHX=Bách Hóa Xanh\n689ee7916a484917e101fd14-Sync Coffee=Sync Coffee\n689ee19dc0ce6590c80fb6cd-Trường Đại Học Nguyễn Tất Thành=Trường Đại Học Nguyễn Tất Thành\n689c29bdff2ba94f4703eb02-Nhà Hàng Chay Làng Ta=Nhà Hàng Chay Làng Ta\n689c0bb1f905e9bb170a2836-Guardian Bình Thới=Guardian\n689c09d8c8d146721d0b6381-Cơm Niêu Bình Dân=Cơm Niêu Bình Dân\n689b361188bc117512014afa-Sun Pet=Sun Pet\n689b1edc01fe904a55071952-Tmart =Tmart\n689b16747ee34bb055007504-Trà/Bánh Tráng=Trà/Bánh Tráng\n689acdefe21c7d9a6d0ea950-Haseyo Nguyễn Gia Trí=Haseyo\n689ac37f0223b5babc008ba4-GS25 - 511 HUỲNH VĂN BÁNH=GS 25\n689a149f102266797901c9ea-Lục Trà Thăng Hoa  - Hoàng Diệu 2=Lục Coffee & Tea\n6899f39d01406402130c8d5f-Góc Của Tùng=Góc Của Tùng\n689747c4f1be0790590284c2-Cơm Ngon Đà Lạt=Cơm Ngon Đà Lạt\n689704cfaecef7e7bc0746ab-Warning Zone Nguyễn Văn Trỗi=Warning Zone\n6896e8f215f7da2bf306c2a4-Quán Ăn Gia Đình Fresh=Quán Ăn Gia Đình Fresh\n6896cd885dc3e0f8d70dd9c4-Better Food Corner=Better Food Corner\n6896a709c0090dae09058df1-Better Food Corner CN1=Better Food Corner\n6895c98faaf5cb641503bd60-Better Food Corner CN2=Better Food Corner\n68958dfad0655801020bdfbe-Cơm Bắc Lan Hương=Cơm Bắc Lan Hương\n```',
 "689576222ee57988a6005b04-Không Gian Khởi Nghiệp Phú Nhuận=Không Gian Khởi Nghiệp Phú Nhuận\n68948dc152ace8706c011bf7-Tao Ngộ - Lẩu Gà Lá É Gà Đồi Tây Nguyên=Tao Ngộ\n68936b853f6abc21c70cf2d8-Pharmacity=Nhà thuốc Pharmacity\n68933578858144b97b0812cd-FamilyMart=FamilyMart\n6892ce59d23883624309b4d6-Trà Sữa Phi Phi=Trà Sữa Phi Phi\n68921aa71a08a3b6e80e8fc6-Mì Cay Sasin - Bình Trị Đông B=Mì Cay Sasin\n68915d8e77d83af8bd09302a-Pharmacity=Nhà thuốc Pharmacity\n688f6d970627912011054936-Yori=Yori\n688e19094738cbc72b0f41f3-HIFA=HIFA\n688e18367b781467610280de-Circle K - 13 Tôn Đản=Circle K\n688dd3b09fb4fc028b0f2110-Hej Matcha=Hej Matcha\n688c9f05d00b11a97f00a1dd-HAN Tea=HAN Tea\n688b0ff74b2e0895c30e25fe-GUTA CAFE - 549 Điện Biên Phủ=GUTA CAFE\n688af23589caa594190d86a7-Cơm Gà Giòn Giòn=Cơm Gà Giòn Giòn\n688a6cf86ecf05b30f03f542-Trà Sữa Thăng Hoa - Hoàng Diệu 2=Trà Sữa Thăng Hoa\n6889b9942bc907204a05089f-Mixue=Mixue\n6889b3a5c63504ad350dd1c1-Another Space=Another Space\n68898b6f61cb9fbfcd0201e6-Thành Coffee=Thành Coffee\n6888ce043b47ff0f6d06ea0d-Casio HCM=Casio HCM\n68873fef243409325703d595-MV Food & Drink=MV Food & Drink\n6887105d9b76753f950b2694-Mr.Eco Salad Healthy=Mr.Eco Salad Healthy\n688601b4d4a8c0fa3f0afc83-Pizza Có Tâm=Pizza Có Tâm\n68820fa5413cb1dfa002207d-Nhà Của Thời Thanh Xuân=Nhà Của Thời Thanh Xuân\n687e4b4c832afb99c901e42a-Lyn's Chicken=Lyn's Chicken\n687e2dfc4b84bd27d602f671-Cháo Ếch Singapo=Cháo Ếch Singapo\n687cc4bdb60896ca2c08d90a-Phamacity=Nhà thuốc Pharmacity\n687ca27b95cc713e1a069c68-HIGHLANDS - LÝ CHÍNH THẮNG=Highlands Coffee\n687b3ca60cd23608eb01ba92-BÁCH HOÁ XANH - 234 HOÀNG HOA THÁM=Bách Hóa Xanh\n687b1b445757ebed1e0a01d0-HIGHLANDS COFFEE - ĐỨC TRỌNG=Highlands Coffee\n6878f4accc12d6e77f0d6651-Famarcity=Famarcity\n6878f490cc12d6e77f0d662b-Famarcity=Famarcity\n6878e499e131880aae086f21-Lục Coffee & Tea=Lục Coffee & Tea\n6878df6989e0b7a3980dc8ef-Mì Quảng Ăn Là Nhớ=Mì Quảng Ăn Là Nhớ\n6878c7f1d08042df55085a61-My Cafe=My Cafe\n6877c23d2cc7b484f205a688-Hằng Lê Trà Sữa=Hằng Lê Trà Sữa\n6877973dfa0fc330f0058328-Lẩu Cá Kèo Chị Tôi=Lẩu Cá Kèo Chị Tôi\n687771fc4f2307d1780564e9-Sowee Space=Sowee Space\n68767a43d15605ecd00ac765-MINISTOP -  87 VẠN KIẾP=Ministop\n68762acf6328af071207bf4d-Khách Sạn Sân Vườn Hà Giang 2=Khách Sạn Sân Vườn Hà Giang 2\n6874f4fcd47d97f2de00aaaa-Cộng đồng Design Thinking - Techfest VN=Cộng đồng Design Thinking\n687330ef00ec32366706bb39-Thè M Cafe=Thè M Cafe\n6873238908538e0e540d09cf-Coop Mart=Co.opmart\n687305620fa540ae4203d4f1-Cafe Amazon=Cafe Amazon\n686f7986d0071401cd047f22-Demo=Demo\n686f656be89127d1230221d9-CO=CO\n686f52955ef920311b05dc29-Cá Ơi Làng Chài=Cá Ơi Làng Chài\n686dff07f262f568fc06df4d-Jollibee Vạn Hạnh Mall=Jollibee\n686dfee887f39ff57c0ed64f-Jollibee Vạn Hạnh Mall=Jollibee\n686dc9441dfb73a7e70dc5e8-HIGHLANDS COFFEE - PHẠM VĂN ĐỒNG=Highlands Coffee\n686cd280c43efc0888069b30-Xịn House Design=Xịn House Design\n",
 '```\n686c9afb6384edb1be0d4351-Xịn House Design = Xịn House Design\n686c92bdae2402127603c856-Xịn House Design = Xịn House Design\n686b4a51d8831e60f80b6437-HIGHLANDS COFFEE - VINWONDERS=Highlands Coffee\n686b3ec2a3f83eacd90b53f2-Vị Cà Phê=Vị Cà Phê\n686a38523d153c07720483b2-BÁCH HOÁ XANH - 173 BÙI ĐÌNH TUÝ=Bách Hóa Xanh\n686a35b7ffca6b6b4f0a2263-Mangrove=Mangrove\n6869426f5095b2086e0ddbd8-Pharmacity=Nhà thuốc Pharmacity\n68692c07d7593087810221f6-Ăn Vặt 148=Ăn Vặt 148\n6868d73bb2cb722fb00b5058-CLB ROPOLY=CLB ROPOLY\n6866119d9ff61d515d01a29b-Tiệm Cà Phê Xứ Nam Kỳ=Tiệm Cà Phê Xứ Nam Kỳ\n68654ef63375be60d904d2ff-Pharnacity=Pharnacity\n68649b159aa2165a0d05352b-Cafe 24/24=Cafe 24/24\n68648987c26933c0d2008f7d-Circle K - 106 Hoàng Diệu=Circle K\n6863b544c9eb3c10b60f75ab-Fuji Mart Tân Mai=Fuji Mart\n68629331580df7b7c5065536-Starbuck - Quang Trung=Starbuck - Quang Trung\n68629274e63af9122503659a-Sun Pet=Sun Pet\n6862905fe24909a5f707a408-Lẩu Gật Gù=Lẩu Gật Gù\n68627d93cf0eeeb8720397cb-KYO WATAMI Grill & Sushi=KYO WATAMI Grill & Sushi\n686233b641b885e5b30a656c-Phát Đạt Dental=Phát Đạt Dental\n68614cdd498b547dc706b370-7 Map=7 Map\n686135f6c940db29c801aabf-Lẩu Cá Mang Về 69k=Lẩu Cá Mang Về 69k\n6860e8a5767a67702e052dfe-Xịn House=Xịn House\n685ff5fd01db61a6560451c1-Lẩu Phong Vị 24H=Lẩu Phong Vị 24H\n685ff595fee372bf2c0cd43d-Lẩu Phong Vị 24H=Lẩu Phong Vị 24H\n685f8161f1d049f2360bf326-COCÉVI Coffee And Chill=COCÉVI Coffee And Chill\n685e724a672f1fc415008b3d-B-S Mart=B-S Mart\n685e0cd4358056f736072355-COCÉVI Coffee And Chill=COCÉVI Coffee And Chill\n685d2ec992503ebd140a9ed3-Circle K - D5=Circle K\n685cd2f4d635521ddf09d881-Haga=Haga\n685cd2b5d635521ddf09d81c-Anc=Anc\n685cd15deb90e320be003d1d-Trà Sữa Shiney=Trà Sữa Shiney\n685cd09dc93ab13cda012bad-Trà Sữa Shiney=Trà Sữa Shiney\n685c09859a93e297e30be332-Tacos Labubu=Tacos Labubu\n685bd92db1a548fad10bedd7-Takashimaya=Takashimaya\n685bd725b49528302c0b873b-Cây Đầu To=Cây Đầu To\n685bd71aff05da42680b6bf6-Cây Đầu To=Cây Đầu To\n685bc3f06c348405ef03dd5c-Cà Rề Cafe=Cà Rề Cafe\n685aad92653f27aea70bea19-Vinamilk=Vinamilk\n685a9f1844d2b42c1f09686c-Yolo BBQ=Yolo BBQ\n685a926eaeba1bed9f0383a4-Metro Khu Công Nghệ Cao=Metro Khu Công Nghệ Cao\n685a74557a005a2c150d0141-Street Coffee =Street Coffee \n685a62b5d19a80e1e109a02b-HIGHLANDS COFFEE - MENAS MALL=Highlands Coffee\n685a622ca63f105b680ac5dd-HIGHLANDS COFFEE - MENAS MALL=Highlands Coffee\n685a36d28bbba8fd49008bb8-Metro Bến Thành=Metro Bến Thành\n685a2ee244b9eb49bc0ba6ac-Kim Đô=Kim Đô\n6859f1053a9a1712b30ad750-Nhà Sách Mực Tím=Nhà Sách Mực Tím\n6859977cdcea1abe2e05f658-Bách Hóa Xanh=Bách Hóa Xanh\n68592110c1b0c4fea3024722-Blue Dream=Blue Dream\n6857e2fc283acb45060de9e3-Monstera Roastery Coffee=Monstera Roastery Coffee\n6857a57694d4f594fb04d822-Hutong Hotspot=Hutong Hotspot\n```',
 '```\n6856b58368ced4e4ae0dc958-FamilyMart=FamilyMart\n6856b4f67e991d6aa30929fb-Gà Hầm Thố đá=Gà Hầm Thố đá\n68568fdf37dffc60fe004cd7-KingCross=KingCross\n685687c12850751427027028-KAI COFFEE K300, Cong Hoa=KAI COFFEE\n68566f0dac34588a9e02d4f3-Bách Hóa Xanh=Bách Hóa Xanh\n68554663be2053c1fd09b5ba-Xù Food=Xù Food\n6854bc9842c79443da07ba6c-BELL CLUB=BELL CLUB\n6853c521f0b657214900ed07-Aeon Mall Long Biên=Aeon Mall\n6853a7c0f0ef27e43b0f13c5-Higland Coffee=Higland Coffee\n6852c0b3fe5899bf6a050073-Năm Ánh=Năm Ánh\n6852af9fdcc037284f0921f8-Demo=Demo\n68528c6011126a5182070891-Circles Cafe=Circles Cafe\n68527d1d7fe1725eac0cb897-Traffee Tea & Coffee=Traffee Tea & Coffee\n685242e4b24f9855b204e964-Lotteria Coopmart Cam Ranh=Lotteria\n68516e2eab22c7d0db0c0ff5-Trà Sữa Viên Viên=Trà Sữa Viên Viên\n684fdf46b9fb72530d09f3b9-Ấp Cafe=Ấp Cafe\n684fbcdcf1be16dc630d5812-Novo Cafe=Novo Cafe\n684e7f77f34875596c0ef094-LÀ VIỆT COFFEE - PHÓ ĐỨC CHINH=LÀ VIỆT COFFEE\n684e4a907e6ef61f8d03a81d-Beanthere Cafe - Hoàng Sa=Beanthere Cafe\n684e31bbb5ec250bea0fe274-Cầu Đất Showroom=Cầu Đất Showroom\n684e2526130191680800d1db-The Casca Coffee=The Casca Coffee\n684d2ab487f1ba96330bb9bf-Cafe Phuc Long=Cafe Phuc Long\n684d18880d31ec4c7c0913c6-Phuc Long Coffee & Tea - 352 Võ Văn Ngân=Phuc Long Coffee & Tea\n684c3464d40dcf8e6303c39f-Nhà Hàng Hương Cau 2=Nhà Hàng Hương Cau 2\n684ba23363c01bc71309f825-Kingfood=Kingfood\n684a6d285caf3ca2f901810a-Teamax=Teamax\n684a4a61c5588ab4e90aded8-POLA COFFEE & TEA=POLA COFFEE & TEA\n6849665247df3e85fa0cb3e7-Beer Đức Jaderborner=Beer Đức Jaderborner\n6849542fae03cd62b40f47bf-Cây Cột Điện Coffee Books=Cây Cột Điện Coffee Books\n6849540dd6f5fd1a9f032fcb-Cây Cột Điện Coffee Books=Cây Cột Điện Coffee Books\n68494b00dc5d7248d00adaf0-Passio Coffee To Go=Passio Coffee\n68494ae93a4722399e01e3bd-Passio Coffee=Passio Coffee\n6847eafb54a62352700c5b2c-Trà Sữa Thái Lan Songkran=Trà Sữa Thái Lan Songkran\n6847e2fcd1ba7916850e6096-Saigon Centre=Saigon Centre\n6847a6b06597efdf5d095b02-HIGHLANDS COFFEE - ĐẠI LỘ BÌNH DƯƠNG=HIGHLANDS COFFEE\n6846e875b9f8d1fee601665a-Meta Cafe=Meta Cafe\n68468c156d2c3f8b00039270-HE Tea & Coffee=HE Tea & Coffee\n68468bd1f6614a4cde0a881b-HE Tea & Coffee=HE Tea & Coffee\n68468a18679da347af0b9823-HE Tea & Coffee=HE Tea & Coffee\n684689fb714b3a51ce07cd04-HE Tea & Coffee=HE Tea & Coffee\n684689af4d4690a18c077cc6-HE Tea & Coffee=HE Tea & Coffee\n684689923cd32ac85704ec59-HE Tea & Coffee=HE Tea & Coffee\n6846896dcc27367f620f2f58-HE Tea & Coffee=HE Tea & Coffee\n684689516a227f160305a329-HE Tea & Coffee=HE Tea & Coffee\n6846890c0cf7b50d490d4734-He Tea & Coffee=He Tea & Coffee\n68465c3bfb8229b8ab0c8824-Dtel Office=Dtel Office\n68465a78dd86dd042c0a894e-BlueTechX Office=BlueTechX Office\n68443802dae5d17a8c0762ce-Nhi Đồng 315 Và Tiêm Chủng=Nhi Đồng 315 Và Tiêm Chủng\n6843ed7ec67491a4b30fbef0-Hiên Nhà Coffee=Hiên Nhà Coffee\n6843ed38eb8376415e008eb7-Hiên Nhà=Hiên Nhà\n```',
 '```\n6843ec4e266bb7a40b07761b-Hiên Nhà Coffee=Hiên Nhà Coffee\n6843cc232e86e5cbcb0d3e62-Hủ Tiếu Ghẹ Muối Ớt Đỏ=Hủ Tiếu Ghẹ Muối Ớt Đỏ\n6843983ecb9dd8b8df0ba16a-Trường Đại Học Khoa Học Tự Nhiên TP HCM=Trường Đại Học Khoa Học Tự Nhiên TP HCM\n68430d23bb5138814f0406a8-Tiệm Sa Chuỷ 80s=Tiệm Sa Chuỷ 80s\n6842eb82101bca96ac019df5-Lotteria Thường Tín=Lotteria\n6842eb718714eb32ee0147c7-Loterria Thường Tín=Loterria\n6842c0c06087b08ee609fc46-Gd=Gd\n68427bdbd317116bd30e2e27-Saigon Innovation Hub - SIHUB=Saigon Innovation Hub - SIHUB\n6842431977516023f20a5f22-F Coffer=F Coffer\n6841b6ffa3675578860183c5-Gon Cake=Gon Cake\n6841b698752f1f0b2b09f162-Gon Cake=Gon Cake\n6841b66aec3d8cc7ac0a2fc3-Gôn Cake=Gôn Cake\n6841a2fac07a7554a30fc6a7-Tra Sữa Viên Viên=Trà Sữa Viên Viên\n68413f238e92e677a8062311-Nhà Hàng Đức Dương Palace=Nhà Hàng Đức Dương Palace\n68401e12f664053102030fd3-Hội Trường Trịnh Công Sơn - Trường Đại Học Văn Lang=Hội Trường Trịnh Công Sơn - Trường Đại Học Văn Lang\n68400b987f3f136dd20cc69b-Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI - Diamond Brand Institute)=Công Ty Cổ Phần Học Viện Thương Hiệu Kim Cương (DBI - Diamond Brand Institute)\n683eb363e302ccd57307be52-MetaUni=MetaUni\n683d98e5296533f6b208d42a-Golden Bakery 2=Golden Bakery 2\n683d98abde408c11180fcbac-Golden Bakeryvungx=Golden Bakeryvungx\n683d6e866c8412d2890a5506-Hongkong Baley=Hongkong Baley\n683c597e4c2ed87da5005283-Kingfoodmart Era Town=Kingfood Mart\n683c596679098ab3020d7379-Kingfood Mart Era Town=Kingfood Mart\n683c58724e514b86ec0d0506-Ông Chủ Nhỏ=Ông Chủ Nhỏ\n683c544e5b6b821e1608c857-Cà Phê ông Bầu Quận 7=Cà Phê ông Bầu Quận 7\n683c4c9d58e39aead4098c92-Vĩnh Phát Dimsum=Vĩnh Phát Dimsum\n683bdab0d2df8ae62405966b-Kohaku=Kohaku\n683acfc0a8d4f18de1012e12-Bách Gia Tinh Hoa=Bách Gia Tinh Hoa\n683ab8a2428268c54306b0d3-BGTH - Vương Gia=BGTH\n683ab87f89174d5d560e8953-BGTH - Trịnh Gia=BGTH\n683ab8549abbd61a8509cf1b-BGTH - Tạ Gia=BGTH\n683ab797e66aa434c50b6414-BGTH - Phan Gia=BGTH\n683ab778c9f032db410d8f21-BGTH - Mai Gia=BGTH\n683ab75ee8e19aced80b5bd0-BGTH - Lý Gia=BGTH\n683ab737ff1b00948b035d7c-BGTH - Hà Gia=BGTH\n683ab6d4f052541029038e2b-BGTH - Đào Gia=BGTH\n683ab6b09a42d108d70c5b56-BGTH - Cao Gia=BGTH\n683ab65f225aa4f5c30ca27b-BGTH - Vân Gia=BGTH\n683ab630f73dbbd1a105f2e7-BGTH - Trương Gia=BGTH\n683ab5dae6ee4af69e050d77-BGTH - Tô Gia=BGTH\n683ab5811bbb06973f0e7db7-BGTH - Ngô Gia=BGTH\n683ab4cef3ddb7e29b0c243e-BGTH - Lưu Gia=BGTH\n683ab49c38752ac8a4068eeb-BGTH - Lê Gia=BGTH\n683ab4816ae159015101025c-BGTH - Hồ Gia=BGTH\n683ab461c3cbe7e57003b0b9-BGTH - Đinh Gia=BGTH\n683ab4042e1683525b0992c0-BGTH - Chử Gia=BGTH\n683ab3e7bbca5ce1cf04d7fc-BGTH - Đặng Gia=BGTH\n683ab3c4406571cb2c0f61cb-BGTH - Từ Gia=BGTH\n683ab20c1533eceeb60cdff0-BGTH - Thiều Gia=BGTH\n683ab1dbc133b842d400c85b-BGTH - Phùng Gia=BGTH\n683ab19a368db808ec080fe6-BGTH - Nguyễn Gia=BGTH\n```',

---
4.Xử lý dữ liệu được label
---

In [ ]:
def parse_response_to_df(response_text: str) -> pd.DataFrame:
    """
    Parse response string thành DataFrame có cột StoreID, StoreName, BrandID.
    """
    rows = response_text.strip().split("\n")  # tách từng dòng
    parsed_data = []

    for row in rows:
        if "=" not in row:
            continue  # bỏ qua dòng không hợp lệ
        left, brand_id = row.split("=", 1)
        if "-" in left:
            store_id, store_name = left.split("-", 1)
        else:
            store_id, store_name = left, ""
        parsed_data.append([store_id.strip(), store_name.strip(), brand_id.strip()])

    return pd.DataFrame(parsed_data, columns=["StoreID", "StoreName", "BrandName"])

In [ ]:
print(len(gemini_responses))

270

In [ ]:
# Gom toàn bộ response sau khi clean
all_clean_texts = []

for res in gemini_responses:
    if isinstance(res, str):  # tránh lỗi nếu có phần tử không phải string
        clean_text = res.replace("```", "").strip()
        if clean_text:  # bỏ qua chuỗi rỗng
            all_clean_texts.append(clean_text)

# Gộp tất cả lại thành 1 chuỗi (có xuống dòng phân cách)
final_clean_text = "\n".join(all_clean_texts)

In [ ]:
# Parse toàn bộ vào DataFrame
df_labeled = parse_response_to_df(final_clean_text)

In [ ]:
print(df_labeled.head(10))

                    StoreID                                   StoreName  \
0  6738c2a46b16d0f45b0614b6                                Som Tum Thai
1  6738c1ec0f160484310b4b08                         Nhà Sách Phương Nam
2  6738c1d05065cb1cb00399cf                             Highland Coffee
3  6738c1401a6b19f2710ae7fa                                       Zmart
4  6738c1291a6b19f2710ae7da                                    Circle K
5  6738c02ac262e196a204aaee                      UNIQLO - VAN HANH MALL
6  6738bff7aad98d5b94057dec                            Nguyễn Phong Sắc
7  6738bfad1a6b19f2710ae653                      Lim Coffee - Quỳnh Lưu
8  6738bf91b8b45ad4eb0b9299  Phúc Long Coffee & Tea - 33 Nguyễn Văn Bảo
9  6738bf8b45b6646ed50b855a                              Go Thái Nguyên

                BrandName
0            Som Tum Thai
1     Nhà Sách Phương Nam
2        Highlands Coffee
3                   Zmart
4                Circle K
5                  Uniqlo
6        Nguyễn Phong Sắc
7              Lim Coffee
8  Phúc Long Coffee & Tea
9                      GO

In [ ]:
# Export the df_label to a new Excel file
output_file_path = 'branded_data_201_290.xlsx'
df_labeled.to_excel(output_file_path, index=False)

print(f"Merged DataFrame successfully exported to {output_file_path}")

Merged DataFrame successfully exported to branded_data_201_290.xlsx

In [ ]:
# Filter the DataFrame to show rows where BrandName is 'Thương hiệu khác'
df_thuong_hieu_khac = df_labeled[df_labeled['BrandName'] == 'Thương hiệu khác']

# Display the filtered DataFrame
display(df_thuong_hieu_khac)

Empty DataFrame
Columns: [StoreID, StoreName, BrandName]
Index: []

In [ ]:
len(df_labeled)

4998

In [ ]:
# Merge df_labeled into df based on 'ID' and 'StoreID'
df_merged = df.merge(df_labeled[['StoreID', 'BrandName']], left_on='ID', right_on='StoreID', how='left')

# Drop the redundant 'StoreID' column
df_merged = df_merged.drop('StoreID', axis=1)

# Display the first few rows of the merged DataFrame to verify
display(df_merged.head())

# Export the merged DataFrame to a new Excel file
output_file_path_merged = 'merged_branded_data.xlsx'
df_merged.to_excel(output_file_path_merged, index=False)

print(f"Merged DataFrame successfully exported to {output_file_path_merged}")

,ID,Trùng với ID,Tên,Lĩnh vực ID,Lĩnh vực Name,Tỉnh thành ID,Tỉnh thành Name,Brand ID,Brand Name,Địa chỉ,BrandName
0,68d2de42cc9361574c028970,NaN,CGV Saigonres Nguyen Xi,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,CGV
1,68d2db50ea440018b406378d,NaN,Lotte Cinema Gò Vấp,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Lotte Cinema
2,68d2da3aa5272c273c0d4ec2,NaN,Dabaco Cinema Quế Võ,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Dabaco Cinema
3,68d2d9e2277ef09e45011bcc,NaN,Rạp Chiếu Phim Beta Thanh Hóa,14.0,Rạp phim,5016fd6c7f8b9ac842000036,Thanh Hóa,NaN,NaN,NaN,Rạp Chiếu Phim Beta Thanh Hóa
4,68d2c6e5946e8664910eb20d,NaN,Liberty Centre Point,NaN,NaN,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Liberty Centre Point

Merged DataFrame successfully exported to merged_branded_data.xlsx

In [ ]:
# List of file paths to merge
file_paths = [
    '/content/branded_data_1_100.xlsx',
    '/content/branded_data_101_200.xlsx',
    '/content/branded_data_201_290.xlsx'
]

# List to hold DataFrames from each file
dfs_to_merge = []

# Read each file and append its DataFrame to the list
for file_path in file_paths:
    try:
        df_temp = pd.read_excel(file_path)
        dfs_to_merge.append(df_temp)
        print(f"Đã đọc file: {file_path}")
    except FileNotFoundError:
        print(f"Lỗi: Không tìm thấy file {file_path}")
    except Exception as e:
        print(f"Lỗi khi đọc file {file_path}: {e}")

Đã đọc file: /content/branded_data_1_100.xlsx
Đã đọc file: /content/branded_data_101_200.xlsx
Đã đọc file: /content/branded_data_201_290.xlsx

In [ ]:
# Concatenate all DataFrames in the list
if dfs_to_merge:
    df_full = pd.concat(dfs_to_merge, ignore_index=True)

    # Display the first few rows of the merged DataFrame
    print("\nDataFrame sau khi ghép:")
    display(df_full.head())

    # Export the merged DataFrame to a new Excel file
    output_full_file_path = 'brand_full.xlsx'
    df_full.to_excel(output_full_file_path, index=False)

    print(f"\nDataFrame đã ghép thành công và lưu vào: {output_full_file_path}")
else:
    print("Không có DataFrame nào để ghép.")

DataFrame sau khi ghép:

,StoreID,StoreName,BrandName
0,68d2de42cc9361574c028970,CGV Saigonres Nguyen Xi,CGV
1,68d2db50ea440018b406378d,Lotte Cinema Gò Vấp,Lotte Cinema
2,68d2da3aa5272c273c0d4ec2,Dabaco Cinema Quế Võ,Dabaco Cinema
3,68d2d9e2277ef09e45011bcc,Rạp Chiếu Phim Beta Thanh Hóa,Rạp Chiếu Phim Beta Thanh Hóa
4,68d2c6e5946e8664910eb20d,Liberty Centre Point,Liberty Centre Point

DataFrame đã ghép thành công và lưu vào: brand_full.xlsx

In [ ]:
# Merge df with df_full based on 'ID' and 'StoreID'
# Using a left merge to keep all rows from the original df
df_merged = df.merge(df_full[['StoreID', 'BrandName']], left_on='ID', right_on='StoreID', how='left')

# Drop the redundant 'StoreID' column after merging
df_merged = df_merged.drop('StoreID', axis=1)

# Display the first few rows of the merged DataFrame to verify
print("DataFrame sau khi ghép BrandName:")
display(df_merged.head())

DataFrame sau khi ghép BrandName:

,ID,Trùng với ID,Tên,Lĩnh vực ID,Lĩnh vực Name,Tỉnh thành ID,Tỉnh thành Name,Brand ID,Brand Name,Địa chỉ,BrandName
0,68d2de42cc9361574c028970,NaN,CGV Saigonres Nguyen Xi,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,CGV
1,68d2de42cc9361574c028970,NaN,CGV Saigonres Nguyen Xi,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,CGV
2,68d2db50ea440018b406378d,NaN,Lotte Cinema Gò Vấp,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Lotte Cinema
3,68d2db50ea440018b406378d,NaN,Lotte Cinema Gò Vấp,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Lotte Cinema
4,68d2da3aa5272c273c0d4ec2,NaN,Dabaco Cinema Quế Võ,14.0,Rạp phim,5016fd6b7f8b9ac842000000,TP Hồ Chí Minh,NaN,NaN,NaN,Dabaco Cinema

In [ ]:
# Export the merged DataFrame to a new Excel file
output_file_path_merged = 'Du-Lieu-Place_branded.xlsx'
df_merged.to_excel(output_file_path_merged, index=False)

print(f"\nDataFrame đã ghép và lưu thành công vào: {output_file_path_merged}")

DataFrame đã ghép và lưu thành công vào: Du-Lieu-Place_branded.xlsx